### ISSUE TITLE
Allow to run Source actions on a set of projects from Project Explorer even if one of them is not a Java project

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#102]
Follow-up for https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/34

#34 allows to run source actions from the project explorer which is great. One missing feature is that this is also possible if the set of project contains one or more non Java projects but at least one Java project. This is currently suported by the Package explorer.

To test: 

Create three projects, two Java projects, one of type General.
Open Package Explorer, select all projects, right-click -> You see the Source options
Open Project Explorer, select all projects, right-click -> You  DO NOT see the Source options

@jjohnstn can you also have a look at this one?

**Comment by jjohnstn** [comment]
Hi @vogella I tracked down the problem to CommonActionProviderDescriptor in o.e.ui.navigator.  It checks all the objects in a multi-selection and fails when any of them is not enabled.  To fix this, I have proposed a fix that adds a new attribute for an actionProvider (multiprojectEnable).  When set to "any", if one or more of the selected projects is enabled, then the action is enabled.  I have created a PR: https://github.com/eclipse-platform/eclipse.platform.ui/pull/222 for this.  If you can, please take a look.  From there, it is a simple fix for JDT to add the multiprojectEnable attribute for the Java action provider that supports the Source options.  I have tested and this works.  If you don't have time to look at it then it will have to be proposed for M3 or next release.  If you have a better solution, by all means, I'm all ears.
