### ISSUE TITLE
Outline view (Ctrl+O) is not on the center of the screen when running eclipse on Ubuntu 23.10(Wayland)

### ISSUE THREAD

**Issue by s4gh** [eclipse-jdt/eclipse.jdt.ui#1033]
Hello,

Version information:
Build id: 20231201-2043
Version: 2023-12 (4.30.0)

OS:
Ubuntu 23.10

Outline view (Ctrl+O) is misaligned. It is not in the center of the screen. See screenshot.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/2587238/a44d4785-f666-4e9f-9aa5-86857dd6817a)

Similarly, Ctrl+F (Find and Replace) is also misaligned. While popup triggered by "Ctrl+H" is positioned correctly.

at the same time other popups e.g. Ctrl+N are correctly aligned
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/2587238/41602c3e-6a9f-44df-8d9c-41aefee291ec)

**Comment by sveryovka** [comment]
@nlisker  thank you for suggestion. Unfortunately this does not work"Remember Location" does not solve the problem. I clicked "down" arrow next to search box, enabled "Remember Location" drag popup to the center of the scree, close it. Next time on "Ctrl+O" window is still misaligned.

This is a clean installation of Ubuntu and Eclipse. And on this fresh clean installation some popups are correctly aligned (Ctrl+H or Ctrl+P, Ctrl+L) but others (like Ctrl+O) are aligned incorrectly. And "Remember Location" does not work for misaligned popups.  And I think that moist people don't even know about option to remember location.

Serhiy

**Comment by sveryovka** [comment]
There is difference in how popups produced by "Ctrl+O" and for example "Ctrl+H" behave. When I click "Ctrl+H" or "Ctrl+L" the IDE window below popup is grayed out. The popup is in the center of the screen and you cannot actually move it. 
However, outline popup triggered by "Ctrl+O" is movable and does not cause IDE window below popup to gray out. 

For me, personally, incorrect alignment of "Ctrl+O" popup is much bigger annoyance compared to the possibility of loosing ability to drag this popup. To be honest I never actually move "outline view" popup.

**Comment by akurtakov** [comment]
This is SWT limitation https://github.com/eclipse-platform/eclipse.platform.swt/issues/790
