### ISSUE TITLE
Code cleanup to switch expression doesn't handle comments correctly

### ISSUE THREAD

**Issue by cyril-steimer** [eclipse-jdt/eclipse.jdt.ui#107]
While testing the fix for https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/106, another issue appeared when applying the clean for converting switch statements to switch expressions in our code. The following code can be used to easily reproduce the issue:

```java
private static boolean isOne (int value) {
    switch (value) {
        case 1:
            // Some comment
            return true;
        default:
            return false;
    }
}
```

The comment is then wrongly merged with `true` after the cleanup:

```java
private static boolean isOne (int value) {
    return switch (value) {
        case 1 -> // Some comment true;
        default -> false;
    };
}
```

**Comment by jjohnstn** [comment]
Thanks for catching this.  I'll fix it ASAP and add to the original PR.
