### ISSUE TITLE
imports not sorted ascending anymore

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1088]
When i organize imports on NewJavaProjectWizardPageOne 
"org.eclipse.jdt.launching." is put in front of 
"org.eclipse.jdt.internal"

eclipse.buildId=4.31.0.I20240116-1800
java.version=21.0.1
i have not seen that before.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/51790620/a3aa60f2-76e4-4e79-8ce0-7b8537329183)

**Comment by jjohnstn** [comment]
@jukzi This is working as set up by the project settings for the org.eclipse.jdt.ui project.  If you look at the Preferences you will find a page for Organize Imports where you can specify groups that organize imports is supposed to group imports into in the given order.  If you look at project specific settings, you will see a set of groups set up for org.eclipse.jdt.ui and that is what it is using to define how to sort the imports.

**Comment by jjohnstn** [comment]
BTW: according to git blame, the group ordering for o.e.jdt.ui was set by Dani Megert in 2008

**Comment by jukzi** [comment]
@jjohnstn thanks for analysis. I did not know that feature (and don't get its value). The configuration feels bad
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/69410ffc-2177-48f4-a9e9-0811cdfc8283), but we can close the issues as  "works as configured"
