### ISSUE TITLE
Problems with "While loop to foreach loop conversion "

### ISSUE THREAD

**Issue by HannesWell** [eclipse-jdt/eclipse.jdt.ui#109]
I just applied the enhanced [Convert while loops to enhanced for loops](https://www.eclipse.org/eclipse/news/4.25/jdt.php#while-to-enhanced-for) clean-up introduced in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/55 to the equinox code base (The unchanged result is at https://github.com/eclipse-equinox/equinox/pull/45) and encountered the following problems. The option "Only if loop variable used" was enabled and all other clean-ups were disabled.

- [x] Loop variable of `Map.entrySet()` iterator is not typed correctly, the second argument is missing:
```
	public static void before() {
		Map<String, Object> map = Map.of("Hello", new Object());
		Iterator<Entry<String, Object>> iterator = map.entrySet().iterator();
		while (iterator.hasNext()) {
			Entry<String, Object> entry = iterator.next();
			System.out.println(entry);
		}
	}

	public static void after() {
		Map<String, Object> map = Map.of("Hello", new Object());
		for (Entry<String> entry : map.entrySet()) {
			System.out.println(entry);
		}
	}
```
- [x] The import of java.util.Iterator is not always removed if not used anymore. I noticed it is removed most often but in the equinox-code base for [ModuleDatabase.java](https://github.com/eclipse-equinox/equinox/pull/45/files#diff-9c1e3f220b7f4b01c47e22ccf78778c76428f9575afa32a303523de97442f542) the clean-up fails to remove it.
- [x] The conversion of a counting-loop over a list fails if the current entry is assigned to two different variables (although I suspect this is a bug in the corresponding code that the second variable is assigned from the same list). If two separate lists use the same counter-variable the clean-up correctly does nothing:
```
	private void before1() {
		List<String> list1 = List.of("");
		for (int i = 0; i < list1.size(); i++) {
			String s1 = list1.get(i);
			String s2 = list1.get(i);
			System.out.println(s1 + "," + s2);
		}
	}

	private void after1() {
		List<String> list1 = List.of("");
		for (String s1 : list1) {
			System.out.println(s1 + "," + s2);
		}
	}

	private void before2() {
		List<String> list1 = List.of("");
		List<String> list2 = List.of("");
		for (int i = 0; i < list1.size(); i++) {
			String s1 = list1.get(i);
			String s2 = list2.get(i);
			System.out.println(s1 + "," + s2);
		}
	}

	private void after2() {
		List<String> list1 = List.of("");
		List<String> list2 = List.of("");
		for (int i = 0; i < list1.size(); i++) {
			String s1 = list1.get(i);
			String s2 = list2.get(i);
			System.out.println(s1 + "," + s2);
		}
	}
```

@carstenartur and @jjohnstn maybe you can have a look at this. Thanks in advance.

**Comment by jjohnstn** [comment]
Regarding the Iterator not being removed, there is a default cleanup for unused imports that gets run after the For loop and While loop cleanups.  Did you turn this off for that project or use a cleanup template that has turned this off?

**Comment by HannesWell** [comment]
> Regarding the Iterator not being removed, there is a default cleanup for unused imports that gets run after the For loop and While loop cleanups. Did you turn this off for that project or use a cleanup template that has turned this off?

I intentionally turned it off and only run the enhanced-loop-conversion clean-up.
The following screenshot was the setting, then I hit finish and pushed the result as it is to https://github.com/eclipse-equinox/equinox/pull/45

![grafik](https://user-images.githubusercontent.com/44067969/174899427-98fe145b-1529-4a22-9f1c-91d37c5c2996.png)

Interestingly if I add `Remove unused imports` and apply the (then) three clean-ups to the previous state, the result is the same and the import is still there. However if I run the clean-up with still the three ones active a second time the import is removed.
So I suspect that, if `Remove unused imports` is added explicitly it runs before the loop clean-up

**Comment by jjohnstn** [comment]
I should have stated "Organize Imports" instead of Unused imports.  According to JDT UI plugin.xml, the ImportsCleanUp (Organize Imports) should run after the ConvertLoopCleanUp and UseIteratorToForLoopCleanUp.  However, so should have the Unused Imports clean up so I'll have to take a look.  Try the Organize Imports cleanUp which is a default.

**Comment by HannesWell** [comment]
> I should have stated "Organize Imports" instead of Unused imports. According to JDT UI plugin.xml, the ImportsCleanUp (Organize Imports) should run after the ConvertLoopCleanUp and UseIteratorToForLoopCleanUp. However, so should have the Unused Imports clean up so I'll have to take a look. Try the Organize Imports cleanUp which is a default.

Using "Organize Imports" indeed removes that import on the first run.
But I noticed that in other files imports that are unused after the loop-conversion are removed even without "Organize Imports" or "Remove unused imports" being enabled. So I suspect that in general there is a defection if the import becomes unused by applying the conversion. Therefore my guess is that the detection if the import becomes unused does not work in that case. Maybe some counter or similar is not set correctly.

In case you want the exact class it is [org.eclipse.osgi.container.ModuleDatabase.java](https://github.com/eclipse-equinox/equinox/pull/45/files#diff-9c1e3f220b7f4b01c47e22ccf78778c76428f9575afa32a303523de97442f542) in https://github.com/eclipse-equinox/equinox/pull/45

**Comment by jjohnstn** [comment]
Ok thx for reporting back.  I'll take a look.

**Comment by jjohnstn** [comment]
Regarding the failure to remove the import of Iterator, please open a separate issue.  I reproduced with a simple test that has one for loop using iterator and one while loop using iterator in the same compilation unit.  Isolating either loop works by themselves.  My guess is that somehow the two cleanups aren't communicating properly so that when the ImportRemover is called on the second cleanup run, it still thinks the other loop still needs to use the iterator.  Most people won't run into this as they will have Organize Imports defaulted for them.

public class TestForLoop {

	public void before1() {
		Map<List<? extends Date>, Date[]> map3 = new HashMap<>();
		Iterator<Entry<List<? extends Date>, Date[]>> iterator3 = map3.entrySet().iterator();
		while (iterator3.hasNext()) {
			Entry<List<? extends Date>, Date[]> entry = iterator3.next();
			System.out.println(entry);
		}
		Map<Date[], Date[]> map = Map.of(new Date[0], new Date[1]);
		for (Iterator<Entry<Date[], Date[]>> iterator = map.entrySet().iterator(); iterator.hasNext();) {
			Entry<Date[], Date[]> entry = iterator.next();
			System.out.println(entry);
		}
	}
	
}

**Comment by HannesWell** [comment]
> Regarding the failure to remove the import of Iterator, please open a separate issue. I reproduced with a simple test that has one for loop using iterator and one while loop using iterator in the same compilation unit. Isolating either loop works by themselves. My guess is that somehow the two cleanups aren't communicating properly so that when the ImportRemover is called on the second cleanup run, it still thinks the other loop still needs to use the iterator. Most people won't run into this as they will have Organize Imports defaulted for them.

That sounds like an explanation. But do you think this is still necessary, because with your latest fix in jdt.ui available in the I-build from tonight (i.e. I20220624-1800) the import is correctly removed. So maybe your latest enhancement also fixed that (unintentionally?).

**Comment by HannesWell** [comment]
Closed this issue since all initially reported problems with the equinox code base are fixed.
Thanks again!

**Comment by HannesWell** [comment]
> > Regarding the failure to remove the import of Iterator, please open a separate issue. I reproduced with a simple test that has one for loop using iterator and one while loop using iterator in the same compilation unit. Isolating either loop works by themselves. My guess is that somehow the two cleanups aren't communicating properly so that when the ImportRemover is called on the second cleanup run, it still thinks the other loop still needs to use the iterator. Most people won't run into this as they will have Organize Imports defaulted for them.
> 
> That sounds like an explanation. But do you think this is still necessary, because with your latest fix in jdt.ui available in the I-build from tonight (i.e. I20220624-1800) the import is correctly removed. So maybe your latest enhancement also fixed that (unintentionally?).

OK with other clean up configuration that issue showed again and I was also able to reproduce it with a simple test.
Created https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/121 to track that.

**Comment by jjohnstn** [comment]
Thanks Hannes.
