### ISSUE TITLE
OwningAnnotationsConfigurationDialog_title missing

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1094]
logged  for example during MarkOccurrenceTest
`Warning: NLS missing message: OwningAnnotationsConfigurationDialog_title in: org.eclipse.jdt.internal.ui.preferences.PreferencesMessages
`
@stephan-herrmann  regression from 417ba9ad1af488d8b40ab87445cb45130c98550d

**Comment by stephan-herrmann** [comment]
Thanks, @jukzi
