### ISSUE TITLE
Override covariant methods

### ISSUE THREAD

**Issue by jonbarril** [eclipse-jdt/eclipse.jdt.ui#1152]
Add support to generate covariant return of methods. Currently, if you have a lot of methods this is a real pain, even using Source->Override/Implement methods -- lots of cleanup needed.

Perhaps there could be an additional option: Source->Override Covariant Return, or a checkbox on the Override/Implement dialog for Covariant Return. In any case, the selected methods would be overridden with the host class return type, a return cast to the type, and no TODO line.

Thanks
--jon

**Comment by jukzi** [comment]
If you could provide a PR it would be welcome - please reopen. otherwise its unlikey someone else will step in

**Comment by jonbarril** [comment]
What is a PR?

**Comment by jukzi** [comment]
a Pull request. A code commit that we can change in eclipse IDE to improve it
