### ISSUE TITLE
Jenkins ECJ plugin detects way too less warnings

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1169]
My workspace shows 962 warnings for JDT.UI repo, but jenkins only shows two
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-Github/job/master/2/eclipse/
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/533faf8d-cdbe-469b-82fd-90cd2c21c389)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/6f00821e-b30b-4264-99e3-fd66233bdf09)

 @laeubi any idea?

**Comment by laeubi** [comment]
One thing I ave noticed in the past is that if one has some project specific preference and then there is a new preference key (not mentioned in the existing one) then it always uses the workspace default (what can differ).

So to analyze this one needs a reference to one project and one file there where a warning as shown that is configured in that project preference and is not shown at Jenkins.

To prove this one then could for example change it from warning > error in this project to see that it is actually picked up (e.g. fails the build).
