### ISSUE TITLE
ContextMenue: "References" missing

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1181]
I badly miss Reference Search in the context menu
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/0fe8b9e2-0868-417b-8b10-6f51fc252c52)
seems like it moved into a submenu
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/11638b99-d7d8-409a-8ac2-d019f372402a)

but i am still confused and miss it at the ancient spot, because i was very much used to it

Also the key accelerator for"Occurrences in File/Identifier" is at the wrong spot (and it seems dump to have a submenu for a single entry)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/24d3c369-7722-45a3-a450-b66ac5a6d481)

**Comment by iloveeclipse** [comment]
Sorry, I'm not sure I understood if the state in screenshot is what you are expecting or what you are not expecting to see?
I see same menus in  I20240207-1800. So what's wrong?

**Comment by jukzi** [comment]
The first screenshot is from an old version.
The other screenshots are from my current worspace.
Seems to be changable with preference "Use reduced search menu" (but i can not remember i changed it manually)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/6e68d2b5-3a58-49db-9dbe-7882c81bec8e)

**Comment by iloveeclipse** [comment]
Oomph did it for you may be? What happens if you reset to defaults?

**Comment by jukzi** [comment]
defaults seem to be still "reduced"
