### ISSUE TITLE
Clean Up... bad code generated

### ISSUE THREAD

**Issue by gnl42** [eclipse-jdt/eclipse.jdt.ui#1197]
While cleaning up the code in mylyn I came across a number of code snippets that would not compile after being cleaned up.

[cleanUpErrors.zip](https://github.com/eclipse-jdt/eclipse.jdt.core/files/14277056/cleanUpErrors.zip)

George

**Comment by jjohnstn** [comment]
Hi @gnl42 In one of your tests: BadInstanceOfExpression, you are using the wrong AND operator.  You should have used && instead of &.  There is still a compiler bug I will open, but switching to the proper AND before using the cleanup will fix your problem.

**Comment by gnl42** [comment]
@jjohnstn Thanks. It's existing code that I was cleaning up

**Comment by jjohnstn** [comment]
> @jjohnstn Thanks. It's existing code that I was cleaning up

Ok, I'll open a compiler issue about the parsing, but you or somebody who is a committer should still fix the original code - it is not a valid place for a bit-wise and

**Comment by jjohnstn** [comment]
With all the PRs merged, I am closing this as completed.
