### ISSUE TITLE
MAKE_VARIABLE_DECLARATION_FINAL doesn't work for multi-catch

### ISSUE THREAD

**Issue by lbrayner** [eclipse-jdt/eclipse.jdt.ui#1224]
Consider the following code:

```java
public class FinalExceptions {

  public static void main(String[] args) {
    Object token = new Object();

    try {
      token.wait();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    try {
      token.wait();
    } catch (IllegalMonitorStateException | InterruptedException e) {
      e.printStackTrace();
    }
  }
}
```

IProposalRelevance.MAKE_VARIABLE_DECLARATION_FINAL has no effect on the multi-catch form.

https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3075

**Comment by jukzi** [comment]
The description misses steps to reproduce. Please add information how to reprdouce and what the expectation is.

**Comment by lbrayner** [comment]
My mistake: **The parameter e of a multi-catch block cannot be assigned**. Closing this.
