### ISSUE TITLE
Add CTRL+Click "Open Call Hierarchy" Action on classes

### ISSUE THREAD

**Issue by flori-schwa** [eclipse-jdt/eclipse.jdt.ui#1231]
In #575 new functionality was implemented, that adds a quick way of opening the call hierarchy on methods and fields via CTRL+Click. However this functionality is missing on classes, where the Call hierarchy shows the call hierarchy of all constructors (or the default constructor).

CTRL+Hover on Constructor: The "Open Call Hierarchy" Action is properly displayed
![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/17676856/0408da22-53ab-4a94-886d-ae92c8233c11)

CTRL+Hover on Class Declaration: The "Open Call Hierarchy" Action is missing
![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/17676856/42901e67-5cb6-4341-9352-adbfc4ec3f91)

Call Hierarchy View when opened via Right Click -> Open Call Hierarchy on Class Declaration: In my opinion, this view should also be openable using CTRL+Click "Open Call Hierarchy" on classes.
![grafik](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/17676856/4cfb9b98-abbf-48c9-9502-425b9c35186d)

**Comment by iloveeclipse** [comment]
Contributions are welcome.

**Comment by RedeemerSK** [comment]
#1367

**Comment by iloveeclipse** [comment]
@RedeemerSK : thanks for the patch!

Could you please create a PR with a N&N entry for this, repository is https://github.com/eclipse-platform/www.eclipse.org-eclipse and an example of such entry is https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/163/

**Comment by RedeemerSK** [comment]
> @RedeemerSK : thanks for the patch!
> 
> Could you please create a PR with a N&N entry for this, repository is https://github.com/eclipse-platform/www.eclipse.org-eclipse and an example of such entry is [eclipse-platform/www.eclipse.org-eclipse#163](https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/163)

Sorry for delay.
https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/167
