### ISSUE TITLE
Cleanup: "Convert String to TextBlock" breaks code

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1238]
for example on org.eclipse.jdt.core.tests.rewrite.describing.ImportRewriteTest.testAddImports6() it produces
`buf cannot be resolved`
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/f5b216d3-ab84-4d02-bd1a-d55e02ad142d)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/de179bf4-3352-41c2-bd3d-f562f0b1dcd4)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/7548a66d-0384-43ef-82a1-8f0f8e150d9e)

**Comment by jukzi** [comment]
on org.eclipse.jdt.core.tests.compiler.regression.TextBlockTest.testBug565639_6()
`Syntax error on token """", delete this token`
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/6466c628-b197-4fea-ab56-ba42e0183f3c)

**Comment by jukzi** [comment]
Reopening because cleanup still not working on ImportRewriteTest with org.eclipse.jdt.ui 3.32.100.v20240309-1530
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/b18733c9-f77c-4b24-8d9c-7935a9625920)

Note that there are still multiple issues left when applying this cleanup to jdt.ui tests:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/9fdfc628-5130-440f-b95c-7ca0902fa526)
for example:
org.eclipse.jdt.ui.tests.core.ImportOrganizeTest.testStaticImports1(): str86 cannot be resolved to a variable 
org.eclipse.jdt.text.tests.contentassist.CodeCompletionTest.testOverrideCompletion4(): Duplicate local variable str
org.eclipse.jdt.ui.tests.quickfix.AssistQuickFixTest1d8.testSurroundWithTryWithResource_05(): bufOrg cannot be resolved
...

**Comment by jjohnstn** [comment]
There is still a problem with name collision (where the function uses str).

**Comment by jjohnstn** [comment]
Ok, all tests mentioned above in last comment convert correctly and I verified they ran successfully.  If you find something in another test, please open a new issue.  Thanks for submitting as there were multiple issues found.  I saw you had a partial text block conversion PR for the tests.  I might recommend re-running as some of the later fixes have made the conversion better (e.g. name choices of variables - not continuously incrementing over multiple methods and also use of single escape character for trailing white-space).

**Comment by jukzi** [comment]
I am sorry to say cleanup still fails with `Duplicate local variable buf` on cleaning up
```
org.eclipse.jdt.ui.tests.quickfix.LocalCorrectionsQuickFixTest.testCreateNewObjectProposal_6(),
org.eclipse.jdt.ui.tests.quickfix.NullAnnotationsQuickFixTest1d8.runBug531511Test(boolean, String, boolean, boolean),
org.eclipse.jdt.ui.tests.quickfix.UnresolvedTypesQuickFixTest.createSomeAmbiguity(boolean, boolean)
```

**Comment by jukzi** [comment]
And minor warning "The value of the local variable buf is not used"  (code was not good before) in 
org.eclipse.jdt.ui.tests.quickfix.UnresolvedVariablesQuickFixTest.testVarWithGenericType()
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/5b2f426a-48dc-4e37-9d60-2fee0b83a129)

**Comment by jjohnstn** [comment]
This is caused by the duplicate call to the constructor after the declaration.  The code supports finding a new constructor and all of its subsequent statements so it finds this on the 2nd constructor and the declaration gets untouched.  Will fix.

**Comment by jjohnstn** [comment]
Ok, another set of issues found.  Duplicate constructors are now ignored if none of them adds an initial string and their statements are grouped into only one conversion (i.e. they never start a new conversion opportunity).  Look-ahead for converting subsequent constructor Assignments to VariableDeclarationStatements has been made smarter to recognize when the initial declaration is not removed due to something not correct with converting the first concatenation.  I converted all 3 of the files in the last comment posted successfully.

**Comment by jukzi** [comment]
Somehow there are still "buf cannot be resolved" after cleanup jdt.ui tests
Namely cleaning org.eclipse.jdt.junit.tests.JUnitTestFinderTest.testTestCase() 
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/0880ca9f-ce07-4387-9480-e40d5267f6b7)
and org.eclipse.jdt.ui.tests.core.AddImportTest.testAddImportStaticForSubclassReference()
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/a811e597-6ea7-4a65-ad71-e7f26b21c69e)

**Comment by jjohnstn** [comment]
This is a regression caused by my support of redundant constructors.  The next constructor is not being saved to be changed into a VariableDeclarationStatement.  Will fix shortly.
