### ISSUE TITLE
Cleanup: "Convert String to TextBlock" changes whitespaces!!

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1240]
See many failing tests after cleaning up some files:
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1239

for example
```
JdtTextTestSuite org.eclipse.jdt.text.tests.JavaAutoIndentStrategyTest.testSmartIndentAfterNewLine6
expected:<...esult {
    Good{
 [    ]
    }, Bad
}> but was:<...esult {
    Good{
 [    ]
    }, Bad
}>
```
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/d5612778-791a-4596-8ae2-d643d1dc8931)

```
JdtTextTestSuite org.eclipse.jdt.text.tests.JavaHeuristicScannerTest.testIndentation24
expected:< [ ]> but was:< []>
```

**Comment by jukzi** [comment]
maybe a problem with `\t` tabs ?
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/fd03dc68-08f7-499b-a226-e8c1871dead7)

**Comment by jjohnstn** [comment]
Thanks @jukzi This is a separate case from the others.  The input strings don't end with a newline but there is a special indent needed for the closing text block quotes.  The logic for no newlib was adding the end block quotes at the end of the last line.  This has to be handled by adding a line-continuation for the last line and then placing the closing text block quotes on a separate line so that all the previous lines are indented properly.  Will post PR shortly.  I converted both files above and verified they ran successfully.

**Comment by jjohnstn** [comment]
Closing as completed.  Both tests have been converted and run successfully with latest patches.

**Comment by jukzi** [comment]
I am sorry to say there are still failing tests after cleanup. See
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1239/3/testReport/
For example:
https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/PR-1239/3/testReport/junit/JdtTextTestSuite%20org.eclipse.jdt.text.tests/ArrayWithTempVarForLoopJavaContextTest/proposalsWithFieldAndParam/
```
expected:<[	for (int i = 0; i < strings.length; i++) {
		String string = strings[i];
		
	]}> but was:<[for (int i = 0; i < strings.length; i++) {
	String string = strings[i];
	
]}>
```

**Comment by jjohnstn** [comment]
Sigh..I'll look into it.

**Comment by jjohnstn** [comment]
Hi @jukzi I did a manual cleanup on the file and ran proposalsWithFieldAndParam and it works fine for me.  I also copied and pasted from your patch into the test file and again it worked for me locally.   Can you confirm by running the test locally to verify if you are seeing the same?

**Comment by jukzi** [comment]
confirmed. thats strange!
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/0746eb08-53af-43bc-aa1a-1605ccfd79a4)

**Comment by jukzi** [comment]
Maybe a bug in ECJ version used in the build?

**Comment by jukzi** [comment]
no. You have to run the cleanup on the whole bundle, then i ccan reproduce the error locally. May be a wrong string in any helper method

**Comment by jukzi** [comment]
The error happens in formating org.eclipse.jdt.text.tests.AbstractForLoopJavaContextTest.CU_POSTFIX
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/3fb7b900-7b42-44fb-9f42-c5ff6422ed11)

**Comment by jjohnstn** [comment]
Ok, thx.  There is a \s missing.  Will investigate.

**Comment by jjohnstn** [comment]
Alright, all errors verified.  There was a new unicode support error in JavadocTest.TestUnicode() where it was using \u005cn to represent a newline.   I think you don't want to convert that test because the only way to convert that string to a text block is to strip those unicode newlines (i.e. end newlines don't exist in the transformed string so the test itself won't have to handle them).

**Comment by jukzi** [comment]
The jdt.ui tests pass now, but there are 73 jdt.core tests that now fail after cleanup. See https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2182/1/#showFailuresLink
For example org.eclipse.jdt.core.tests.compiler.regression.ScannerTest.test030() because it's complicated escape sequence is converted wrong:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/8385c2b3-145c-4067-8ac8-8d0fa2e2797e)

```

junit.framework.ComparisonFailure: Unexpected failure.
----------- Expected ------------

------------ but was ------------
----------\n
1. ERROR in Test.java (at line 6)\r\n
	System.out.print(C.charAt(0) == '\n
');\r\n
	                                ^^\n
Invalid character constant\n
----------\n

---------------------- ----------
 expected:<[]> but was:<[----------\n
1. ERROR in Test.java (at line 6)\r\n
	System.out.print(C.charAt(0) == '\n
');\r\n
	                                ^^\n
Invalid character constant\n
----------\n
]>
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertStringEquals(TestCase.java:267)
	at org.eclipse.jdt.core.tests.junit.extension.TestCase.assertEquals(TestCase.java:242)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3563)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runTest(AbstractRegressionTest.java:3253)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1974)
	at org.eclipse.jdt.core.tests.compiler.regression.AbstractRegressionTest.runConformTest(AbstractRegressionTest.java:1971)
	at org.eclipse.jdt.core.tests.compiler.regression.ScannerTest.test030(ScannerTest.java:637)
```

**Comment by jjohnstn** [comment]
@jukzi This last problem was due to text blocks treatment of single quotes.  They were escaped in the original strings but should not be escaped in the text block, similar to double quotes.  I made a fix and verified the failing tests.
