### ISSUE TITLE
Cleanup: "Convert String to TextBlock" ignores StringBuilder constructor argument

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1267]
Cleaning up org.eclipse.jdt.core.tests.rewrite.describing.ASTRewritingTypeAnnotationsTest.testNameQualifiedTypeAnnotations()
results in "The value of the local variable contents is not used"
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/64126273-a19a-4901-8588-37b2e5eebde1)

**Comment by jjohnstn** [comment]
Closed as fixed via #1268
