### ISSUE TITLE
[critical] UI issues in latest i-builds start from 06-27

### ISSUE THREAD

**Issue by gayanper** [eclipse-jdt/eclipse.jdt.ui#127]
The first problem is it doesn't show items in the Open Type table
![image](https://user-images.githubusercontent.com/7471994/176373182-4e8ddbb5-2a43-48b4-98f0-e5e9977e7a41.png)

This works fine with i-build from 06-26

The second problem is characters type after content assist is not filtering the items.

![image](https://user-images.githubusercontent.com/7471994/176376450-9332cf20-5c3d-4006-aad1-6a25903421bf.png)

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/223.

Please verify if the https://github.com/eclipse-platform/eclipse.platform.swt/pull/231 fixes the problem, I haven't had time to do this yet.

**Comment by niraj-modi** [comment]
> See [eclipse-platform/eclipse.platform.swt#223](https://github.com/eclipse-platform/eclipse.platform.swt/issues/223).
> 
> Please verify if the [eclipse-platform/eclipse.platform.swt#231](https://github.com/eclipse-platform/eclipse.platform.swt/pull/231) fixes the problem, I haven't had time to do this yet.

Above PR fixes the root cause, just triggered below Eclipse IBuild:
I20220629-0540

**Comment by niraj-modi** [comment]
Verified with [I20220629-0540](https://download.eclipse.org/eclipse/downloads/drops4/I20220629-0540/) all broken views are back to normal:
![image](https://user-images.githubusercontent.com/92304759/176496116-55ea49bd-a29b-4518-ba8d-72ce2241d199.png)

Except for one minor scenario where-in empty table is not visible(unless we type something):
![image](https://user-images.githubusercontent.com/92304759/176496387-d20f5d00-835f-4d0b-88dd-784afa33102e.png)

Will fix this part as well shortly.

**Comment by niraj-modi** [comment]
With fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/223 verified in Build id: I20220629-1800.
We can close this issue now.

**Comment by gayanper** [comment]
Yes now its fixed, Thanks Niraj
