### ISSUE TITLE
Cleanup: "Convert String to TextBlock" deletes comments

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1273]
Java TextBlocks can not contain comments
https://stackoverflow.com/questions/70198251/comments-inside-text-block-in-java-17-is-that-possible
But they should not be silently deleted.

Possibilites: completely skip the refactoring for that string or concat several Textblocks with comments.
Example:
org.eclipse.jdt.core.tests.model.SearchTests.testSearchPatternCreation37() (which also fails after cleanup)
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/474459e1-bdf2-43ec-bc55-d54efb6d0a3c)

**Comment by jjohnstn** [comment]
Bug occurs because code didn't escape the last space before the end quotes.  I will fix shortly and will add check for line comments.
