### ISSUE TITLE
Java code editor syntax highlighting isn't working properly

### ISSUE THREAD

**Issue by dg444** [eclipse-jdt/eclipse.jdt.ui#1287]
Java code editor syntax highlighting isn't working properly since I installed Eclipse 2024-03.
The syntax highlighting comes and goes, usually with rows of black text on selected lines before normal hightlighting, and sometimes it is mix of black and colours for different words in same line (see 
![Java Syntax Highlight all black](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/165050571/9a1bde7d-2802-4ccd-9369-c473999b9534)
example screenshot). I cannot offer a way to reproduce, and can only note that there were no similar issues in Eclipse 2023-12 for same projects I'm currently working on. The java release version for my code is 21, today I have also tried "Java 22" support from Marketplace and same issue occurs.

**Comment by jukzi** [comment]
need info how to reproduce

**Comment by dg444** [comment]
Sorry - as I said this issue comes and goes on a Windows 10 PC. Since I logged this issue, I've replaced my PC and use Windows 11. copying the eclipse and workspace folders from old to new PC but have not seen the problem on Windows 11.

**Comment by jukzi** [comment]
closing as not reproducable
