### ISSUE TITLE
IllegalAccessError - tried to access protected method in org.eclipse.ltk.core.refactoring.Change

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1293]
In a Java project having an empty module-info.java file, create a JUnit 5 test class like this:

```
package p1;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class CTest {

	@Test
	void test() {
		fail("Not yet implemented");
	}

}
```

The project has JUnit 5 container in its Modulepath (in Java Build Path).

In the above test, the comile error at @Test provides a quick fix: 
Add 'requires org.junit.jupiter.api' to module-info.java file

Apply the quick fix. We get the following error in Error Log view and the quick fix doesn't work:

```
java.lang.IllegalAccessError: class org.eclipse.jdt.internal.ui.text.correction.proposals.AddModuleRequiresCorrectionProposal tried to access protected method 'org.eclipse.ltk.core.refactoring.Change org.eclipse.jdt.internal.ui.text.correction.proposals.AddModuleRequiresCorrectionProposalCore.createChange()' (org.eclipse.jdt.internal.ui.text.correction.proposals.AddModuleRequiresCorrectionProposal is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7f9fa387; org.eclipse.jdt.internal.ui.text.correction.proposals.AddModuleRequiresCorrectionProposalCore is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @16feb910)
	at org.eclipse.jdt.internal.ui.text.correction.proposals.AddModuleRequiresCorrectionProposal.createChange(AddModuleRequiresCorrectionProposal.java:42)
	at org.eclipse.jdt.ui.text.java.correction.ChangeCorrectionProposal.getChange(ChangeCorrectionProposal.java:339)
	at org.eclipse.jdt.ui.text.java.correction.ChangeCorrectionProposal.performChange(ChangeCorrectionProposal.java:132)
	at org.eclipse.jdt.ui.text.java.correction.ChangeCorrectionProposal.apply(ChangeCorrectionProposal.java:109)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:1004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:951)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$3.widgetDefaultSelected(CompletionProposalPopup.java:697)
```

**Comment by iloveeclipse** [comment]
@jjohnstn , @robstryker : seem to be regression from #1120. Could you please check?

**Comment by robstryker** [comment]
Hrmm, not sure why this is not showing an error in the IDE.  The two classes are in the same package, visibility is set to 'protected' but it's not package-protected so it should show an error inside eclipse. 

Any ideas @jjohnstn ?  

Possible fixes are to change `return fCore.createChange();` to `return fCore.getChange()`, or, make a public but non-API method in the fcore that performs the same call effectively. 

I'm more curious why this isn't showing an error in the IDE or during build time, though.

**Comment by iloveeclipse** [comment]
The error says about different classloaders, this is where we should look for. Classes with "same" package (with same name) are considered to be from different packages at runtime if loaded from different classloaders.
So the question is probably why two classes were loaded from different classloaders. This would mean there is a way to get different bundles to load classes in question separately instead of one bundle to get classes loaded by another. Missing "export" package? Wrong version constraints?

**Comment by jukzi** [comment]
see https://nirmalsasidharan.wordpress.com/2010/09/02/split-packages-an-osgi-nightmare/
can you please just avoid split package?

**Comment by robstryker** [comment]
Upon reflection, I'm not sure blaming this on split packages is compelling. 

The eclipse tooling should recognize the two objects have completely different heirarchies, and `AddModuleRequiresCorrectionProposal` should under no circumstances be allowed to access the regular protected (ie, not package-protected) `createChange` method in `AddModuleRequiresCorrectionProposalCore`.

The tooling should 100% be marking this as an error. The method is not package-protected. It is regular protected with very different heirarchies.

**Comment by jukzi** [comment]
See https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html
that protected allows any access from the same package.
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=152568 that JDT can not detect split package, and OSGi can not solve it either

**Comment by jjohnstn** [comment]
> Hrmm, not sure why this is not showing an error in the IDE. The two classes are in the same package, visibility is set to 'protected' but it's not package-protected so it should show an error inside eclipse.
> 
> Any ideas @jjohnstn ?
> 
> Possible fixes are to change `return fCore.createChange();` to `return fCore.getChange()`, or, make a public but non-API method in the fcore that performs the same call effectively.
> 
I think your last idea is the best one: create a new public method.  I imagine this problem will need to be addressed in multiple spots.

**Comment by robstryker** [comment]
The public method already exists. I'll make a PR to call it.
