### ISSUE TITLE
Bug：Move interface method causes compilation errors.

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1299]
move  **_interfaceMethod()_** to **_MyClass_**  to classes causes compilation errors

interface MyInterface {
   // move **_interfaceMethod()_** to **_MyClass_**;
    void interfaceMethod();
}

class MyClass implements MyInterface {
    

	@Override
	public void interfaceMethod() {
		
	}
}

**Refactoring results：**
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/90594e29-c466-4205-9f4e-648ee7186be3)

**Comment by jjohnstn** [comment]
@DongChunHao This move is a textual move which means it is a cut/paste operation without checking hierarchy, implementers, etc...  I have created a patch that will restrict moving an interface method to anything other than another interface (something a user may reasonably want to do).  IMO, this is a reasonable check as moving such a method declaration anywhere else makes no sense.  As mentioned, there is no additional checking done (e.g. verifying that there aren't any implementers out there that will be broken when the method is moved).
