### ISSUE TITLE
Refreshing tree takes very long when projects are opened

### ISSUE THREAD

**Issue by dmigowski** [eclipse-jdt/eclipse.jdt.ui#130]
I have about 100 projects open in Eclipse, some trees of them are opened. When I refresh all projects it takes ages when I don't close the trees before hitting Ctrl-A and refresh. 

Could you please, when a whole project is selected anyway, don't call the refresh action on every item in the project by itself? I am still waiting for Eclipse to respond while writing this report. 

Thanks.

**Comment by jukzi** [comment]
A PR to improve it would be welcome. However I had never a problem with this. We use to press the refresh button in the git view, which works fine. 
Closing as not planned.
