### ISSUE TITLE
Default Execution Environment for Y build is 9

### ISSUE THREAD

**Issue by vik-chand** [eclipse-jdt/eclipse.jdt.ui#131]
Launch Y build using Java 19. Create a java project. The Execution Environment selected is 9. It should be 19.

**Comment by ktatavarthi** [comment]
@vik-chand The plugin build fails after this change. Can you please have a look.

**Comment by ktatavarthi** [comment]
> @vik-chand The plugin build fails after this change. Can you please have a look.

Closing this issue as the build failure is not related to this change.
