### ISSUE TITLE
[css themes] Floating Package Explorer view keeps blanking to white when clicking back and forth from the active source file and the code window

### ISSUE THREAD

**Issue by zhro** [eclipse-jdt/eclipse.jdt.ui#1321]
I don't know what the cause of this is, but the window keeps blanking to white when I click back and forth on the active source file between the IDE and Package Explorer. This only occurs when Package Explorer is a floating window.

I do not know how to provide a better example other than video or how to test this further. My workspace is large and I cannot reproduce this in a clean workspace.

This bug does NOT occur when the Project Explorer is docked. This is not ideal, as I use multiple monitors and prefer that my Project Explorer be floating and on a different screen.

https://youtu.be/nAi8kSye7Ug

I downloaded the latest Eclipse IDE for Java release (eclipse-java-2024-03-R-win32-x86_64.zip) with stock settings. All I did was import my workspace.

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

**Comment by iloveeclipse** [comment]
Looks like Windows or package specific, I haven't seen anything like this on Linux / plain SDK in any of SDK versions in the past.

This leads us to questions:
- is this a regression?
- if yes, in which version was it working?
- if not, can you disable Themes and try again?
- can you try latest SDK build from https://download.eclipse.org/eclipse/downloads/drops4/I20240410-1800/ is you see same issue?

**Comment by zhro** [comment]
> is this a regression?
> if yes, in which version was it working?
I have actually experienced this issue for years. I just updated my Eclipse from a 2022 version to 2024, but I've had the problem before that. It wasn't until now that I filed a report. Because it is difficult to reproduce (I don't have this problem in a clean workspace), it's difficult to differentiate at which version this problem manifested, as the workspace may not have been in the right state to cause the problem.

> can you try latest SDK build 
I tried the latest SDK and the problem still exists.

> can you disable Themes and try again?

I can confirm that disabling themes solves the problem. This appears to be the cause or is at least link to the source.

Please let me know if there is any further testing that I can do.

**Comment by iloveeclipse** [comment]
> I can confirm that disabling themes solves the problem

With that I'm unfortunately out, I don't use them and therefore have no interest / free time to fixing them, sorry.

**Comment by iloveeclipse** [comment]
Once more: since themes are provided by platform UI, please open the ticket here https://github.com/eclipse-platform/eclipse.platform.ui/issues and add the extra info from last comment that it is a long known issue and related to the css themes.
