### ISSUE TITLE
Fix new class wizard to flag missing package name as error when module info exists

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-jdt/eclipse.jdt.ui#1328]
When creating a new Java project, the new default is to create a module-info.java file for the project.

Creating a new class for this project, only a warning is issued if the package name is missing but once created, the source marks the missing package as an error.

Change the wizard to flag the missing package name as an error instead of a warning in this case.

**Comment by danthe1st** [comment]
Note: Even the warning is just because of the use of the unnamed package in general and it is unrelated to the module descriptor.
