### ISSUE TITLE
[23] ImplicitTypeDeclaration cannot be resolved to a type

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1336]
Taking the latest code from BETA_JAVA23 branches of both jdt core and UI, I am getting the error "ImplicitTypeDeclaration cannot be resolved to a type" in HierarchicalASTVisitor. 

I can see "org.eclipse.jdt.internal.compiler.ast.ImplicitTypeDeclaration" but no API version in org.eclipse.jdt.core.dom.*.

@jarthana, any inputs?

**Comment by jarthana** [comment]
I am not sure about the error. But looks like the DOM node is named `UnnamedClass`, which is not inline with the spec. I will fix this during the Java 23 work.

**Comment by jarthana** [comment]
OK, I see things have changed in the master branch wrt to the node name. I will do a merge.

**Comment by jarthana** [comment]
JDT Core in BETA_JAVA23 is now updated with master. The errors in the jdt.ui are gone now.

**Comment by noopur2507** [comment]
I have verified the same after pulling the latest code. Thanks.
