### ISSUE TITLE
Javadoc sections misaligned

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#1346]
Stumbled while looking at this code java doc: `FileSystems.newFileSystem((URI)null, null, null);`
Javadoc looks like on 4.30:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/b5eab38d-a059-4158-88ef-c49444801f50)

Javadoc looks like on 4.32:

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/b94d18f0-ccb6-440c-8e98-2117278b1318)

Note the missing indentation of "Parameters", "Returns" and "Throws" section headers - this makes reading complex javadoc harder as it should be.  

The section headers should be aligned on left side, not on same column as the following content.

![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/964108/814d6870-f386-442e-b9cd-2fb42e9e677c)

Also other headers ("Since", "See Also") are now misaligned, like on `java.util.regex.Pattern.splitAsStream(CharSequence)`:

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/964108/1e847601-5b14-4065-a235-a9563a0f2238)

I assume all section headers are misaligned now :-(

This is a regression from https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/941

**Comment by iloveeclipse** [comment]
@RedeemerSK : could you please check this one?

**Comment by RedeemerSK** [comment]
@iloveeclipse  seems like it was broken in 4.31 already. Commit that broke it: https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/cbc03c25f6059c774d8766bd7b02489c9df53acf

(I assume it's related to changes in JavadocContentAccess2.java )

Changing from using
`<dl> + <dd>`
HTML elements to
`<ul> + <li>`

**Comment by iloveeclipse** [comment]
@RedeemerSK : many thanks. I've created https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1351 for the fix.
