### ISSUE TITLE
API usage warning - ASTFlattener illegally references methods from RecordPattern

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1352]
org.eclipse.jdt.internal.corext.dom.ASTFlattener has API usage warnings - ASTFlattener illegally references method RecordPattern.getPatternType().

.api_filters file to be updated.

**Comment by noopur2507** [comment]
@jarthana - org.eclipse.jdt.core.dom.RecordPattern and its methods should be standard features now so @noreference should be removed from these API classes and methods. That should fix the API usage warnings in JDT UI.

**Comment by jarthana** [comment]
> @jarthana - org.eclipse.jdt.core.dom.RecordPattern and its methods should be standard features now so @noreference should be removed from these API classes and methods. That should fix the API usage warnings in JDT UI.

This was fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2379

**Comment by noopur2507** [comment]
> > @jarthana - org.eclipse.jdt.core.dom.RecordPattern and its methods should be standard features now so @noreference should be removed from these API classes and methods. That should fix the API usage warnings in JDT UI.
> 
> This was fixed via [eclipse-jdt/eclipse.jdt.core#2379](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2379)

What about TypePattern, GuardedPattern, or any other such APIs?
