### ISSUE TITLE
Move method dependency type conversion call causes syntax errors

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1354]
Eclipse version：2023-9

Repeat the steps：

1. select “moveMethod”
2. click “Refactor-move method”
3. tratget class "TargetClass "

Refactoring result:

![Uploading image.png…]()

Expected result： Check the method moved to the interface and issue a warning before refactoring if there are syntax errors

**Comment by iloveeclipse** [comment]
@DongChunHao : please provide at least minimal code example that triggers the error and please explain **which** error do you observe.

**Comment by jukzi** [comment]
Closing due to missing information
