### ISSUE TITLE
Inconsistent behavior caused by refactoring extraction methods

### ISSUE THREAD

**Issue by DongChunHao** [eclipse-jdt/eclipse.jdt.ui#1355]
Eclipse version：2023-9

Repeat the steps：

1. select “return;”
2. click “Refactor-extract method”

public class OriginalClass {
	public void foo() {
		Object runnable= null;
		Object[] disposeList= null;
		for (int i=0; i < disposeList.length; i++) {
			if (disposeList [i] == null) {
				disposeList [i] = runnable;
				// extract method
				return;
			}
		}
	}
}

refactoring result:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/77560508/cd7bd403-03a7-423b-a265-0e92a2a0a7b5)

Expected result：Missing "return" after refactoring, extracting a return statement should provide a warning prompt

**Comment by akurtakov** [comment]
It is recommended that you check whether the issue still appears with latest release (2024-03 now) as some of the things could have been fixed already (or not but if you check that you would ensure that committers look only at current issues).
