### ISSUE TITLE
add a "sticky scroll" feature

### ISSUE THREAD

**Issue by Madjosz** [eclipse-jdt/eclipse.jdt.ui#1364]
[Monaco Editor](https://github.com/microsoft/monaco-editor) added "sticky scroll" feature with v0.35.0 somewhere around February 2023 and thus it is supported in VS Code, Eclipse Theia and the web editor of e.g. GitHub.

This feature lets the current code section stick to the top of the editor when it scrolls out of the viewport so that current class and method (and I think I even saw loops/ifs/try blocks in some languages) are still visible to the user:
![Sticky Scroll in Eclipse Theia](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/28844868/c8f0e230-407b-4fc3-8847-414b0d091d56)

It would be nice to have this feaure also in the Eclipse Java editor.

Maybe this needs to be implemented in Eclipse Platform UI first. I saw that there already is an issue which somewhat requests this feature: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1719

**Comment by Christopher-Hermann** [comment]
Implemented with https://github.com/eclipse-platform/eclipse.platform.ui/issues/1719. Issue can be closed in my opinion.

**Comment by jjohnstn** [comment]
Thanks @Christopher-Hermann
