### ISSUE TITLE
Quickfix: Text block used for single line string if split into multiple arguments

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.ui#1406]
Assume the following code:

```
try {
	project.getBuildConfig("org.eclipse.pde.ManifestBuilder"); //$NON-NLS-1$
} catch (CoreException e) {
	ILog.get().error(
			"eclipse.pde/issues/1185: validateBuildPropertiesExists called for project without plugin nature: "
					+ project.getName(),
			e);
	return;
}
```

I select the string + the concatenation with the project name and now activate the quickfix
![grafik](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/1331477/69deeaec-60ad-4725-aec5-9ca60ce68651)

this now results in a textblock used:
```
try {
	project.getBuildConfig("org.eclipse.pde.ManifestBuilder"); //$NON-NLS-1$
} catch (CoreException e) {
	ILog.get().error(
			String.format("""
			eclipse.pde/issues/1185: validateBuildPropertiesExists called for project without plugin nature: \
			%s""", project.getName()),
			e);
	return;
}
```

Now I put everything in one line:

```
try {
	project.getBuildConfig("org.eclipse.pde.ManifestBuilder"); //$NON-NLS-1$
} catch (CoreException e) {
	ILog.get().error(
			"eclipse.pde/issues/1185: validateBuildPropertiesExists called for project without plugin nature: "	+ project.getName(),
			e);
	return;
}
```

this results in the desired/correct new code:

```
try {
	project.getBuildConfig("org.eclipse.pde.ManifestBuilder"); //$NON-NLS-1$
} catch (CoreException e) {
	ILog.get().error(
			String.format("eclipse.pde/issues/1185: validateBuildPropertiesExists called for project without plugin nature: %s", project.getName()),
			e);
	return;
}
```

**Comment by jjohnstn** [comment]
@jukzi, Yes, transferred.

**Comment by laeubi** [comment]
I don't agree (_as a user_) that this is intentional, this is simply not a multiline string (it is a one line string with one concatenation in the next line) and the result is hardly an improvement over the previous state as it requires an additional escape.

**Comment by laeubi** [comment]
This also results in a textblock and it is definitely **not** multiline;

```
public String getText() {

	if(label != null) {
		if(unit != null) {
			return label + " (" + unit + ")";
		}
		return label;
	}
	return null;
}
```

result is

```
public String getText() {

	if(label != null) {
		if(unit != null) {
			return String.format("""
			%s\
			 (\
			%s\
			)""", label, unit);
		}
		return label;
	}
	return null;
}
```

what is completely unreadable compared to desired result:

```
public String getText() {

	if(label != null) {
		if(unit != null) {
			return String.format("%s (%s)", label, unit);
		}
		return label;
	}
	return null;
}
```

**Comment by jjohnstn** [comment]
@laeubi Agreed.  It should have recognized that was on one line.  It was meant to distinguish concatenations over multiple lines so that is wrong.   I will look at it.

**Comment by jjohnstn** [comment]
@laeubi For the example given, if I select label or unit just after the return statement and select quickfix -> String format, I get one line as expected.  Do you have a recent I-build?  The fix was made on May 1st thereabouts commit: 87af14444e9eeb6847036a6655d7389d3350e9ff).

I am going to change the threshold to 3 lines or more to correspond with other cleanups like StringBuffer/StringBuilder to text block.

**Comment by jjohnstn** [comment]
Addition: will also check number of chars in StringLiterals.  If they are < a limit, then will also use one line.

**Comment by jjohnstn** [comment]
Fix has been made.  Text block is only used if 3 or more lines AND number of string literal characters are > 80.  Your examples will never use a text block and the examples of copyright statements from the initial issue to add text block support work as expected.
