### ISSUE TITLE
[JUnit5] New JUnit Test Suite Project wizard does not give option to create JUnit 5 Suite

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.ui#142]
We get the options to Create JUnit 3 and JUnit 4 Test Suite.
Should we not got an option to create JUnit 5 Test Suite?

**Comment by SarikaSinha** [comment]
Notification @noopur2507 @ktatavarthi

**Comment by ktatavarthi** [comment]
Initial bug for his was created in bugzilla : [Bug 511183](https://bugs.eclipse.org/bugs/show_bug.cgi?id=511183)

**Comment by carstenartur** [comment]
> We get the options to Create JUnit 3 and JUnit 4 Test Suite.
> 
> Should we not got an option to create JUnit 5 Test Suite?

You are talking about something else?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=570989

**Comment by ktatavarthi** [comment]
> > We get the options to Create JUnit 3 and JUnit 4 Test Suite.
> > Should we not got an option to create JUnit 5 Test Suite?
> 
> You are talking about something else? https://bugs.eclipse.org/bugs/show_bug.cgi?id=570989

This is not about creating Test Case, but about creating Test Suite

![image](https://user-images.githubusercontent.com/18457577/177551651-f9755104-c2da-49d7-a756-16d3fbd0b6e4.png)

**Comment by noopur2507** [comment]
JUnit 5 test suites support was added recently so this can be an enhancement to the wizard.

@jjohnstn Would you like to take this up and describe what can be done here as part of JUnit 5 test suites support?

**Comment by jjohnstn** [comment]
Sure.  I'm on vacation for a bit, but I can look at it for 2022-09 M2.

**Comment by jjohnstn** [comment]
@noopur2507 If you get a chance, please comment on the PR, otherwise, if you are too busy, I will merge for M2.

**Comment by noopur2507** [comment]
> @noopur2507 If you get a chance, please comment on the PR, otherwise, if you are too busy, I will merge for M2.

Sure, I will take a look.

**Comment by jjohnstn** [comment]
Verified for 4.25 M3 using I20220817-0600 build

**Comment by SarikaSinha** [comment]
I tried adding the Wizard to create the Test Suite but I land up with errors which specifies that org.junit is not recognized.
When I add a Test Case, I get a dialog to add JUnit5 in the build path but I don't get the same when I dd the test suite, any reason?

N&N entry is still missing.

**Comment by jjohnstn** [comment]
N&N was pushed, but I don't have permission to merge after the github migration.  I noticed that it was just merged.

I will have to look at the missing dialog; off-hand I am not sure if this was done for JUnit 4 testsuites.  I also noticed that New JUnit Testsuite isn't in the default New dialog while New JUnit Test is.  Should that be changed as well?

**Comment by SarikaSinha** [comment]
> N&N was pushed, but I don't have permission to merge after the github migration. I noticed that it was just merged.
> 
> I will have to look at the missing dialog; off-hand I am not sure if this was done for JUnit 4 testsuites. I also noticed that New JUnit Testsuite isn't in the default New dialog while New JUnit Test is. Should that be changed as well?

In which New dialog t isn't in the default? Can you attach the screenshot?

**Comment by jjohnstn** [comment]
Select a Package.  Do a right click -> New ...  You will see the last item is a JUnit Test Case but to get a testsuite you have to click on Other -> Java -> JUnit -> JUnit Testsuite  (lots of work)

**Comment by noopur2507** [comment]
Adding it to the default New menu is not required I think as it is not used very frequently. We can consider if we get more user requests.
