### ISSUE TITLE
In eclipse sdk 4,31, The wrong API method showed in UI

### ISSUE THREAD

**Issue by TigerGod** [eclipse-jdt/eclipse.jdt.ui#1431]
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/34829719/aa9d62fc-ce7c-491e-8518-84eb8d46bf12)

**Comment by humphreygao** [comment]
极少情况下会去给老版本打补丁。这个问题还是会被关闭的，因为新版本不可复现。
