### ISSUE TITLE
Eclipse 4.32 offers the execution environment JavaSE-23, although it is not yet supported

### ISSUE THREAD

**Issue by howlger** [eclipse-jdt/eclipse.jdt.ui#1448]
In the Eclipse SDK **4.32**, in the **_New Java Project_** dialog, in the **_Use an execution environment JRE_** drop-down menu, **`JavaSE-23` is offered** as an option, although it is not yet supported.

See also: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1349#issuecomment-2144428116

**Comment by akurtakov** [comment]
Running with JavaSE-23 EE is supported as this mandates the EE one wants to run with but it doesn't mandate that the bytecode generated from the project should be at level 23. What am I missing here?

**Comment by iloveeclipse** [comment]
> What am I missing here?

It is not about running but about compilation level. After this wizard is done, we allow & **set** Java 23 in compiler preferences for the project but generate and support only Java 22. So user assumes he can use Java 23 JLS but he can't actually.

**Comment by iloveeclipse** [comment]
> None of them seems to allow setting 23

But the **actual compiler options file** has 23!

**Comment by howlger** [comment]
The Java compiler setting _Use compliance from execution environment 'JavaSE-23' on the 'Java Build Path'_ does not do what it says, or at least what a user would expect. From the user's point of view the differences between `JavaSE-22` and `JavaSE-23` are not shown in the _Package/Project Explorer_, nor in the Java compiler setting (a user will not look at greyed-out/disabled fields).

**Comment by akurtakov** [comment]
@iloveeclipse What do you think of the approach taken in https://github.com/akurtakov/eclipse.jdt.ui/commit/7a2ac1b9b2010b2a76052c42dec676749a5d5716 ? If this looks fine as idea I'll finish it. 
Btw, is there any public API to achieve the same as CompilerOptions.getLatestVersion() ?

**Comment by iloveeclipse** [comment]
> What do you think of the approach taken in [akurtakov@7a2ac1b](https://github.com/akurtakov/eclipse.jdt.ui/commit/7a2ac1b9b2010b2a76052c42dec676749a5d5716) ? If this looks fine as idea I'll finish it. Btw, is there any public API to achieve the same as CompilerOptions.getLatestVersion() ?

See my ideas / comments on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2606

**Comment by akurtakov** [comment]
I don't see this directly benefiting the use case here (EE version that the compiler doesn't know about yet) but I will wait for the API changes to shape up before looking further into this one to reduce cross-fire.

**Comment by howlger** [comment]
Closed: in the [Eclipse SDK 4.33RC2](https://download.eclipse.org/eclipse/downloads/drops4/S-4.33RC2-202408281820/), in the _New Java Project_ dialog, in the _Use an execution environment JRE_ drop-down menu, `JavaSE-23` is no longer offered as an option.
