### ISSUE TITLE
Project Explorer is just a big white block

### ISSUE THREAD

**Issue by losmurfs** [eclipse-jdt/eclipse.jdt.ui#1451]
Project Explorer tab no longer functional in 2024-06.
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/10159345/0aff57a9-efc4-4664-9ab6-de5e08f3a5c6)

**Comment by iloveeclipse** [comment]
1) You seem to have custom theme bundles installed, they may cause that issue.
2) This is wrong bug tracker. If you see same issue on a **clean** Eclipse installation without 3rd party theme plugins, please report this at https://github.com/eclipse-platform/eclipse.platform.ui/issues

**Comment by losmurfs** [comment]
This appears to have been caused by "Darkest Dark Theme with DevStyle"
