### ISSUE TITLE
Outline tab displays each line of text 3px tall

### ISSUE THREAD

**Issue by losmurfs** [eclipse-jdt/eclipse.jdt.ui#1452]
Outline tab no longer useable in 2024-06.
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/10159345/c2463be4-897b-4c94-b5e4-ed53a54aac37)

**Comment by iloveeclipse** [comment]
Same comment as on https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1451. Closing.
