### ISSUE TITLE
Bug 513423 - Quick Fix provides incorrect placement of @Nullable

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.ui#1462]
From https://bugs.eclipse.org/513423

Given the class:
```
@NonNullByDefault
public class UncheckedException extends RuntimeException {
   public void printStackTrace(
      // Illegal redefinition of parameter s, inherited method from Throwable
      // does not constrain this parameter
      java.io.PrintStream s)
   {
      synchronized (s) {
         s.print(getClass().getName() + ": ");
         s.print(stackTrace);
      }
   }
}
```

According to:
http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm

Type annotation should be:
`java.io.@Nullable PrintWriter s`

But Quick Fix provides it as:
`@Nullable java.io.PrintWriter s`

I am also not provided a "Move type annotation" fix as suggested by 4.7-M5:
https://www.eclipse.org/eclipse/news/4.7/M5/

**Comment by jjohnstn** [comment]
FWIW: the Move type annotation quick fix is now offered after the @Nullable annotation is added and the line marked in error.
