### ISSUE TITLE
Sidebar and error markers not shown in Java Editor

### ISSUE THREAD

**Issue by ptziegler** [eclipse-jdt/eclipse.jdt.ui#1476]
The sidebar on the left side of the Java editor, which usually shows problem markers and line numbers, is broken in the currently nightly build. 

To reproduce:

 - Download and install the nightly build: https://download.eclipse.org/eclipse/downloads/drops4/I20240624-1800/
 - Create a new Java project
 - Create a new Java file 

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/70652978/23809e1c-fb17-4008-b566-e15f37edce33)

**Comment by iloveeclipse** [comment]
Any errors in the log?
I run nightly build without issues (on Linux).

**Comment by ptziegler** [comment]
> Any errors in the log? I run nightly build without issues (on Linux).

I was a little suspicious because the log is empty. But even with "-consoleLog", no error is shown.

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/70652978/14035552-e391-4f58-8f8c-887081baef8a)

**Comment by humphreygao** [comment]
Related to the screen resolution. And the color picker does not work as well.

**Comment by ptziegler** [comment]
> Related to the screen resolution. And the color picker does not work as well.

That's something I can verify... I just switched from 1920x1200 to 1600x900 and the sidebar shows up again.

**Comment by iloveeclipse** [comment]
@ptziegler : please create this bug at SWT project. JDT UI is not the right component.

**Comment by ptziegler** [comment]
Will do. Thank you both for the quick response!

**Comment by ptziegler** [comment]
In case anyone else is running into this issue: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1301
