### ISSUE TITLE
snippet javadoc is not formatted as snippet

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#1491]
example from java.nio.file.DirectoryStream
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/a04f5cae-0cc4-4d35-aece-48ce4914695b)

**Comment by jjohnstn** [comment]
@jukzi This is working for me after my fix for adding parameterized type support to snippet hover.  Could you confirm it works for you too with latest JDT UI?

**Comment by jjohnstn** [comment]
Closing as done.

**Comment by jukzi** [comment]
@jjohnstn  i am sorry to say it got even worse for me - the javadoc is empty now (I20240811-1800):
![image](https://github.com/user-attachments/assets/c9c2a1a6-cbe3-4a68-8a9e-6f34a2429d56)

**Comment by jjohnstn** [comment]
Hi @jukzi Something is different with your set-up.  Using I20240813 SDK with justj-22, it is working fine and I get the following when paging down to the last snippet:

![javadoc](https://github.com/user-attachments/assets/d1549633-8329-4409-a280-60e9fe8347c2)

**Comment by jukzi** [comment]
I tried it on another computer as well and can't see the javadoc.
lets make it a minimal reproducer, that does not show javadoc for me ( I20240814-1800, win10, compiled against org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_21.0.1.v20231028-0937\jre), to be sure we talk about the same javadoc:
example from https://openjdk.org/jeps/413
```
/**
 * The following code shows how to use {@code Optional.isPresent}:
 * {@snippet :
 * if (v.isPresent()) {
 *     System.out.println("v: " + v.get());
 * }
 * }
 */
class JEP413ExampleEmpty {

}

/**
 * Test
 * {@snippet lang = java :
 * {}
 * }
 */
class Empty {

}

/**
 * Test
 * {@snippet lang = java :
 *      Path dir = ...
 * }
 */
class Wrong {

}
```

![image](https://github.com/user-attachments/assets/c0bda946-e2d4-4ff2-92a1-b78868e738fd)
![image](https://github.com/user-attachments/assets/4b3a538c-aea0-41c7-abdd-63a23754abc6)

for the Jep413Example there is a warning:
![image](https://github.com/user-attachments/assets/0638baa6-2b85-4de9-82b6-42cd5e0d6daf)

**Comment by jjohnstn** [comment]
@jukzi What do you mean compiled against the JRE?

I run the downloaded/unzipped  Linux gtk x86-64 I20240814-1800 SDK from the command line (in this case I have OpenJDK installed: /usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc40.x86_64/lib/jrt-fs.jar

It works fine as does my previous setup using I20240813.  Perhaps this is Win-specific.  Unfortunately, I don't have access to Windows or Mac.

![Screenshot from 2024-08-19 14-49-59](https://github.com/user-attachments/assets/5a45eb69-fb9e-4947-8fe3-a47062a00593)

**Comment by jjohnstn** [comment]
FWIW: I made no changes to Preferences/etc.. and simply created a Java project and added a package to which I added your test file.

**Comment by jukzi** [comment]
> What do you mean compiled against the JRE?

The java that that was selected in the preferences.

> Perhaps this is Win-specific.

Is there any related junit test that i could test on my windows? Or any hint where i could start to debug?

**Comment by jukzi** [comment]
Turns out the javaproject that references the JDK has to be compiled with Compiler compliance setting 18+.
It is not enough that it is an 18+ jdk that contains the source
![image](https://github.com/user-attachments/assets/f8e77b32-e397-4fc9-b62c-3df428ba40a7)
workaround:
![image](https://github.com/user-attachments/assets/4017ddb4-e7ae-4664-b545-9bb070a2fcd5)
Would be better if the compiler version used to render the javadoc would match the version of the .class file that contains the javadoc.

**Comment by jjohnstn** [comment]
Glad you found the reason for the problem.
