### ISSUE TITLE
Support Convert to Text Block quickfix in annotations

### ISSUE THREAD

**Issue by vrozkovec** [eclipse-jdt/eclipse.jdt.ui#1500]
Currently, it is not possible to convert easily text in annotations to text block.
![image](https://github.com/eclipse-jdt/eclipse.jdt.core/assets/135681/e46470ee-07cc-48d0-8d96-46d0dfd13061)

This would come handy when using libraries such as JDBI which let you define your SQL in annotated methods.

**Comment by jjohnstn** [comment]
@vrozkovec What version of Eclipse are you using?  This works fine for me using 2024-03.  For example:

```
package tests;

import static java.lang.annotation.ElementType.TYPE;

import java.lang.annotation.Target;

@Target(TYPE)
public @interface SomeAnnotation {
	
	String value();

}

```

```
package tests;

@SomeAnnotation("abc\n"
+ "def"
+ "ghi" +
"jkl")
public class TryAnnotation {

}

```

When I use Ctrl+1 in the abc... string, it offers to convert to text block.

**Comment by vrozkovec** [comment]
@jjohnstn my bad, indeed, in newer version it works, sorry for the noise.
