### ISSUE TITLE
JUnit view shows wrong tests when re-using suites

### ISSUE THREAD

**Issue by paphko** [eclipse-jdt/eclipse.jdt.ui#151]
I have a test suite with some default data under test.

For variations of the test data, I subclassed the test suite and change the data under test in an @BeforeClass method.

Then the debug view shows both all test executions under the same (last) instance, even though one passes and one fails:
![image](https://user-images.githubusercontent.com/6435623/178235238-64916db0-82b3-4a6c-9e40-91e3d5e89b20.png)

Test files are attached: [suits.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/9082726/suits.zip)
Tested with Eclipse 22-06.

**Comment by noopur2507** [comment]
Can you please describe what's the expected result here?

Please run the same JUnit 4 test on the command line and attach the result here.

Also, try it out and mention if it was working in any older Eclipse release and is a regression in Eclipse 22-06.

**Comment by jukzi** [comment]
There is not information provided in this issue.
