### ISSUE TITLE
Convert to method reference creates usless cast

### ISSUE THREAD

**Issue by laeubi** [eclipse-jdt/eclipse.jdt.ui#1520]
```
Eclipse SDK

Version: 2024-09 (4.33)
Build id: I20240630-1800
```

## Assume the following code:

```
public class LamdaCast {

	public static void main(String[] args) {
		create("Hello").map(c -> c.get()).map(s -> s.concat("World"));
	}

	public static <X> Optional<Supplier<X>> create(X value) {
		if (value == null) {
			return Optional.empty();
		}
		return Optional.of(() -> value);
	}
}
```

now go to the first map and convert it to a method reference, this creates the following unnecessary casts:

```
public static void main(String[] args) {
    create("Hello")
       .map((Function<? super Supplier<String>, ? extends String>) Supplier<String>::get)
       .map(s -> s.concat("World"));
}
```
## The desired result would be (and as in Eclipse 2024-03 and earlier versions)

```
public static void main(String[] args) {
	create("Hello").map(Supplier::get).map(s -> s.concat("World"));
}
```

## Problem in action:

https://github.com/user-attachments/assets/ca6b4ab7-3702-452b-8728-4472e5d77580

**Comment by jjohnstn** [comment]
The extraneous cast was recently fixed, but I noticed that the method ref was adding a type parameter whereas it did not do so with the cleanup.  This has been fixed by the PR above.

**Comment by laeubi** [comment]
Thanks I'll try to test this with M2 in my codebase!
