### ISSUE TITLE
cleanup "use local variable type interference" refactors method references and creates error

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.ui#1524]
eclipse.buildId=4.33.0.20240711-1200
java.version=22.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_DE

Code like this:

```java
IDialogFieldListener adapter= this::addReadsDialogFieldChanged;
```

is refactored by the "use local variable type interference" cleanup on the "Java feature" tab to that:

```java
var adapter= this::addReadsDialogFieldChanged;
```

Result is that the code now is marked with the error "Method reference needs an explicit target-type"

I'm not completely sure where the issue is. The following code seems to be ok.

```java
public interface MyIntf  {
		void bla(Object... o);
	}

private  void bla(Object... o) {

	}

private void blubb() {
		new ArrayList<Object>().forEach((o) -> bla(o));
		MyIntf myin=this::bla;
	}
```

But when I want to use "var" I have to add a cast otherwise get the mentioned error:

```java
		var myin=(MyIntf)this::bla;
```

 Besides there is some magic using the refactoring to extract a variable. Depending on if I mark "this::bla" or include the cast I get an error. When I include the cast I get this and it contains an unnecessary cast that is not notified. I can just remove it.

```java
		MyIntf myIntf= (MyIntf)this::bla;
		var myin=myIntf;
```

When I extract a variable without the cast then I get this and eclipse marks an error:

```java
		MyIntf myIntf= this::bla;
		var myin=(MyIntf)myIntf;
```

So I'm not sure if there maybe is a bug in more than just the cleanup.

**Comment by jjohnstn** [comment]
Hi @carstenartur I think that a second issue should be opened against the compiler for not marking the cast as unnecessary.  I also think that the var cleanup should not change the MyIntf myintf= this::bla; statement (as opposed to adding a cast).  I have posted a fix.

**Comment by carstenartur** [comment]
Thanks @jjohnstn! I created an issue in jdt.core for the "unnecessary cast" question. Feel free to add information.
