### ISSUE TITLE
Rename with keyboard shortcut "⌥⌘R" is renaming more than one AST node

### ISSUE THREAD

**Issue by jmini** [eclipse-jdt/eclipse.jdt.ui#157]
With the newest Eclipse 2022-06 I have observed a wired behavior when I try to rename a method using the `⌥⌘R` shortcut:

![Eclipse Refactoring - rename issue](https://user-images.githubusercontent.com/1222165/178692372-3e9b59da-44c3-4ef9-94ab-0e4566a8e44c.gif)

I do not have a standalone reproduced yet. Also the project (Gradle project, imported in the Workspace using Buildship) presented in the screenshot is not open-source yet.

When I tried it this morning again, the error is still present but the wrongly-renamed node is somewhere else (maybe also because the code has changed)
![Eclipse Refactoring - rename issue (2)](https://user-images.githubusercontent.com/1222165/178694663-be9decef-6adf-4755-bf96-333449370c61.gif)

Also note that when you hit "Enter" to terminate the renaming operation, the wrongly renamed node is turned back to his original value. So maybe it is only a display problem during the rename operation?

**My Eclipse version:**

Eclipse IDE for Java Developers (includes Incubating components)

Version: 2022-06 (4.24.0)
Build id: 20220609-1112

```
applicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi
awt.toolkit=sun.lwawt.macosx.LWCToolkit
ds.delayed.keepInstances=true
ds.delayed.keepInstances.default=true
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.24.0.I20220607-0700
```

Tested on macOS.

**Comment by jjohnstn** [comment]
Can you please try the latest I-build from:  https://download.eclipse.org/eclipse/downloads/ ?

A fix was made to handle a regression in the rename code that among other things caused a BadLocationException to occur under the covers which prevented the rename from occurring after hitting Enter.  It also sometimes caused an assertion failure.  I have verified that today's I-build contains the fix and I believe it may be the same issue as this one.

The issue recently fixed is:  https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/158

The sample test from the issue above is simple.

**Comment by jmini** [comment]
I will give it a try

**Comment by jjohnstn** [comment]
@jmini Did you manage to try out the latest I-build?

**Comment by jukzi** [comment]
this issue contains insufficent information / is likely to be already fixed.
