### ISSUE TITLE
[23] Compiler compliance level 23 missing (BETA) label

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1588]
In compiler preferences, compliance level 23 is not having the label (BETA) in the latest Y-build.

This was added initially via https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1350/files#diff-75bddcdfd2484e74dd12777aa5f88c804a476cb214989f7363c5a654ef9eb0b1.

It seems to have been removed while dropping the support for older Java versions.

**Comment by stephan-herrmann** [comment]
> I'm on vacation till 27 August without access to computer. I guess the merge from master to BETA branch was not OK.

The merge was OK, just the new strategy without separately defined labels cannot handle this requirement.

We could manually replace "23" with "23 (BETA)" inside `ComplianceConfigurationBlock.createComplianceTabContent(Composite)` but that would add yet another task to the preparations for GA, when such disclaimers are to be removed.

Does JDT/UI have a central location where "beta-ness" is handled?

**Comment by noopur2507** [comment]
> Does JDT/UI have a central location where "beta-ness" is handled?

No. Another place where early-draft disclaimer is added is [ComplianceConfigurationBlock](eclipse-javadoc:%E2%98%82=org.eclipse.jdt.ui/ui%3Corg.eclipse.jdt.internal.ui.preferences%7BComplianceConfigurationBlock.java%E2%98%83ComplianceConfigurationBlock).validateComplianceStatus().

**Comment by stephan-herrmann** [comment]
> > Does JDT/UI have a central location where "beta-ness" is handled?
> 
> No. Another place where early-draft disclaimer is added is ComplianceConfigurationBlock.validateComplianceStatus().

Thanks,
In #1621 I tried to add the "(BETA)" suffix in a way that doesn't cause more maintenance efforts. I admit that the manual label manipulation is not the most elegant code.

@noopur2507 what do you think?

**Comment by stephan-herrmann** [comment]
Fixed for now by https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1621
