### ISSUE TITLE
[23] Highlight 'module' in module imports

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.ui#1589]
The syntax from https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2383 needs to get some help for highlighting the conditional keyword / restricted identifier **module** in code like this:

```java
package foo;
import module java.xml;
public class Foo {
    Document doc;
}
```

**Comment by stephan-herrmann** [comment]
Sneak preview of local implementation based on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2836:
![image](https://github.com/user-attachments/assets/33850267-ff7c-4d43-948e-ed4ad4fb20d7)

I changed the color for restricted identifiers for clarity (see how `record` is rendered).

This is the code we are referring to:
* `module-info.java`:
![image](https://github.com/user-attachments/assets/f5631c46-4da6-4a89-b233-b52eb882798a)
* `con/Fusion.java`:
![image](https://github.com/user-attachments/assets/05f9914f-d8d3-4d3d-a1b9-fd9939f6500c)

See that the import declaration can distinguish between occurrences of the word "module" (modifier vs. identifier), which the editor of `module-info.java` cannot yet.

**Comment by nlisker** [comment]
@stephan-herrmann I see that in this example
<img width="227" height="66" alt="Image" src="https://github.com/user-attachments/assets/4d89c50c-fcee-4124-bcce-7df33951184f" />
"module" is still highlighted when it shouldn't. Is this a bug in jdt.ui?

**Comment by nlisker** [comment]
> But honestly, is declaring module module { ... } really a sane why of creating software?? ;-P
Perhaps we should let those, who really want to create confusion, succeed in that effort.

Here's a real example: https://github.com/FasterXML/jackson-modules-base/blob/2.x/paranamer/src/moditect/module-info.java

It's a very small issue, so not worth a lot of work. I thought it's a matter of treating it as a contextual keyword like `var`, but it seems more complicated now with the explanation.
