### ISSUE TITLE
Eclipse default formatter profile and jdt

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.ui#1609]
What is the reason behind the eclipse default formatter rule for eclipse is violating jdt formatting standards? Could that be changed?

![image](https://github.com/user-attachments/assets/8ed5a8de-7d4d-4ced-8388-06a78f315352)

**Comment by stephan-herrmann** [comment]
I think this rule is very specific to JDT/UI and should probably not be imposed on everybody using this built-in profile.

Do you see other sub-projects following this rule?

**Comment by carstenartur** [comment]
Nice would be imho if there was a profile for jdt contributions - in case it is necessary even two or more but I wasn't aware that jdt is really using different standards depending on the specific project.
