### ISSUE TITLE
"record" is highlighted as a keyword when used as a variable name

### ISSUE THREAD

**Issue by jarthana** [eclipse-jdt/eclipse.jdt.ui#1624]
Here's a sample code:

```
        RforRecord rec = new RforRecord(x);
        if (record instanceof RforRecord(int y)) {
            System.out.println("Yay");
        }
```
Note that the variable "record" is miss-spelt and therefore not defined. In this case, the editor considers "record" as a keyword and highlights accordingly, as below:

![image](https://github.com/user-attachments/assets/2ff7227e-4634-4521-b0c9-0265ef522302)

**Comment by noopur2507** [comment]
Debugged and checked that it is not getting highlighted by incorrectly being identified as a record declaration. Verified by changing the color of restricted keywords in Preferences, which doesn't change the color of "record" at the error location but changes it at the record declaration site. 

The behavior is similar to having any other (mis-spelt) keyword at this error location e.g. "public". 

Hence, closing the issue. Please reopen if it is causing any major inconvenience.

<img width="594" alt="Screenshot 2024-09-12 at 12 10 07 PM" src="https://github.com/user-attachments/assets/067a64ea-60b8-4090-95d7-082768e7f021">
