### ISSUE TITLE
Save Actions Conflict and Cause Logic Change

### ISSUE THREAD

**Issue by IanKrL** [eclipse-jdt/eclipse.jdt.ui#1638]
Window->Preferences->Java->Editor->Save Actions
Select "Perform the selected actions on save" and "Additional actions"
Select Configure->
->->Code Style->Control statements->Reduce indentation when possible
->->Unnecessary Code->Unnecessary Code->Remove useless return

These two options being enabled at the same time interact to cause logic changes. This:
```
public class Cleanup {
    public void foo(boolean arg) {
        if (arg) {
            return;
        } else {
            System.out.println("Hello World");
        }
    }
}
```
gets cleaned up to this:
```
public class Cleanup {
    public void foo(boolean arg) {
        if (arg) {
        }
        System.out.println("Hello World");
    }
}
```
Now the output is seen regardless of the parameter value. This is not the case when either is selected independently.

**Comment by jjohnstn** [comment]
Thanks @IanKrL for reporting.  The cleanups don't see one another as they are not recursive.  Some special guarding is needed to handle this.  I'll look at it.
