### ISSUE TITLE
[23] Remove reference to Y-builds in pom.xml

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#1650]
Remove reference to Y-builds in pom.xml while merging the beta branch to master.

**Comment by stephan-herrmann** [comment]
@noopur2507 shouldn't this wait until we have the final builds for Java 23?

Y-build is currently running, and I'm not sure it can succeed without a reference to a Y-build, where it needs to find the Java 23 variant of JDT/Core?

@mpalat @jarthana where, when and how will the final version be built?

Also, I see a branch `remove-beta-disclaimers`. Is that the input that should go into the final build? Will it?

**Comment by stephan-herrmann** [comment]
> @noopur2507 shouldn't this wait until we have the final builds for Java 23?
> 
> Y-build is currently running, and I'm not sure it can succeed without a reference to a Y-build, where it needs to find the Java 23 variant of JDT/Core?

I guess I got it a bit backwards? So the change in pom.xml wasn't used for *creating* a Y-build, but for letting a PR build of JDT/UI find the required bits from JDT/Core, right? If there is no more PR for BETA_JAVA23 then this reference is indeed no longer needed.

**Comment by noopur2507** [comment]
> > @noopur2507 shouldn't this wait until we have the final builds for Java 23?
> > Y-build is currently running, and I'm not sure it can succeed without a reference to a Y-build, where it needs to find the Java 23 variant of JDT/Core?
> 
> I guess I got it a bit backwards? So the change in pom.xml wasn't used for _creating_ a Y-build, but for letting a PR build of JDT/UI find the required bits from JDT/Core, right? If there is no more PR for BETA_JAVA23 then this reference is indeed no longer needed.

That's right. This change was only for running JDT UI Gerrit builds for BETA_JAVA23 branch against a Y-build. So, it's fine to remove the Y-build reference now.

**Comment by noopur2507** [comment]
> > Also, I see a branch `remove-beta-disclaimers`. Is that the input that should go into the final build? Will it?
> 
> Is this on someone's radar, so users won't see "23 (BETA)" and the full beta-disclaimer after installing the patch feature?
> 
> @noopur2507 @mpalat @jarthana

Yes, https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1648 is tracked in https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2213. To be merged into the BETA_JAVA23 branch after Java 23 GA. A patch build will be created after that which will be used for the Marketplace entry as well.

**Comment by jarthana** [comment]
> @mpalat @jarthana where, when and how will the final version be built?
> 
> Also, I see a branch `remove-beta-disclaimers`. Is that the input that should go into the final build? Will it?

Yes, Stephan. Once all the beta disclaimers have been removed on the BETA_JAVA23 branch (for jdt.core, ui and debug), we will have one last P build off BETA_JAVA23 and that should be the our release candidate.

**Comment by stephan-herrmann** [comment]
Thanks, @noopur2507 , @jarthana for explanations. I see you know better than me what needs to be done and in which order :)
