### ISSUE TITLE
quickfix "remove 'restriction' token is not able to handle several cases in one file in one run

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.ui#1668]
Trying to move the tests from a separate folder to the usually used jdt.tests project in
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1631
I have to remove a lot of suppressions for warnings (that they are needed might be another issue in jdt).

![image](https://github.com/user-attachments/assets/cc55dcac-fe37-4f90-97c8-0164e8418e2b)

You have to do that one after another because there is no option to remove all equal suppressions at once.
Is that intended?

**Comment by jjohnstn** [comment]
Intended isn't the correct word.  There are fixes that do that, this one isn't set up to do that.  That said, I will look into making it a multifix.
