### ISSUE TITLE
Hamcrest 3.0 is still breaking things in Eclipse 4.30

### ISSUE THREAD

**Issue by pci-mthompson** [eclipse-jdt/eclipse.jdt.ui#1672]
I am seeing the same errors in my Eclipse 2023-12 (v4.3.0) during clean installs and whenever someone has run the update on an existing install.

java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.core.IClasspathEntry.getEntryKind()" because "entry" is null
	at org.eclipse.jdt.internal.ui.packageview.ClassPathContainer.getChildren(ClassPathContainer.java:190)
...

java.lang.IllegalStateException: Unable to compute bundle location for 'org.hamcrest' with range [2.2.0,2.3.0)
	at org.eclipse.jdt.internal.junit.buildpath.BuildPathSupport$JUnitPluginDescription.getLibraryEntry(BuildPathSupport.java:236)
...

Opening a project's properties under Libraries for Junit 4 it shows the Junit 4.13 jar and hamcrest core, but can't find hamcrest itself.

Removing Hamcrest 3.0 plugin fixes some of those errors but then random views like Ant break, and File/Search stops working.  I see this issue was fixed for Eclipse v4.34?  But I can't see how to get the fix down into older versions.

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1610
https://github.com/eclipse/xtext/issues/3178
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1611
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1612

**Comment by pci-mthompson** [comment]
Traceback from Ant view:
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ant.ui [131]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit; bundle-version="[3.5.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.jdt.junit; bundle-version="3.16.200.v20231106-1537"; singleton:="true"
       org.eclipse.jdt.junit [461]
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.core; bundle-version="[3.11.200,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.core; bundle-version="3.13.0.v20231102-1522"; singleton:="true"
              org.eclipse.jdt.junit.core [462]
                Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.300.v20231106-1537"; singleton:="true"
                     org.eclipse.jdt.junit.runtime [463]
                       Unresolved requirement: Require-Bundle: org.junit; bundle-version="3.8.2"
                         -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230809-1000"
                            org.junit [1001]
                              Unresolved requirement: Require-Bundle: org.hamcrest.core; bundle-version="1.3.0"; visibility:="reexport"
                                -> Bundle-SymbolicName: org.hamcrest.core; bundle-version="2.2.0.v20230809-1000"
                                   org.hamcrest.core [992]
                                     Unresolved requirement: Require-Bundle: org.hamcrest; bundle-version="2.2.0"; visibility:="reexport"
         Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.7.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.jdt.junit.runtime; bundle-version="3.7.300.v20231106-1537"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)

**Comment by jukzi** [comment]
> But I can't see how to get the fix down into older versions.

There is no support for old eclipse IDE versions. You need to update to the newest release.
