### ISSUE TITLE
Clean up "Convert if/else if/else chain with 3 blocks min to switch" in 2024-09 changes code semantic by not considering null

### ISSUE THREAD

**Issue by FlorianKroiss** [eclipse-jdt/eclipse.jdt.ui#1714]
Consider the following example:
```java
public class Dummy {

    enum TestEnum {
        A, B, C
    }

    public int doSomething(final TestEnum val) {
        if (val == TestEnum.A) {
            return 1;
        }
        else if (val == TestEnum.B) {
            return 2;
        }
        else if (val == TestEnum.C) {
            return 3;
        }
        return 4;
    }

}
```
Calling this method with `null` returns 4.

Applying the code clean up "Convert if/else if/else chain with 3 blocks min to switch" produces the following code
```java
public class Dummy {

    enum TestEnum {
        A, B, C
    }

    public int doSomething(final TestEnum val) {
        switch ( val ) {
            case TestEnum.A:
                return 1;
            case TestEnum.B:
                return 2;
            case TestEnum.C:
                return 3;
            default:
                break;
        }
        return 4;
    }

}
```

The cleaned up code now throws a `NullPointerException`, when being called with `null`, instead of falling through to `return 4;`.
I guess in case `null` was not explicitly treated in the original code, then the correct clean up would be to use `case null, default:` instead of `default:`.

**Comment by jjohnstn** [comment]
BTW: thanks @FlorianKroiss for reporting this.  The cleanup has been changed to add the case null when the Java version allows it and to create an if statement otherwise.
