### ISSUE TITLE
“Change Method Signature” refactoring：Reflection causes code behavior changes

### ISSUE THREAD

**Issue by assdfsdafasfa** [eclipse-jdt/eclipse.jdt.ui#1749]
Select methodToBeRenamed(), and click Change Method Signature refactoring, change the method name to newMethod(), the string remains unchanged, causing code behavior to change.
Code before refactoring:
 ```java
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
class SomeService{
    public void methodToBeRenamed(){}
}
class Test{
    void test() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        Method method = SomeService.class.getMethod("methodToBeRenamed",null);
        method.invoke(new SomeService());
    }
}
```
Code after refactoring: 
 ```java
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
class SomeService{
    public void newMethod(){}
}
class Test{
    void test() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        Method method = SomeService.class.getMethod("methodToBeRenamed",null);
        method.invoke(new SomeService());
    }
}
```

**Comment by jjohnstn** [comment]
Closing as WONTFIX.  Supporting reflection would require processing every class to determine if reflection is being used for the particular class and method in question.  It is possible the strings might be supplied dynamically through a variable (I know of one example we have in Linux Tools Docker tooling where it is an array of strings that is used).  Typically, such reflection is used when using a binary third-party library or the Java library and one is trying to get around modifier restrictions.  In typical reflection uses, a user doesn't have the ability to rename the method.  For classes in the user control, it is far more likely and better practive that they would be accessed directly.
