### ISSUE TITLE
“Extract method” refactoring： Internal class method call changes

### ISSUE THREAD

**Issue by assdfsdafasfa** [eclipse-jdt/eclipse.jdt.ui#1758]
Select the statement in method f(), select Extract Method refactoring, the new method name is 'method', resulting in a change in the calling relationship. Before refactoring, testMethod() calls method() in class SourceClass. After refactoring, testMethod() calls method() in class ParentClass.

Code before refactoring:
 ```java
class ParentClass {
    void f() {
        // extract method, new method name 'method'
        int i;
    }
}

class SourceClass {
    void method() {
    }

    class InnerClass extends ParentClass {
        void testMethod() {
            method();
        }
    }
}
```

Code after refactoring: 
 ```java
class ParentClass {
    void f() {
        // extract method, new method name 'method'
        m();
    }

    private static void m() {
        int i;
    }
}

class SourceClass {
    void method() {
    }

    class InnerClass extends ParentClass {
        void testMethod() {
            method();
        }
    }
}
```

**Comment by jjohnstn** [comment]
@assdfsdafasfa The example given is not what you have reported.  In addition, the default modifier for the new method is private and doesn't cause a problem.  Both the method name and the modifier need to be set to cause the issue.
