### ISSUE TITLE
268 failures in content assist related tests on Mac since I20220726-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#178]
https://download.eclipse.org/eclipse/downloads/drops4/I20220726-1800/testResults.php
https://download.eclipse.org/eclipse/downloads/drops4/I20220726-1800/testresults/html/org.eclipse.jdt.ui.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

Affected: AdvancedQuickAssistTest, AssistQuickFixTest, JavadocQuickFixTest

I can't verify if that is sporadic issue, I don't have Mac.

In most cases there are no proposals found. Not sure what caused that, couldn't see related changes.

These two were merged in I20220726-1800 but seem not be related:
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/177
- https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/86

**Comment by noopur2507** [comment]
Looks like these were sporadic. Didn't fail in the next builds and also running fine locally on mac now.
