### ISSUE TITLE
Warnings show up in the editor but not in problems view

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-jdt/eclipse.jdt.ui#1810]
I am on 4.34 RC2, but this problem has been there for some time and I haven't gotten around to reporting it. 

After a clean and automatic rebuild of jdt-core projects, the problems/marker view does not show warnings. These show up in the editor. 

This is driving me crazy! I am clueless if something my set up could be bringing this up - if so please clue me in.

Thanks!

**Comment by srikanth-sankaran** [comment]
@noopur2507 - Any pointers ? TIA

**Comment by jukzi** [comment]
@srikanth-sankaran please add an example, which warning you are missing for which file and line number.
In my platform workspace i see several warnings for the jdt.core workingset:
![image](https://github.com/user-attachments/assets/e5dbb44f-c5e9-4516-8ea3-8e2c412bb760)

**Comment by srikanth-sankaran** [comment]
Mea culpa. I don't know how my problem view filter got configured to NOT show warnings. Thing is I am such a basic IDE user I don't even know I can apply some filters on problem view. So this cannot be due to my action. But I am able to eliminate the filters and see the warnings, so I am good. Sorry for the noise.
