### ISSUE TITLE
"Add unimplemented methods" does not work for some interfaces with defaults

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-jdt/eclipse.jdt.ui#182]
Consider the following snippet:
```
interface I1 {
    default int gogo() {
        return 24;
    }
}

interface I2 extends I1 {
    int gogo();
}

public class Gugu implements I1, I2 {
}
```

You correctly get an error on "Gugu" saying that the class must implement the method `gogo()`, howerver, invoking the "add unimplemented methods" quick fix shows an error dialog and does not add the method.

**Comment by tsmaeder** [comment]
The relevant section of the spec would be https://docs.oracle.com/javase/specs/jls/se18/html/jls-9.html#jls-9.4.1

**Comment by iloveeclipse** [comment]
I assume this can be closed now. If not, please feel free to reopen and re-set the milestone.
