### ISSUE TITLE
[Bug][Pull Up Refactoring] Pull up refactoring produce uncompilable code for lambda parameter

### ISSUE THREAD

**Issue by RETester66** [eclipse-jdt/eclipse.jdt.ui#1823]
## Steps to reproduce
The input program is following:
```
public class A {
    public class BaseInner {
        void innerMethodLambda(Outer outer) {
            Runnable r = () -> {
                System.out.println(outer.x);
                outer.foo();
            };
            r.run();
        }
    }

    public class Outer {
        public int x = 0;
        public void foo(){};

        public class Inner extends BaseInner {
            void innerMethod() { // Pull this method up to class BaseInner
                innerMethodLambda(Outer.this);
            }
        }
    }
}
```
Left click innerMethod(), then right click -> Refactor -> Pull Up, use the default configuration shown below, click finish:

![image](https://github.com/user-attachments/assets/7468bae8-0bb2-4170-ad33-faf1ae7ea7db)

The refactoring is performed without any warning or exception. The refactored program is following, which contains syntax error:

![image](https://github.com/user-attachments/assets/31dccd00-cb02-419f-aaf4-16fdb681f03f)

### OS Version
Windows 10, 64-bit Operating System, x64-based processor
### Eclipse Version
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2024-09 (4.33.0)
Build id: 20240905-0614
### JDK Version
java version "22.0.1" 2024-04-16
Java(TM) SE Runtime Environment (build 22.0.1+8-16)
Java HotSpot(TM) 64-Bit Server VM (build 22.0.1+8-16, mixed mode, sharing)

**Comment by jukzi** [comment]
The last issue in that area was https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1533
