### ISSUE TITLE
Convert String/StringBuffer/StringBuilder concatenation to Text Block not working on JDT.core UnnecessaryArrayCreationQuickFixTest

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#1841]
/org.eclipse.jdt.ui.tests/ui/org/eclipse/jdt/ui/tests/quickfix/UnnecessaryArrayCreationQuickFixTest.java contains statements like:

````
StringBuilder buf= new StringBuilder();
		buf.append("package test1;\n");
		buf.append("import java.util.Arrays;\n");
		buf.append("import java.util.List;\n");
		buf.append("public class A {\n");
		buf.append("    private class A1 {\n");
		buf.append("        public String[] foo(int x, String[] ... b) {\n");
		buf.append("            return b[0];\n");
		buf.append("        }\n");
		buf.append("    }\n");
		buf.append("    private class A2 extends A1 {\n");
		buf.append("        public String[] foo(int x) {\n");
		buf.append("            return super.foo(x, new String[][] { new String[] {\"a\"}});\n");
		buf.append("        }\n");
		buf.append("    }\n");
		buf.append("}\n");
````

I would expect that the Source clean up convert to Text Block would convert this. It currently does not.

![image](https://github.com/user-attachments/assets/8a3279fa-d5e0-4d3c-a61e-41d41c0c535a)

cc @jjohnstn

**Comment by jjohnstn** [comment]
@vogella The reason the conversion does not occur is that the buf is later passed to a method: fetchConvertingProposal2.  Removing the StringBuilder makes that impossible.  If the methods that take a StringBuilder/StringBuffer were converted to take a String, then the buf.toString() could passed and this would trigger the clean-up to do what you expect.

**Comment by carstenartur** [comment]
Hi @jjohnstn 
Imho it might be possible to aggregate consecutive lines into a text block without substitution of the Stringbuffer object in this case. Wdyt?

**Comment by jjohnstn** [comment]
So, initializing the StringBuilder/StringBuffer with a text block.  Yes, it would be possible.  I'll take a look at it.

**Comment by vogella** [comment]
Thanks @jjohnstn I currently cannot test due to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1843
