### ISSUE TITLE
Quick Search does not look in "target" folder despite no filters set.

### ISSUE THREAD

**Issue by ykartsev** [eclipse-jdt/eclipse.jdt.ui#1857]
Dear Community!

I've spent a lot of time searching for this in various forums and websites in general, but couldn't find the answer. It might be a bug, that's why I'm posting it here.

Basically, my Quick Search in latest Eclipse IDE (2024-12) does not search in target folder, even though a folder inside it (target/generated-sources/cxf) currently marked as source folder in Package Explorer.

Obviously, I checked Quick Search preferences, I removed all ignored names from there, but no luck:
<img width="838" alt="Screenshot 2024-12-16 at 13 18 33" src="https://github.com/user-attachments/assets/e2066d1c-1ccb-4d4e-86cc-feed6e8e5d19" />

Just for sake of experiment, I have also tried adding Resource Filter to exclude "target" folder - that removed target source folder from my project. Removing that filter gets the source folder back, but Quick Search still does not search it.

I searched the docs, but neither of these two helped:
- https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2FgettingStarted%2Fqs-36.htm
- https://spring.io/blog/2013/07/11/eclipse-quick-search

The latter despite being old, talks about preferences, but as you saw in the screenshot above there is no option to include "target" folder.

**Comment by ykartsev** [comment]
As usual, as soon as I ask someone, the answer comes :) I realized that Open Resource does not see files in that folder either. Then noticed that I did not have my parent Mven project open, only its child module. When I opened the parent module, Open Resource and Quick Search started seeing that folder! While it's not intuitive, but this is how it is.

I am still leaving it open to the discretion of the admins, because it's kind of not right still.

**Comment by ykartsev** [comment]
Hm... there is definitely an issue in Quick Search... When I open one of those source-generated files, select its class name and press Cmd+shift+L to call Quick Search dialog, it opens up, but without search results from "target" folder. Then I delete last character of the class name in the search bar and it suddenly includes search results from the target folder. Adding that character back still includes target folder.

I will try to assemble a sample project to attach it here as an example. But I think it's good to know.

**Comment by jukzi** [comment]
@ykartsev quick search is not a JDT feature but platform.ui. Closing as NOT JDT. Please create a new issues at https://github.com/eclipse-platform/eclipse.platform.ui as we can not move issues between organizations, sorry.
