### ISSUE TITLE
iterator declaration missing after "enhanced foreach cleanup" in case of more than one use of declared iterator

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.ui#190]
See a code sample for this issue:

![image](https://user-images.githubusercontent.com/3164220/182121140-cc6b77c5-eeea-4017-8656-eda1c12a1528.png)

The declared variable is used twice but after refactoring the first one the declared variable is no longer available.

Sample code at 
https://github.com/carstenartur/eclipse.pde/commit/b5abc23cdb348fa203d3a72c4d5c2b92c389c570

**Comment by jjohnstn** [comment]
Verified for 4.25 M3 using I20220817-0600 build
