### ISSUE TITLE
Tooltips in Java Editor Eclipse 4.25 M1 are blank when using MS Edge on Windows 11

### ISSUE THREAD

**Issue by minduch** [eclipse-jdt/eclipse.jdt.ui#198]
In Windows 11 and MS Edge in Eclipse 4.25 M1 using `-Dorg.eclipse.swt.browser.DefaultType=edge` in `eclipse.ini` causes all tooltips in Eclipse workbench Java code to be blank, regardless of Dark/Light/Classic theme. Removing the setting `-Dorg.eclipse.swt.browser.DefaultType=edge` makes it work.

Tooltips shown other editors e.g. XML works fine in both modes (with or without declaration of `-Dorg.eclipse.swt.browser.DefaultType=edge`).

**Environment**
Windows 11 (Developer Preview Channel) = Microsoft Windows [Version 10.0.22622.450]
MS Edge = Version 103.0.1264.77 (Official build) (64-bit)
Java = JustJ from Eclipse 4.25 M1

**Comment by minduch** [comment]
Same problem as issue #248.

**Comment by akurtakov** [comment]
This has been worked on in SWT. Please use latest version.
