### ISSUE TITLE
[JUnit] Support collections when showing a failed assertEquals()

### ISSUE THREAD

**Issue by jubax** [eclipse-jdt/eclipse.jdt.ui#211]
When you have code like
```
List<String> expected = List.of("a","b");
List<String> actual = List.of("a","b","c");
assertEquals(expected, actual);
```
and you run the code then Eclipse shows an error. But when you double-click on the failure trace then nothing happens. It would be nice if we would have a display of the differences like it is already done with e.g. strings.

**Comment by noopur2507** [comment]
You need to double-click on the first line of the failure trace. We show the result comparison in this case also.

<img width="1243" alt="Screenshot 2022-08-16 at 12 58 01 PM" src="https://user-images.githubusercontent.com/8749449/184822608-69ef485a-4804-44c9-b11b-f212d20c4b75.png">

**Comment by jubax** [comment]
Thank you. I was aware that I need to double-click on the first line. But for some reason this sometimes does not work for me. I just thought it was a general problem, but maybe it was something specific.

I will re-open or create a new bug if I have a reproducable case. Thanks again!
