### ISSUE TITLE
Follow up from #12 (Bug 577317) to make reconciler work for Syntax coloring

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-jdt/eclipse.jdt.ui#25]
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/13#issuecomment-1097973354

If I use quick fix to add class in same package, the "permits" is not coloured properly. After going back to the file and adding a "enter" applies the colouring.

Debug learnings: Adding breakpoint in Reconciler leads to proper syntax colouring. Looks like the order of  invocation of JavaCompositeReconcilingStrategy is impacting this.

**Comment by ktatavarthi** [comment]
Verified in the build I20220516-1800
