### ISSUE TITLE
Stale Eclipse-SourceReferences for org.eclipse.jdt.astview and org.eclipse.jdt.jeview

### ISSUE THREAD

**Issue by merks** [eclipse-jdt/eclipse.jdt.ui#256]
While investigating https://github.com/eclipse-platform/eclipse.platform.releng/issues/113 I noticed these two references to git.eclipse.org:

![image](https://user-images.githubusercontent.com/208716/189840769-46fc4347-ab1c-4a2b-a4bc-0a0b2a9bec20.png)

I'm not sure why these are hard coded.  Can they be removed?  Should they be changed to https://github.com/eclipse-jdt/eclipse.jdt.ui.git instead?

**Comment by iloveeclipse** [comment]
> I'm not sure why these are hard coded. 

Me either

> Can they be removed? Should they be changed to https://github.com/eclipse-jdt/eclipse.jdt.ui.git instead?

What do we do in other "good" manifests? Just do the same I would say.

**Comment by merks** [comment]
These are the only two bundles in my entire SDK workspace with an Eclipse-SourceReferences property.  They were added like this without a Bugzilla and no explanation.
```
Eclipse-SourceReferences: scm:cvs:pserver:dev.eclipse.org:/cvsroot/eclipse:jdt-ui-home/plugins/org.eclipse.jdt.jeview;tag=R1_0_8
```
I think deleting them makes sense.
