### ISSUE TITLE
Eclipse IDE for Java Developers fails to update

### ISSUE THREAD

**Issue by superbonaci** [eclipse-jdt/eclipse.jdt.ui#269]
Error message when trying to update Eclipse:
````
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: M2E - SLF4J over Logback Logging 2.0.0.20220717-0848 (org.eclipse.m2e.logback.feature.feature.group 2.0.0.20220717-0848)
  Software currently installed: JustJ OpenJDK Hotspot JRE Complete 15.0.1.v20201027-0507 (org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 15.0.1.v20201027-0507)
  Cannot satisfy dependency:
    From: JustJ OpenJDK Hotspot JRE Complete 15.0.1.v20201027-0507 (org.eclipse.justj.openjdk.hotspot.jre.full 15.0.1.v20201027-0507)
    To: org.eclipse.equinox.p2.iu; a.jre.javase 0.0.0
  Cannot satisfy dependency:
    From: JustJ OpenJDK Hotspot JRE Complete 15.0.1.v20201027-0507 (org.eclipse.justj.openjdk.hotspot.jre.full.feature.group 15.0.1.v20201027-0507)
    To: org.eclipse.equinox.p2.iu; org.eclipse.justj.openjdk.hotspot.jre.full [15.0.1.v20201027-0507,15.0.1.v20201027-0507]
  Cannot satisfy dependency:
    From: M2E Logback Configuration 2.0.0.20220705-1221 (org.eclipse.m2e.logback.configuration 2.0.0.20220705-1221)
    To: osgi.ee; (&(osgi.ee=JavaSE)(version=17))
  Cannot satisfy dependency:
    From: M2E - SLF4J over Logback Logging 2.0.0.20220717-0848 (org.eclipse.m2e.logback.feature.feature.group 2.0.0.20220717-0848)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.logback.configuration [2.0.0.20220705-1221,2.0.0.20220705-1221]
````

![](https://i.imgur.com/4H5BWXV.png)

Debug info:
```
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-06 (4.24.0)
Build id: 20220609-1112
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 15.0.1+9-18
Java version: 15.0.1
```

**Comment by jjohnstn** [comment]
Hello.  This is not a JDT UI issue but I understand your frustration.

Eclipse 2022-09 (4.25) components require Java 17.  You have JustJ 15.0.1 as part of your 2022-06 IDE and JustJ 17 is not part of the default update sites.  If you add the following: https://download.eclipse.org/justj/jres/17/updates/release to your available update sites, the update should work.

**Comment by superbonaci** [comment]
Why JDT UI does not prompt to update JustJ before updating Eclipse? If that's the issue seems logic that they update justj alongside with eclipse itself.

**Comment by jjohnstn** [comment]
I have posed such a question internally.  Apparently, it is not part of current simrel but I agree it should be.  It is a build/platform issue and not JDT UI.

**Comment by superbonaci** [comment]
Which bug tracker is the adequate to report this bug?

**Comment by superbonaci** [comment]
To update it's as easy as downloading the new version from the website and installing, but still it's a weird bug.

**Comment by jjohnstn** [comment]
It has been proposed on the mailing lists that JustJ could register and enable its update site automatically for IDEs that have installed it.  I agree and this would have solved your problem and will help in the future.  You can post a bug to JustJ: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Justj

**Comment by superbonaci** [comment]
If it's been proposed already we should wait to see the resolution of who's in charge, isn't it?

**Comment by jonahgraham** [comment]
Please see the [bug raised in bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580808) where we will work towards a resolution. I hope that @superbonaci you are able to add yourself to the CC list there if you can participate.

@jjohnstn I guess you can close the JDT issue.

**Comment by superbonaci** [comment]
Thank you ,👍
