### ISSUE TITLE
PackageJavadocTests# testFailToAccessAttachedJavadoc test failing 

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#275]
PackageJavadocTests# testFailToAccessAttachedJavadoc test failing in I-build since [I20220920-2240](https://download.eclipse.org/eclipse/downloads/drops4/I20220920-2240/).

**Comment by noopur2507** [comment]
java.lang.AssertionError: <html><head><style CHARSET="ISO-8859-1" TYPE="text/css">/* Font definitions */
html { font-family: 'Segoe UI',sans-serif; font-size: 9pt; font-style: normal; font-weight: normal; }
body, h1, h2, h3, h4, h5, h6, p, table, td, caption, th, ul, ol, dl, li, dd, dt { font-size: 1em; }
pre { font-family: monospace; }

/* Margins */
body { overflow: auto; margin-top: 0px; margin-bottom: 0.5em; margin-left: 0.3em; margin-right: 0px; }
h1 { margin-top: 0.3em; margin-bottom: 0.04em; }
h2 { margin-top: 2em; margin-bottom: 0.25em; }
h3 { margin-top: 1.7em; margin-bottom: 0.25em; }
h4 { margin-top: 2em; margin-bottom: 0.3em; }
h5 { margin-top: 0px; margin-bottom: 0px; }
p { margin-top: 1em; margin-bottom: 1em; }
pre { margin-left: 0.6em; }
ul { margin-top: 0px; margin-bottom: 1em; margin-left: 1em; padding-left: 1em;}
li { margin-top: 0px; margin-bottom: 0px; }
li p { margin-top: 0px; margin-bottom: 0px; }
ol { margin-top: 0px; margin-bottom: 1em; margin-left: 1em; padding-left: 1em; }
dl { margin-top: 0px; margin-bottom: 1em; }
dt { margin-top: 0px; margin-bottom: 0px; font-weight: bold; }
dd { margin-top: 0px; margin-bottom: 0px; }

/* Styles and colors */
a:link { color: #0066cc; } /* get's replaced with actual color */
a:hover { color: #00478f; } /* get's replaced with actual color */
a:visited { text-decoration: underline; }
a.header:link { text-decoration: none; color: #000000 }
a.header:visited { text-decoration: none; color: #000000 }
a.header:hover { text-decoration: underline; color: #00478f; } /* get's replaced with actual color */
h4 { font-style: italic; }
strong { font-weight: bold; }
em { font-style: italic; }
var { font-style: italic; }
th { font-weight: bold; }

/* Workarounds for new Javadoc stylesheet (1.7) */
ul.blockList li.blockList, ul.blockListLast li.blockList {
list-style:none;
}
ul.blockList ul.blockList ul.blockList ul.blockList li.blockListLast {
list-style:none;
}
</style>
<base href='https://docs.oracle.com/javase/6/docs/apii/java/math/package-summary.html'>
</head><body text="#000000" bgcolor="#ffffe1"><h5><div style='word-wrap: break-word; position: relative; margin-left: 20px; padding-top: 2px; '><a href='eclipse-open:%E2%98%82=TestSetupProject/C:%5C/Users%5C/genie.releng%5C/workspace%5C/ep426I-unit-win32-java11%5C/workarea%5C/I20220921-1800%5C/eclipse-testing%5C/test-eclipse%5C/eclipse%5C/plugins%5C/org.eclipse.jdt.ui.tests_3.14.500.v20220909-2154%5C/testresources%5C/rtstubs15.jar=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/javase%5C/6%5C/docs%5C/apii%5C/=/%3Cjava.math'>

<img alt='Open Declaration' style='border:none; position: absolute; width: 16px; height: 16px; left: -21px; ' src='file:/C:/Users/genie.releng/workspace/ep426I-unit-win32-java11/workarea/I20220921-1800/eclipse-testing/test-eclipse/eclipse/jdt_folder/.metadata/.plugins/org.eclipse.jdt.ui/jdt-images/0.png'/>


</a><a class='header' href='eclipse-javadoc:%E2%98%82=TestSetupProject/C:%5C/Users%5C/genie.releng%5C/workspace%5C/ep426I-unit-win32-java11%5C/workarea%5C/I20220921-1800%5C/eclipse-testing%5C/test-eclipse%5C/eclipse%5C/plugins%5C/org.eclipse.jdt.ui.tests_3.14.500.v20220909-2154%5C/testresources%5C/rtstubs15.jar=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/javase%5C/6%5C/docs%5C/apii%5C/=/%3Cjava'>java</a>.math</div></h5><br><p></body></html>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.jdt.ui.tests.hover.PackageJavadocTests.testFailToAccessAttachedJavadoc(PackageJavadocTests.java:354)

**Comment by iloveeclipse** [comment]
Duplicate of #272

**Comment by noopur2507** [comment]
> Duplicate of #272

OK. Closing this one.
