### ISSUE TITLE
[refactor] Import static doesn't work when static method is referenced from subtype

### ISSUE THREAD

**Issue by fapdash** [eclipse-jdt/eclipse.jdt.ui#276]
[Original report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=484727) by Lukas Eder: 

Consider the following classes:

```java
package x;

public class A {
    public static void m() {}
}
```

```java
package x;

public class B extends A {

}
```

```java
import x.B;

public class Test {
    void x() {
        B.m();
    }
}
```

I want to be able to click on "m()" and static-import the method via Ctrl+Shift+M or "Right click > Source > Add Import". If I do this, nothing happens. If I do Ctrl+Shift+M on "m()" in the following class, it works:

```java
import static x.A.m;

public class Test {
    void x() {
        m();
    }
}
```

---

I copied the issue to GitHub because Eclipse Genie wanted to close it over on bugzilla.
I intend to work on this issue in the coming weeks.

**Comment by jjohnstn** [comment]
Verified for 4.26 M3 using I20221108 build.
