### ISSUE TITLE
Executing Junit4 based test fails using Junit5 based launch configuration (test not found) 

### ISSUE THREAD

**Issue by carstenartur** [eclipse-jdt/eclipse.jdt.ui#282]
It looks like you removed support for legacy (Junit3+4) tests in junit 5 run configurations in 4.24(?? Is this true or is there something changed in the defaults?). I remember there have been commits to remove legacy support. While it is possible to switch the run configuration back to junit 4 on each test execution it is slightly annoying to be forced to do this.

**Comment by jjohnstn** [comment]
Hi Carsten.  There isn't any JDT patch I can find that mentions removing Junit3+4 testing support.  I have a Junit3 test that has a Run Configuration and it runs as JUnit3.  Do you have a specific case you can elaborate?

**Comment by carstenartur** [comment]
> Hi Carsten. There isn't any JDT patch I can find that mentions removing Junit3+4 testing support. I have a Junit3 test that has a Run Configuration and it runs as JUnit3. Do you have a specific case you can elaborate?

If you feel like trying it yourself just try to start the junit 5 parametrized test at
https://github.com/carstenartur/sandbox/blob/main/sandbox_platform_helper_test/src/org/sandbox/jdt/ui/tests/quickfix/Java8CleanUpTest.java
However it is not exactly the junit 5 case I mean - though it might be related.
