### ISSUE TITLE
result of `fori` postfix is strange

### ISSUE THREAD

**Issue by jdneo** [eclipse-jdt/eclipse.jdt.ui#299]
Given the code

```java
public static void main(String[] args) {
    args.fori|
}
```

When trigger the `fori` postfix, it generates the following code:

```java
for (int args2 = 0; i < args.length; args2++) {
		
}
```

The index variables should be either `args2` or `i`, but here it's mixed together. Is this on purpose?

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/templates/default-postfixtemplates.xml#L37

**Comment by jjohnstn** [comment]
Agreed.  I have posted a fix to make the indexing consistent.

**Comment by jjohnstn** [comment]
Verified for 4.26 M3 using I20221108 build.
