### ISSUE TITLE
[JUnit] `JUnit4TestFinder` large project performance

### ISSUE THREAD

**Issue by eric-milles** [eclipse-jdt/eclipse.jdt.ui#302]
Original discussion: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540712

I have been investigating _Run As > JUnit Test_ start times for a while now.  I think there are some opportunities in `JUnit4TestFinder` to make some improvements.  

1. After `newTypeHierarchy`, all of the types from a source folder, package or project are added to the search scope.  Later, abstract or inaccessible types are excluded from the result.  Q: Is it necessary to search abstract types or anonymous types for test methods?  Is it possible in JUnit 4 to find any test cases this way?  [RxJava](https://github.com/ReactiveX/RxJava) has about 2000 test classes and over 7000 anonymous inner classes.  Minimally, I am proposing that `createJavaSearchScope` be passed only non-anonymous types.  This can be checked without fetching element info using `aClass.getElementName().isEmpty()` -- anonymous inner classes return an empty name.  The abstract test requires creating element info, so I can understand why you might wait until after.

1. After finding all test types, the `candidates` set is filtered by accessibility, abstractness and containment.  At the very least, the abstract check should be the least expensive and can be moved up front:
`if (!Flags.isAbstract(curr.getFlags()) && CoreTestSearchEngine.isAccessibleClass(curr) && region.contains(curr))`

1. Similarly in `JUnit5TestFinder` there are some expensive things like parsing within `internalIsTest`, so I propose changing the order of checks within `findTestsInContainer`:
`if (region.contains(type) && internalIsTest(type, pm))`

1. Lastly, within `JUnit5TestFinder#internalIsTest` is there a way to determine "is test" using only the `IType` passed in?  Is the `TypeBinding` the only way to make the determination?

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit4TestFinder.java#L132
https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/launcher/JUnit5TestFinder.java#L221

**Comment by jjohnstn** [comment]
I think points 1-3 are reasonable with 1 removing anonymous classes.  Do you want to submit a PR or have me do it and you can test it with your project to verify?

**Comment by eric-milles** [comment]
If you could make the changes that would be great.  I don't have a jdt.ui fork or tests ready.

**Comment by jjohnstn** [comment]
Ok, PR created.  If you could verify this makes a difference on the project you opened the issue on, that would be helpful.

**Comment by eric-milles** [comment]
Is there an update site or bundle created for the PR build/checks?  Is the only way to test to import the plugin project into PDE and build/deploy?

**Comment by jjohnstn** [comment]
Yes, you will need to import the plugin project and deploy or do a local build with -Pbuild-individual-bundles.  There won't be an I-build available until the patch is merged which requires at least verifying it fixes problems.

**Comment by eric-milles** [comment]
After downloading the branch and working out Java 17 and Maven 3.5.4 minimums, I get this error:

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:4.0.0-SNAPSHOT:build-qualifier (default-build-qualifier) on project org.eclipse.ltk.core.refactoring: No git repository found searching upwards from C:\Users\xxx\yyy\eclipse.jdt.ui-1-0b847091f80912e01032597ede8ac087a41ef00b\org.eclipse.ltk.core.refactoring -> [Help 1]

**Comment by eric-milles** [comment]
Thanks for making this change.  I can confirm that under Eclipse 4.25 the start time for RxJava 2.2.3 tests went from ~20s to ~13s.

**Comment by jjohnstn** [comment]
Great, patch merged.

**Comment by eric-milles** [comment]
@jdneo @jjohnstn The performance of `JUnit5TestFinder#internalIsTest` has come up again.  Would it be possible to make a two-phase determination?  First, check the `IType` passed for annotations using the JDT API.  Then if not a test, continue to AST parsing as is done currently?  I may be able to mock something up and experiment with it if you're game to make a change here.

**Comment by jdneo** [comment]
> First, check the IType passed for annotations using the JDT API. 

Sorry not quite get the idea. Could you give more details about this sentence?
