### ISSUE TITLE
Eclipse 2022-03 Window -> Preferences -> Java -> Appearance : Compress all package name segments not compressing packages

### ISSUE THREAD

**Issue by jonmichaelpeedin** [eclipse-jdt/eclipse.jdt.ui#32]
This was previously posted in the eclipse-platform (https://github.com/eclipse-platform/.github/issues/5) and was requested to be posted to eclipse-jdt/eclipse.jdt.ui  as an issue. 

Upon recently upgrading to 2022-03 I have noticed that the "Compress all package name segments, except the final segment" is not compressing the packages in my project. I have attempted to use the compression pattern '.', '0', and '1' with no success.

I also attempted to use the "Abbreviate package names" and that was not doing anything to the package names that I specified either.

I have manage to figure out the following since the original post to the eclipse-platform issues: 
I deleted the .project file for my project and it displayed properly, however when I converted it back to a faceted project the issue comes back. Please see attached screenshots

![E2022-03_CompressPackageIssue_1](https://user-images.githubusercontent.com/48923241/166269910-dd32493e-c8e3-456a-8893-af1d553d0035.PNG)
![E2022-03_CompressPackageIssue_2](https://user-images.githubusercontent.com/48923241/166269918-88fe9f92-5341-49fc-8230-4e3d4ba1a019.PNG)
![E2022-03_CompressPackageIssue_3](https://user-images.githubusercontent.com/48923241/166269930-7a10a868-0def-4c94-84a5-a4e14474238f.PNG)
![E2022-03_CompressPackageIssue_4](https://user-images.githubusercontent.com/48923241/166269936-2e2fa671-b9a8-403a-a816-f4fa9469c304.PNG)

**Comment by iloveeclipse** [comment]
@mickaelistria : thanks, this is surely https://bugs.eclipse.org/bugs/show_bug.cgi?id=579170.

@jonmichaelpeedin : AFAIK there is no "final" release yet containing the webtools fix, only M1 build : 

https://www.eclipse.org/downloads/packages/release/2022-06/m1

So please update webtools from that and if this doesn't fix your issue, comment on original bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=579170.

JDT has nothing to do with "faceted projects"

**Comment by jonmichaelpeedin** [comment]
Updating the WebTools to 2022-06 solved the issue, thank you.
