### ISSUE TITLE
Freeze on launch

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#326]
After launching Eclipse I see that the window is freezed, it says that eclipse.exe is not responding.

**Comment by iloveeclipse** [comment]
Create thread dump and attach it here please.

**Comment by andreasdc** [comment]
How to do it?

**Comment by iloveeclipse** [comment]
Please search with your preferred search provider "how to create Java thread dump".

**Comment by andreasdc** [comment]
Is it necessary?

**Comment by andreasdc** [comment]
I guess it wasn't necessary, I don't see this issue anymore. :)
