### ISSUE TITLE
Improve the Safety of "Extract Local Variable" Refactorings concering ClassCasts

### ISSUE THREAD

**Issue by chixiaye** [eclipse-jdt/eclipse.jdt.ui#331]
# Improve the Safety of "Extract Local Variable" Refactorings concerning ClassCasts

## Description
In previous work (commit ID: [2987007](https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/2987007d9703de02eea83081a0b7b65fdc6e4a84)), we improved the safety of extract variable refactorings in JDT that otherwise may have resulted in NullPointerException. However, as specified in the issue(issue ID: [39](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/39)), if the extracted expression is a classcast, the extract variable refactoring conducted by JDT may result in NULLPOINTER EXCEPTION as well. This problem has not yet been fixed. 

Considering such example:
```java
1   /* CS1: Original Code Snippet */
2    void foo(Object obj){
3       if(obj instanceof Integer && ((Integer)obj).intValue() > 0){
4             System.out.println(((Integer)obj).intValue());
5       }else if(obj instanceof Float && ((Float)obj).floatValue() > 0.0){
6            System.out.println(((Float)obj).floatValue());
7       }
8    }
``` 

If we select the expression `((Integer)obj).intValue()` (line `4` in `CS1`), and conduct refactoring "extract local variable",and name the new variable as `value`, we will get the following code snippet:
```java
1   /* CS2: Refactored Code Snippet */
2    void foo(Object obj){
3       int value = ((Integer) obj).intValue();
4       if(obj instanceof Integer && value > 0){
5             System.out.println(value);
6       }else if(obj instanceof Float && ((Float)obj).floatValue() > 0.0){
7            System.out.println(((Float)obj).floatValue());
8       }
9    }
``` 

Such refactoring is incorrect and dangerous. If the method is called via `foo(new Float(3.5))`, the refactored version of the method would result in ClassCastException whereas the original version would not.

## Solution
The main difference between NullPointerException case and ClassCastException case is the condition that would cause ClassCastException. We defined the case as sub-condition `obj` instanceof `Class1` and sub-condition `((Class2)obj).method()` occur sequentially in the same logical expression which is between the declaration position and the position where the first expression appears, where `Class2` is the superclass of `Class1`.

The correct and safe refactorings would be as:
```java
1   /* CS3: Safe Refactored Code Snippet */
2    void foo(Object obj){
3       if(obj instanceof Integer && ((Integer)obj).intValue() > 0){
4             int value = ((Integer) obj).intValue();
5             System.out.println(value);
6       }else if(obj instanceof Float && ((Float)obj).floatValue() > 0.0){
7            System.out.println(((Float)obj).floatValue());
8       }
9    }
``` 

**The corresponding PR will be submitted later.**

**Comment by chixiaye** [comment]
@ktatavarthi hi, could you please confirm the bug report? Thanks a lot.

**Comment by liuhuigmail** [comment]
The patch for this issue is under review now (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/333#issuecomment-1339462032). 

Can somebody help to check this issue and kindly confirm the bug?  Thanks.

**Comment by jjohnstn** [comment]
Closing this issue as the PR has been merged.
