### ISSUE TITLE
Remove overridden assignment with combine statement results in two ;

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#36]
``
	ImageDescriptor desc = info.getFeatureImage();
		Image featureImage = null;

		Button button = new Button(parent, SWT.FLAT | SWT.PUSH);
		button.setData(info);
		featureImage = desc.createImage();
```
ends up as 
```
		ImageDescriptor desc = info.getFeatureImage();
		Button button = new Button(parent, SWT.FLAT | SWT.PUSH);
		button.setData(info);
		Image featureImage = desc.createImage();;
		images.add(featureImage);
```

I push the PR andl link to it here so that you can see that.

**Comment by vogella** [comment]
@tsmaeder please see https://github.com/eclipse-platform/eclipse.platform.ui/pull/57

**Comment by vogella** [comment]
If you run the updated clean-up on platform ui repo you all lots of these ;; changes.

**Comment by jjohnstn** [comment]
Hi Lars.  I found the problem.  In our testing, we have the default cleanup option to remove redundant semi-colons.  Anyway, the assignment was being replaced by a declaration statement which ends up with the double semi-colons.  I have a fix that I will post immediately.

**Comment by vogella** [comment]
Thanks, looks good. Found another issue and opened https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/38 ticket for this.
