### ISSUE TITLE
Spell Checker issues error for Javadoc tag @param

### ISSUE THREAD

**Issue by duesentrieb17** [eclipse-jdt/eclipse.jdt.ui#365]
Version: 2022-12 RC1 (4.26.0 RC1)
Build id: 20221124-2251
```
package bugs;

public class Param {
    /**
     * @param i
     * @return i
     */
    public int test(int i) {
        return i;
    }
}
```
![spelling_error](https://user-images.githubusercontent.com/34717473/205303594-04d61d68-fca4-49e2-9f4f-1f5587cb205a.png)

**Comment by mariomarinato** [comment]
Hello, @jjohnstn, I see this problem happening on Eclipse 2024-06.  Would you care to take a look at it?

**Comment by jjohnstn** [comment]
@mariomarinato I'll take a look

**Comment by jjohnstn** [comment]
@mariomarinato I tried with 2024-06 Java EPP package on Linux and it works fine.  I also tried with latest Eclipse I-build and it worked fine as well.  Can you provide some context?  Do you have an example that is failing?  Do you by any chance have some additional plug-ins installed that might be interferring (e.g. gradle)?  As well, can you provide info from About Eclipse?

**Comment by mariomarinato** [comment]
@jjohnstn I'm using Eclipse 2024-06 for RCP.  Indeed, the message I get is a bit different from the one originally posted here:

![spellError](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/6649014/476b7477-213e-4897-ac67-dff07e65384e)

Checking the option _Ignore non-letters at word boundaries_ makes no difference.

Here's the About Eclipse screen (is that you wanted to see?)

![about](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/6649014/da3bb9db-2229-4872-9f31-99f044ec000f)

We have a few additional plug-ins installed.  I'll try a fresh installation to check if any of them might be the cause.
