### ISSUE TITLE
New keywords (like `record` and `sealed`) are colored like the `return` keyword

### ISSUE THREAD

**Issue by hjohn** [eclipse-jdt/eclipse.jdt.ui#368]
I've configured the return keyword to stand out with the Eclipse preference `Java > Editor > Syntax Coloring` "Keyword 'return'".  New keywords take on this color, instead of the color set for "Keywords excluding 'return'".

See screenshot:

![image](https://user-images.githubusercontent.com/995917/210975262-59c4e070-f1cf-41be-b405-80ae183dd4db.png)

Expected:

I would except these new keywords to be colored like regular keywords.

**Comment by PhilippWendler** [comment]
For me, `record` is formatted in the color chosen for "Restricted identifiers". Maybe try changing this color definition?

These new keywords are not really regular keywords but "contextual keywords".

**Comment by jjohnstn** [comment]
Hi @hjohn, @PhilippWendler is correct.  The color for record and sealed is set via the "Restricted identifiers" color category.  I will close this issue.
