### ISSUE TITLE
Code Minings - Method call occurences for common named methods are not correctly calculated

### ISSUE THREAD

**Issue by CarlosMOGoncalves** [eclipse-jdt/eclipse.jdt.ui#370]
# Description #
----------

Hello there, 

I noticed Code Minings is not calculating correct occurences of, at least, methods. 
This has likely something to do with the way occurences are found.
I don't know when it started working like this.

## Expected Outcome ##

I expect that an occurence of a method call is calculated in the same way as **"Open Call Hierarchy"** option or at least that shows the call occurences in the workspace.

## Current Outcome ##

Some methods, depending on their name and/or signature will be marked has having `"X occurences"` but these don't match any actual call of that method, but rather any other method with the same name that can be somehow found in the classpath.

## Steps to reproduce ## 

I have prepared a sample application that has a very simple Payara Micro application, whose kind is irrelevant to the case in point.
It can be found [here](https://github.com/CarlosMOGoncalves/eclipse-issue-tester)

This app does nothing special. It has a Jakarta REST endpoint but that is just for show.

1. Fresh install Eclipse for **Eclipse IDE for Enterprise Java and Web Developers 2022-12**
2. Checkout the project from my repository
3. Run `mvn clean install` on it
4. Activate Code Minings for method references, like this:

![image](https://user-images.githubusercontent.com/2636004/211067333-6b813341-7ab9-4128-b408-f35f8381ad1f.png)

5. Then navigate to the class `NumericUtils.java`, method `getType()`:

![image](https://user-images.githubusercontent.com/2636004/211068009-e46e8ecb-53a9-4e66-8bb3-f932cf4d1249.png)

6. It marks 1 occurence. However, that occurence is not correct, but rather just an occurence a similarly named method on a comment:

![image](https://user-images.githubusercontent.com/2636004/211068338-8b2b6fa0-72f6-4cc3-9874-b735077b01f3.png)

7. If we use "Open Call Hierarchy" on that method we clearly see that no one is calling it:

![image](https://user-images.githubusercontent.com/2636004/211068504-14cf9c17-9acf-477c-b849-5cfa8a168c41.png)

8. The same can be said for methods with common names, like on `TestResource#get()`:

![image](https://user-images.githubusercontent.com/2636004/211068787-ef8ee099-5e92-48d0-94ea-8be710659e30.png)

9. Which is not in fact the right callee:

![image](https://user-images.githubusercontent.com/2636004/211068918-de63533d-749f-4886-b55a-98aaf992ce9b.png)

**Final note**

- sorry for all the Issue ceremony. I used a template from Payara issues as I think it is pleasant to work with.

## Environment ##
- **Distribution**:  Eclipse IDE for Enterprise Java and Web Developers 2022-12 2022-12 for Windows x64
- **JDK Version**: Corretto JDK 11
- **Operating System**:  Windows 10

**Comment by humphreygao** [comment]
![image](https://user-images.githubusercontent.com/52394598/211153835-253a96bf-e2c1-45f6-83a0-2bb3dd962491.png)
uncheck this option may solve this problem. 

> I expect that an occurence of a method call is calculated in the same way as **"Open Call Hierarchy"** option or at least that shows the call occurences in the workspace.
I agree.

**Comment by CarlosMOGoncalves** [comment]
Hello @humphreygao,

Thanks for the quick reply.
Indeed, this prevents those results to be counted as matches. Solves it, basically.

However, I think this brings up the point: **should these kind of "potential matches" be considered in Code Minings?**
Because I think Code Minings is extremely useful for quick checking references to methods (and types, fields), specially to quickly understand and consider dependencies... but these results must be very accurate or they risk losing their value.

Surely, showing potential matches, by default, is not what is expected and potentially highly misleading.

Here's an example. 
This is a screenshot from a somewhat more complex project I have.
There is a JPA entity that has a method called **getType()**, similar to the one in the issue description.
On Code Minings this shows 123 references (!!!), but most of those are in fact from 3rd party libraries which my project depend on which naturally cannot be referencing my project. Check below:

![image](https://user-images.githubusercontent.com/2636004/211300665-2cf11c28-6956-461a-b10c-7af94a79a9af.png)

The actual expected results for this Code Mining is rather this (now with potential matches disabled):

![image](https://user-images.githubusercontent.com/2636004/211301240-db4ee43b-d921-431d-a0d9-d0ed9bf84f21.png)

All of these references are actually in my own project, which is what is correct and expected.

**What do the developers think about this?**
**Wouldn't it be much more accurate to perform the Code Minings default reference search withous "potential matches"?**

**Comment by humphreygao** [comment]
> What do the developers think about this?
Wouldn't it be much more accurate to perform the Code Minings default reference search withous "potential matches"?

Could ask @angelozerr 
as he is the original developer of code mining https://github.com/angelozerr/jdt-codemining

**Comment by humphreygao** [comment]
@jdneo 在写代码时，Eclipse的codelens跳来跳去的，处于几乎不可用状态，但是VS Code就好多了，是怎么做到的？

**Comment by jdneo** [comment]
@humphreygao VS Code has a dedicated job for document update. When trying to resolve the code lens, we will first wait the document update job is finished.

Take the debugger's `Run | Debug` code lens as an example: https://github.com/microsoft/java-debug/blob/42f9ac7d4843b75b1fdde64762d8c5ce4a4c51b2/com.microsoft.java.debug.plugin/src/main/java/com/microsoft/java/debug/plugin/internal/ResolveMainMethodHandler.java#L51-L55

**Comment by jjohnstn** [comment]
| What do the developers think about this?
| Wouldn't it be much more accurate to perform the Code Minings default reference search withous "potential matches"?

I think this could be accomplished by adding a specific option to the Code Minings preferences and not rely on the Search settings which are in another preference page which is unintuitive.  This option could be set to Ignore by default.  What do you think?
