### ISSUE TITLE
JUnit failure trace view: Stracktrace garbled (org.junit.jupiter truncated from message)

### ISSUE THREAD

**Issue by hohwille** [eclipse-jdt/eclipse.jdt.ui#372]
I have to create my own assertion error message in an advanced JUnit.
When I run the JUnit with Maven, I get the proper output:
```
[ERROR] testReadProject  Time elapsed: 0.407 s  <<< FAILURE!
java.lang.AssertionError:
Expected
<[Dependency {groupId=org.apache.maven, artifactId=maven-core, version=3.6.1, type=jar}, Dependency {groupId=io.github.m-m-m, artifactId=mmm-code-base, version=0-SNAPSHOT, type=jar}, Dependency {groupId=org.mockito, artifactId=mockito-junit-jupiter, version=4.9.0, type=jar}, Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter, version=5.9.1, type=jar}, Dependency {groupId=org.assertj, artifactId=assertj-core, version=3.23.1, type=jar}, Dependency {groupId=ch.qos.logback, artifactId=logback-classic, version=1.4.5, type=jar}]>
to contain
<[Dependency {groupId=io.github.m-m-m, artifactId=mmm-code-base, version=0-SNAPSHOT, type=jar}, Dependency {groupId=org.apache.maven, artifactId=maven-core, version=3.6.1, type=jar}, Dependency {groupId=org.assertj, artifactId=assertj-core, version=3.23.1, type=jar}, Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter, version=5.9.0, type=jar}, Dependency {groupId=org.mockito, artifactId=mockito-junit-jupiter, version=4.9.0, type=jar}, Dependency {groupId=ch.qos.logback, artifactId=logback-classic, version=1.4.5, type=jar}]>
but could not find
<[Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter, version=5.9.0, type=jar}]>
 and did not expect
<[Dependency {groupId=org.junit.jupiter, artifactId=junit-jupiter, version=5.9.1, type=jar}]>
        at io.github.mmm.code.java.maven.impl.MavenBridgeImplTest.verifyDependencies(MavenBridgeImplTest.java:133)
        at io.github.mmm.code.java.maven.impl.MavenBridgeImplTest.testReadProject(MavenBridgeImplTest.java:91)
```

However, Eclipse does make evil black magic here and simply removes lines from the exception message that contain brackets:
<img width="1271" alt="Eclipse-JUnit-stracktrace-garbled" src="https://user-images.githubusercontent.com/1923119/211167021-422f9ed9-4a86-466c-b01a-f4fa52565698.png">

As a result the important information is missing and the result is rendered useless.
It would be awesome if you could consider adapting this magic that truncates stacktraces.
I also created a minimal test-case and found out that the keyword `org.junit.jupiter` is triggering this effect.
While it makes fully sense to remove such lines from the actual stacktrace call hierarchy, it IMHO does not make sense to remove it from the actual exception message.
Here is my test-case:
```
import org.junit.jupiter.api.Test;

public class MyTest {
  @Test
  public void test() {
    throw new AssertionError("Eclipse truncates lines with\n[org.junit.jupiter]\nfrom stracktraces.");
  }
}
```

**Comment by hohwille** [comment]
My hope was that after JDK moved to github that issues get seen unlike the eclipse bugzilla graveyard where issues have not been addressed for decades. :)

Is there any feedback on this (e.g. "issue was understood and accepted as bug but with very low prio and PR is welcome")?

**Comment by jjohnstn** [comment]
Will take a look at it.

**Comment by jjohnstn** [comment]
What is happening is that there is an Eclipse preference page that specifies what should be filtered from a JUnit stack trace:

Preferences -> Java -> JUnit

This page displays items to be filtered from a stack trace but the filter is not used on the first line of the trace.  This is the majority of user; if you remove the newline before [org.junit.jupiter], in the example, your information will print as expected.

If you are happy with all the junit info in the traces, you can simply disable the org.junit.* filter in the preferences page and you will see what you see in the left side of your sample trace.

If you would like filtering but don't want to remove "org.junit.jupiter", you can disable the org.junit.* filter and add your own: org.junit.jupiter.* and org.junit.platform.* filters.  These will filter out the stuff in the stack trace but leave your lines where org.junit.jupiter is specified without any trailing .xxxx. 

That said, a code modification could be made to hold off on filtering until it has seen a line that matches a trace line (e.g. starts with " at ").  If you use newlines and also make lines look like a trace line, then you would be out of luck.  4.27 M3 is already frozen so such a modification would have to be a 4.28 M1 item and could be available for an I-build once the master repo is unfrozen post RC1.  If you are happy with the above work-arounds, then I will close this issue.
