### ISSUE TITLE
Remove $author from code template for class and module

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-jdt/eclipse.jdt.ui#374]
The default code templates for new type and new module (maybe others) contain a placeholder to insert the author of that new class/type/module. This was useful at times where many people did not have version control or a version control system that was not easy to use and query.

Today I see more negative than positive benefit:
* The same information is _better_ available in the version control history, with attribution by line instead of assuming this one author for every line currently in the file
* People copy/paste classes to create "something similar", without fixing this comment.
* It may leak information of the private user account to the public (at least on Windows, this defaults to your local user account id, and my company admin would surely not like me posting that account id everywhere).
* Even developers without an underlying version control system should not rely on this information, but rather be nudged to set up a real version control system.

I therefore want to suggest to remove this from all Javadoc-like comment templates (i.e. not from file header copyright banners, it does have benefit there).

Be aware this is not about the JDT or Eclipse platform source code, but about the templates provided by JDT.

**Comment by erik-brangs** [comment]
I think this would be a good change. Personally, I've configured my templates to remove the author information because I just ended up deleting it every time.
