### ISSUE TITLE
Clean up "Convert to switch expression" produces invalid code for end-of-line comments at end of case

### ISSUE THREAD

**Issue by PhilippWendler** [eclipse-jdt/eclipse.jdt.ui#382]
Consider the following code:
```java
public class Test {

  public int f(int i) {
    switch (i) {
      case 0:
        return 0; // comment
      default:
        return 1;
    }
  }
}
```
The cleanup "Convert to switch expression" puts everything on one line, which makes all cases after the one with an end-of-line comment become part of the comment:
![grafik](https://user-images.githubusercontent.com/2545335/212089385-f6f6fc8a-3cae-47e4-8fc6-ec4ddc82e03e.png)
Note the `// commentdefault return 1;`.

The clean up should not join all lines into one in order to avoid this.

I am using version 4.26.0.20221201-1200 of the Eclipse IDE for Java Developers and version 3.27.100.v20221122-0749 of `org.eclipse.jdt.ui`, which is the latest that the updater offers for me.

**Comment by jjohnstn** [comment]
Hi @PhilippWendler I am unable to reproduce this problem.  I get:

```
public class Test {

	public int f(int i) {
		return switch (i) {
		case 0 -> 0; // comment
		default -> 1;
		};
	}

}
```
Do you have any special formatting options set up to put everything on one line?

I am using the Eclipse IDE for Eclipse Committers 2022-12 4.26.0.  I also get the same results when I use a child Eclipse that uses latest JDT UI sources that I am using to work on 4.27 M2.

**Comment by PhilippWendler** [comment]
Weird. I cannot reproduce this anymore as well. I use the Eclipse plugin for google-java-format as formatter, and last week I had some problems with it because the latest version does not work. But even when I replicate the situation with the non-working formatter, I cannot reproduce this issue. So no idea what happened back then. Sorry for the noise!

And thanks a lot for the fast response and fixes also for my other issues!
