### ISSUE TITLE
Incorrect "Extract Variable" refactoring, resulting in NullPointerException

### ISSUE THREAD

**Issue by chixiaye** [eclipse-jdt/eclipse.jdt.ui#39]
# Incorrect "Extract Variable" refactoring, resulting in NullPointerException

## Description
"Extract Variable" refactoring is a useful feature of JDT. However, in some cases, it may not work correctly. Here we report a bug in this feature and attach a feasible patch for the bug.

We take the following sample code to illustrate the bug:  
```java
1   /* CS1: Original Code Snippet */
2   public String metaPhone(final String txt){
3       boolean hard = false;
4       if(txt == null || txt.length() == 0){
5           return "";
6       }
7       if(txt.length() == 1){
8           return txt.toUpperCase(java.util.Local.ENGLISH);
9       }
10      //Do other things
11      // ...
12   }
``` 

If we select expression `txt.length()` (line `4` in `CS1`), conduct refactoring "extract local variable",and name the new variable as `length` , we will get the following code snippet:
```java
1   /* CS2: Code Snippet after refactoring */
2   public String metaPhone(final String txt){
3       boolean hard = false;
4       int length = txt.length();
5       if(txt == null || length == 0){
6           return "";
7       }
8       if(length == 1){
9           return txt.toUpperCase(java.util.Local.ENGLISH);
10       }
11      //Do other things
12      // ...
13   }
``` 

The refactoring is incorrect and dangerous. If the method is called via `metaphone(null)`, the refactored version of the method would result in NullPointerException whereas the original version would not.

## Solution
The most simple and intuitive solution is to WARN the developers if the refactored version would result in NullPointerException.

- First, once developers select an expression and invoke "extract variable" refactoring, we create a list of subexpressions of the selected expression. For example, if we extract expression like `a.b.f().c`, the list should contain `a`, `a.b`, and `a.b.f()`. The list is noted as `ExpList`.

- Second, we analyze the code snippet between the newly introduced local variable declaration (line `4` in `CS2`) and the first usage of the variable (line `5` in `CS2`). If the code snippet contains InfixExpression node like `x==null`, and `x` is on `ExpList`, we warn the developer with clear information about the potential problem. 
 
<img width="1114" alt="pic" src="https://user-images.githubusercontent.com/54989108/167254733-0d0e60d9-07a2-4212-b6f6-aa62ea11ce58.png">

Similar error may occur when developers select `txt.length()` on other places (i.e., line `7` in `CS1`) to conduct "extract variable" refactoring. The refactoring will get the same result as `CS2`.

To this end, we apply a greedy strategy to extract as many as expressions without introducing NullPointerException. 

- First, we validate whether the selected expression (`EXP`)itself could be extracted safely. If not, we warn the developers. 
- Second, we search backward from `EXP` for expressions identical to `EXP`, and validate whether they could be extracted together safely. Resulting in a sequence of instances of the expression, noted as `InsExp1`.
- Third, we search forward from `EXP` for expressions identical to `EXP`, and validate whether they could be extracted together. Resulting in a sequence of instances of the expression, noted as `InsExp2`.
- Finally, we declare and initialize a local variable `var` and replace all instances in `InsExp2`, `EXP`, and `InsExp2`.
- The refactoring is accomplished.

**The relevant code has been completed and the corresponding PR will be submitted later.**

**Comment by jjohnstn** [comment]
I believe the correct answer is that the declaration should never be backed up before the null check.  In the example given, it should be placed just before its usage in the second if statement.  A cleanup/refactoring should never change the behaviour of the code if possible.  In this case, if we can identify there is a potential issue, we can create valid code instead of warning the user.  I will take a look at your PR to see if it can be used for this.  I think it may need to be more generic (e.g. look for all assignments and checks of the field/method's expression pieces), but I haven't looked at it closer.  It also will need a test case.

**Comment by jjohnstn** [comment]
I see with your change that you do this correctly if the user picks the second txt.length() call to refactor.  It only changes the 2nd call and subsequent calls and puts the declaration before the 2nd if statement.  However, when the first txt.length() statement is chosen, you issue the warning and then only the first txt.length() gets changed if the user continues.  I would like the code to recognize the issue and then skip to the next use and do exactly what you do for the 2nd call.

**Comment by chixiaye** [comment]
Thanks a lot for your reply! For the past few months, we've been working on improving extracting local variable refactoring, and the completed code will be submitted as a patch later. 

As you suggested, if the first `txt.length()` is chosen, the result of conducting refactoring would be the same as the second `txt.length()`. We only warn if only one expression is extracted and such refactoring would result in NullPointerException. Besides, we have added relevant test cases to verify the check. The modification of the relevant code has been committed to PR.

**Comment by jjohnstn** [comment]
I will take a look.

**Comment by jjohnstn** [comment]
I tried out the latest code.  Works much better, thanks.  For the first call, it leaves it alone and puts the local variable after the first if without any warnings; same behavior when the 2nd txt.length() call is selected.  I'll take a look at why it is not building with latest rebase and do the official code review.

**Comment by liuhuigmail** [comment]
@jjohnstn  Thank you for reviewing the pull request. We have reported another similar bug (https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/331) concering the Extract Local Varialbe refactoring, and have submitted the corresponding patch (https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/333). We notice that the bug report has not yet been handled althougt it has been submitted for quite a long time (17 days). Would you please kindly help to review the bug report and its corresponding pull resust?  Thank you.

**Comment by jjohnstn** [comment]
@liuhuigmail Hi, we are just wrapping up the final details of the 2022-12 release so I will take a look this week.

**Comment by liuhuigmail** [comment]
@jjohnstn Thank you.
