### ISSUE TITLE
Indentation setting of formatter "forgotten" sometimes

### ISSUE THREAD

**Issue by odrotbohm** [eclipse-jdt/eclipse.jdt.ui#413]
I have a formatter setup using tabbed indentation and a tad width of two. Sometimes, after restarting Eclipse, these indentation settings are not applied anymore. The symptom is that I see tabs with the default width in the editor and when applying the formatter the sources change to space-based indentation. I can fix this problem by going to the formatter settings, switching to space-based indentation and then back to tab-based in the formatter.

Not that I also see the preference "General > Editors > Text Editors > Insert spaces for tabs" has been reactivated (I had explicitly disabled that before). I wonder if it's rather a bug in reading that setting that, if erroneously activated on startup, overrules the indentation settings of the formatter?

**Comment by iloveeclipse** [comment]
You use Oomph and that one simply restores your previously saved settings on startup in every workspace.

**Comment by odrotbohm** [comment]
No, I don't. I use a downloaded STS and the phenomenon appears without any changes to the platform (no updates or the liked).

**Comment by iloveeclipse** [comment]
> I use a downloaded STS

You should probably report that to the STS first?

**Comment by odrotbohm** [comment]
Neither the general editor preference pane nor the JDT formatter settings are part of STS, right?

**Comment by odrotbohm** [comment]
I see, thanks for clarifying. I'll make sure I'm not gonna bother you in the future anymore.

**Comment by cnmade** [comment]
https://spring.io/tools  

STS is short called of Spring boot Tools, It is really base on Eclipse.

**Comment by cnmade** [comment]
@iloveeclipse Oliver Drotbohm 🥁 & 👨‍💻
[@odrotbohm](https://twitter.com/odrotbohm)
Frameworks & Architecture in the Spring team @ VMware, OpenSource, all things Spring, Java, data, DDD, REST, software architecture, drums & music. He/him.

**Comment by iloveeclipse** [comment]
> It is really base on Eclipse.

No one doubted that. The question not answered is: since we have no related bugs reported for such basic functionality for the platform, could it be, that STS should investigate the problem first? There are many ways a product can change platform behavior, and not everything that is added by products is bug/side effects free.

**Comment by martinlippert** [comment]
@iloveeclipse @odrotbohm Don't worry, I am involved here from the Spring Tools side and happy to help investigating this issue. No need to have a discussion around where to report his first, let's focus on the issue and try to reproduce this in the various environments to get to the bottom of this. Will keep you updated here.

**Comment by martinlippert** [comment]
@odrotbohm I tried to reproduce this with the latest STS 4.17.2 as well as the most recent nightly builds based on Eclipse 2023-03 and wasn't able to reproduce this. Ping me when you are around and we can take a look at your specific installation to see what is going on here.
