### ISSUE TITLE
Indent action indents unformatted text block wrongly

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.ui#414]
This is a continuation of #30, which was fixed only partially with #33. We use the `Correct Indentation` save action and its applying odd indentations in our code.

E.g. with default formatter settings, the following (already formatted) snippet is no longer indented wrongly due to #30:

```
	public static void main(String[] args) {
		String a = """
				    line1
				    line2
				""";
		System.out.println(a);
	}
```

However, for a snippet that is not formatted, the formatting done by the indent action is wrong when compared to formatting the source.

Unformatted snippet:

```
	public static void main(String[] args) {
		String a =
				"""
				    line1
				    line2
				""";
		System.out.println(a);
	}
```

Formatting the whole snippet: 

```
	public static void main(String[] args) {
		String a = """
				    line1
				    line2
				""";
		System.out.println(a);
	}
```

Indent action after selecting the snippet, this is also done for the `Correct Indentation` save action:

```
	public static void main(String[] args) {
		String a =
				"""
						    line1
						    line2
						""";
		System.out.println(a);
	}
```

This is due to the indent action formatting each line separately, in which case the default formatter options result in the misaligned lines seen above. The fix for #30 addresses some cases of this (e.g. select the text block and `String a =`), but not all.

The expected outcome of the save action is to have the source look like formatted as a whole, since its supposed to correct indentations for all of the file.

**Comment by trancexpress** [comment]
Hi @jjohnstn ,

any idea what might be missing in #33, when a text block starts on a separate line? Is maybe the "0 indentation" assumption (`TextBlockInfo textBlockInfo= new TextBlockInfo(-1, -1);`, from #33) wrong for that case?

Best regards and thanks,
Simeon

**Comment by jjohnstn** [comment]
Hi @trancexpress I'll have to take a look.  It's been a while since I looked at that code.

**Comment by trancexpress** [comment]
> Hi @trancexpress I'll have to take a look. It's been a while since I looked at that code.

That would be great, though its nothing urgent. We switched to the "Indent on column" option for text blocks since that seems to work best for us. If a potential fix is too complicated (or even looking into a fix is too much effort), its probably not worth investing time in.

**Comment by jjohnstn** [comment]
From my experiments here, the code is implementing the chosen strategy based on the first line.  The formatter is moving the opening """ to the first line, then following the strategy.  In the case of just indenting, the opening """ is treated as the first line with the strategy followed from there.

**Comment by jjohnstn** [comment]
Hi, the logic has been changed to make the indenting consistent whether the open quotes for the text block occur on their own line or the end of a previous line.  In either case, the indent will use the previous non-empty statement.
