### ISSUE TITLE
Type filtering shouldn't apply to completion proposals dereferencing an object.

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.ui#417]
From
```java
		com.sun.tools.javac.main.JavaCompiler javac = com.sun.tools.javac.main.JavaCompiler.instance(new com.sun.tools.javac.util.Context());
		javac.|
```
trying to complete on `|` gives nothing useful, no field of the `JavaCompiler` type. However, although type `com.sun.*` is filtered out (it wasn't proposed earlier as type and that's OK), once we know the type of the object, it doesn't seem useful to filter out the fields and methods.
In such case, filtering shouldn't apply to fields and methods, it should probably only apply to hide types or other proposals coming from a filtered type *that is not the dereferenced object*.

**Comment by iloveeclipse** [comment]
The fix caused a regression in debugger, see https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/239
