### ISSUE TITLE
Export a runnable JAR fails to include plugin dependencies with Maven nature enabled

### ISSUE THREAD

**Issue by philip-iii** [eclipse-jdt/eclipse.jdt.ui#418]
When trying to export a runnable JAR from a launch configuration of a plugin project that has dependencies included in the manifest, and also the maven nature enabled, the exported JAR does not include the needed dependencies indicated in the manifest. Disabling the maven nature does seem to help, but the run configuration needs to be updated. Not sure if this is a problem of the JDT UI or the Maven integration, but it seems to impact the JDT UI so I put it here.

To reproduce in more detail:

1. Create a plugin project that uses some Eclipse component via the manifest, e.g. create a simple swt project from https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet1.java
1. Run as java
1. Export as Runnable jar with copying required libraries in a subfolder (for visibility) -> the sub-folder contains the required libraries

Enabling maven
1. Repeat the first step above with a separate project, then add maven nature to the project (convert to maven project)
1. Run as java
1. Export as Runnable jar with copying required libraries in a subfolder (for visibility) -> the sub-folder is empty
1. Removing the maven nature and adjusting the run configuration to remove the CLASSPATH_PROVIDER and SOURCE_PATH_PROVIDER entries (not accessible through the UI) and repeating the export seems to fix the issue.

If needed I can provide a repo with all the projects, but it is fairly easy to reproduce as described.

**Comment by jjohnstn** [comment]
Closing this until diagnosis by M2E
