### ISSUE TITLE
Everything is being highlighted

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#421]
Even when I drag the mouse on the double or something it's getting highlighted and big window shows, how to disable that?

**Comment by jjohnstn** [comment]
Hello @andreasdc You are going to have provide details about how to reproduce your problem (i.e. what version of Eclipse were you using, on what system, a sample of code you were editing, what sequence of operations you were doing, what happened, and what you expected to happen) for anyone to work on this.  A picture would also help if you can provide one (before/after).

**Comment by andreasdc** [comment]
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

When for exameple I drag over the String class it shows me big window, maybe it shows too soon?

**Comment by JanecekPetr** [comment]
By "big window" do you mean the JavaDoc for the given class? That's most commonly a fairly small dialog (and goes away immediately if you move away), please show us a screenshot or provide more context on what's going on.

As a side-note, you can disable the dialogs on hover via Preferences -> Java -> Editor -> Hovers, or you can configure them to only appear when a specific modifier key is pressed.

Also on my machine (Mac) the hover delay is +/- 1 second which does not seem to be a bad value at all. Apparently there's no direct way to change the delay as it comes from the OS, but there are some blogposts with alternative approaches if you're on Windows: https://untamedmind.wordpress.com/2008/11/08/changing-the-mousehovertime-add-delay-on-the-tooltips-pop-up/, https://dandar3.blogspot.com/2008/09/tooltip-delay-in-windows.html. I have not tried either of those.

**Comment by andreasdc** [comment]
I want to change it for eclipse. For me window appears almost instantly, it wasn't like that before.

**Comment by iloveeclipse** [comment]
@andreasdc : please provide a screenshot, I have no idea what "big window" you are referring too.

**Comment by andreasdc** [comment]
The one that is described above, this window doesn't appear on screenshots. Yellow window with javadocs.

**Comment by iloveeclipse** [comment]
> The one that is described above

Sorry, I do not want description,  if you need help, **please** provide a **screenshot**.

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/223156384-3dd2e407-9611-4220-a72a-a1c229823a89.png)

**Comment by andreasdc** [comment]
I don't want to disable that.

**Comment by andreasdc** [comment]
It blocks typing and it is being diplayed wrongly for sure.

**Comment by andreasdc** [comment]
Is there a way to improve this?
