### ISSUE TITLE
Improve the Safety of "Extract Local Variable" refactorings by identifying statements that may change the value of the extracted expressions

### ISSUE THREAD

**Issue by chixiaye** [eclipse-jdt/eclipse.jdt.ui#432]
## Description
"Extract Local Variable" refactoring in Eclipse provides an option to replace all occurrences of the selected expression with references to the newly extracted local variable. However, it may result in semantic errors when the selected expression (to be extracted as a variable) depends on variables that could be changed by statements between the initialization of the variable and the accesses (references) to the variables.

We take the following sample code to illustrate the bug:  
```java
1   /* CS1: Original Code Snippet */
2   String[] Lines;
3   int i;
4   private void inc() {
5   	i++;
6   }
7   ...
8   log.warn(Lines[i]);
9   ...
10  log.warn(Lines[i]);
11  ...
12  inc();
13  ...
14  log.warn(Lines[i]);
``` 

If we select expression `Lines[i]` (line `10` in `CS1`), conduct refactoring "extract local variable", and name the new variable as `x` (enabling "replace all occurrences"), we will get the following code snippet:
```java
1   /* CS2: Code Snippet after incorrect refactoring */
2   String[] Lines;
3   int i;
4   private void inc() {
5   	i++;
6   }
7   ...
8   String x= Lines[i];
9   log.warn(x);
10  ...
11  log.warn(x);
12  ...
13  inc();
14  ...
15  log.warn(x);
```  

The refactoring is incorrect because the original values of `Lines[i]` at Line 8 and Line 10 in `CS1` are different from `Lines[i]` at Line 14. Consequently, replacing `Lines[i]` at Line 15 in `CS2` with `x` is incorrect. 

## Solution
The solution is composed of two parts. The first part is to calculate the path between the initialization of generated variable and the to-be-inserted references to the variable. The second part is the validation of the changed value.

To calculate the path, we parse the current BodyDeclaration as an AST, and do a root-first traversal between expressions that are to be verified. We will record these visited nodes without duplication. Notably, we take the method call (but exclude the following method calls) and its implementation into consideration. Besides, control statements (loop-statement, condition-statement, etc.) are also considered for accuracy. However, some dead code and complex control statements(break, continue, goto, etc.) are not considered due to potentially large cost.

To validate of changed value, we will traverse all nodes of the path we have gotten to make sure neither of them do update the variables that the selected expression depends on. It should be pointed out that we currently only consider source code, and subsequent commits will provide support for Java Class Library.

In the end, our desired refactoring result is as follows:
```java
1   /* CS3: Code Snippet after correct refactoring */
2   String[] Lines;
3   int i;
4   private void inc() {
5   	i++;
6   }
7   ...
8   String x= Lines[i];
9   log.warn(x);
10  ...
11  log.warn(x);
12  ...
13  inc();
14  ...
15  log.warn(Lines[i]);
```  

**The above is our proposed solution, if you have any comments or suggestions, please let us know.**

**Comment by jjohnstn** [comment]
Seems reasonable.  You could simplify the cases where you are protecting a local public/protected field and assume a public/protected method call could be overridden in which case, you assume the method call is dangerous (as opposed to spending time analyzing the method and subsequent method calls).  In your example, if i was declared public and inc() was declared public you would stop reusing x at that point.

**Comment by liuhuigmail** [comment]
@jjohnstn  please kindly review the submitted pull request at https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/439
Thanks.

**Comment by jjohnstn** [comment]
@liuhuigmail Will do today.

**Comment by jjohnstn** [comment]
Closing as done with #439
