### ISSUE TITLE
Limited syntax coloring in JavaSourceHover

### ISSUE THREAD

**Issue by RedeemerSK** [eclipse-jdt/eclipse.jdt.ui#437]
Java Source hover has only limited syntax coloring from only basic java source content parsing.
Advanced semantic coloring is not applied.

Example:
![image](https://user-images.githubusercontent.com/36334098/221380002-aa660cc1-80d4-4385-8061-c2ec5df44c3b.png)

Expected:
Java source in hover viewer should be colored the same way as if it was opened in source code editor.

**Comment by RedeemerSK** [comment]
I would like to contribute a change of `org.eclipse.jdt.ui` module that fixes this issue, see https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/438

**Comment by iloveeclipse** [comment]
Looks nice, but why do we need a preference at all? Is the new presentation too slow or what's the point **not** to use it?

**Comment by RedeemerSK** [comment]
> Looks nice, but why do we need a preference at all? Is the new presentation too slow or what's the point not to use it?

I don't find it slower to the point where it may disturb the user. But hovering over elements origins of which are and not the same as that of active editor (not the "fast" AST path, more info in linked PR's comments) and are also large sometimes adds some short slightly noticeable delay.

I was not sure what's the process of introducing UI change like this plus as a 1st time contributor, I thought I rather prepare it with the preference to allow going back to original way.
Removing it, if that's preferred, is very simple.
