### ISSUE TITLE
Typing text will remove next variable

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#445]
When you have for example
if (object.var)
and you want to type newobject. before the object, it will remove "object" text.

**Comment by JanecekPetr** [comment]
This is a feature that you can turn off, see Proferences -> Java -> Editor -> Content Assist, select "Completion inserts" instead of "Completion overwrites". Does that fix your problem?

**Comment by andreasdc** [comment]
yes
