### ISSUE TITLE
NPE in ChainCompletionProposalComputer using CompletionProposalCollector 

### ISSUE THREAD

**Issue by flatombe** [eclipse-jdt/eclipse.jdt.ui#45]
In `org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.initializeRequiredContext(ContentAssistInvocationContext)`, when the `ICompilationUnit` returned by our `JavaContentAssistInvocationContext` is `null`, then the following NPE happens:
```
java.lang.NullPointerException
at org.eclipse.jdt.ui.text.java.CompletionProposalCollector.<init>(CompletionProposalCollector.java:150)
at org.eclipse.jdt.internal.ui.text.java.ChainCompletionProposalComputer.initializeRequiredContext(ChainCompletionProposalComputer.java:86)
```

This seems similar to the old https://bugs.eclipse.org/bugs/show_bug.cgi?id=95862 which was fixed with an [early null check](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/567c1546ee76fbbd4a50ee6b0de8e046a19356fe/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaCompletionProposalComputer.java#L224-L227).

**Comment by jjohnstn** [comment]
Verified for 4.24 M3 using I20220517 build and examining source.
