### ISSUE TITLE
Enhance add NLS quick-fix to work for Text blocks

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-jdt/eclipse.jdt.ui#450]
The following code:

```
	public void foo() {
		String x = """
				a line is here
				and here too
				""";
	}

```
will show a warning after https://github.com/eclipse-jdt/eclipse.jdt.core/issues/762 is merged.

Add support to allow a user to add an NON-NLS marker via quick-fix.

**Comment by jarthana** [comment]
Is it possible to add a testcase verify the JDT Core part alone? Would be good to have one if there's a way.

**Comment by jjohnstn** [comment]
I could add a test to TestTextBlock.java.  I'll do a separate PR for that.
