### ISSUE TITLE
Code Mining + Print Margin discussion

### ISSUE THREAD

**Issue by JanecekPetr** [eclipse-jdt/eclipse.jdt.ui#459]
This is obviously a minor appearance thing, and I do not have a strong opinion on it, but I'd like to open a discussion to see whether there are any good options.

I'm using code mining (for param names and var types) together with a print margin (to visually see when the code is becoming longer than the team agreed to, but it's a soft limit). Obviously, that suddenly does not make any sense because code mining makes my lines a lot longer, so it completely invalidates the print margin. E.g. The code below does _not_ contain a line which is too long:
![image](https://user-images.githubusercontent.com/1746404/223376735-0c53a82e-d8da-4f07-af5b-e57cbe007477.png)

Naively it could be possible to have a separate margin for each line and move it based on code mining. I assume this is technically unfeasible (and probably ugly and distracting)? Is there a good solution?

What I can do and have been doing so far is to properly set up a (auto)formatter, and/or Checkstyle which can warn when the line is too long. This obviously works. Still, it's not ideal that the two features directly counter each other.

**Comment by jjohnstn** [comment]
I agree it is minor and you already have a solution to warn you for lines that are indeed too long.  A separate margin would look very ugly and distracting as you mentioned.  One possibility might be to have a dynamic option to see the line in its non-code-mining form or to show the line with modified print margin (e.g. a hover on the print margin line or a context menu option when on the line).

**Comment by jjohnstn** [comment]
Great.  I'm ok with closing this but if you like we can open a new enhancement issue regarding the JDT setting up a default shortcut.

**Comment by JanecekPetr** [comment]
> we can open a new enhancement issue regarding the JDT setting up a default shortcut

Nah, that's not worth it, I'm probably one of ten people in the world annoyed by this, and that's only until I can convince my team to switch to an autoformatter.

Thanks!
