### ISSUE TITLE
Externalize Strings sometimes generating unusable Messages.java class

### ISSUE THREAD

**Issue by jprisco60** [eclipse-jdt/eclipse.jdt.ui#466]
The following bug suggested using
   private static final String BUNDLE_NAME= <MessagesClassName>.class.getPackageName() + "<properties-file-name>";

when generating the Messages class for Externalize Strings. <https://bugs.eclipse.org/bugs/show_bug.cgi?id=574801>

Apparently this creates a dependency on Java 9 - if this was not the intent then I suspect this a bug.

**Comment by jjohnstn** [comment]
Hi @jprisco60 Thanks for noting.  Yes, the compliance level should be checked.
