### ISSUE TITLE
Extend the replace system properties cleanup to include Long and Integer support

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-jdt/eclipse.jdt.ui#47]
For the Replace system property with constants cleanup found on the Java Feature cleanups page, change the existing sub-option "Boolean type property" to be "Boxed type property" and include support for Long and Integer. For example:

Integer.parseInt(System.getProperty("Option")); //$NON-NLS-1$

changes to:

Integer.getInteger("Option"); //$NON-NLS-1$

**Comment by jjohnstn** [comment]
For the Replace system property with constants cleanup found on the Java Feature cleanups page, change the existing sub-option "Boolean type property" to be "Boxed type property" and include support for Long and Integer.  For example:

Integer.parseInt(System.getProperty("Option")); //$NON-NLS-1$

changes to:

Integer.getInteger("Option"); //$NON-NLS-1$

**Comment by carstenartur** [comment]
Should this one be closed?

**Comment by jjohnstn** [comment]
Yes, closed
