### ISSUE TITLE
Enable LeakTestSite in org.eclipse.jdt.ui.tests pom.xml again

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-jdt/eclipse.jdt.ui#5]
This change comments out LeakTestSite in org.eclipse.jdt.ui.tests pom.xml , as these test are failing in the jenkins github job.

_Originally posted by @ktatavarthi in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1#issuecomment-1093684675_

**Comment by ktatavarthi** [comment]
This a duplicate of #2
