### ISSUE TITLE
Create new Java Project Wizard too small

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#517]
With long JDK names (like "openjdk.jdk17.win32.x86_64_1.17.0.006-010") the Wizard becomes to small by default.
![image](https://user-images.githubusercontent.com/51790620/230092581-9bb64326-c475-4999-9526-714a6c0e76d2.png)
![image](https://user-images.githubusercontent.com/51790620/230094351-53ec346b-30c6-4ebf-bae4-1ddaf8eecc8e.png)
![image](https://user-images.githubusercontent.com/51790620/230093058-3040bf05-753c-4727-a8ce-3c5c43c73b4b.png)

in this case a width of 855px would be enough to not scroll:
![image](https://user-images.githubusercontent.com/51790620/230095208-36f6547c-0209-4317-ad0b-0e3d2506a686.png)

**Comment by jjohnstn** [comment]
![image](https://user-images.githubusercontent.com/1216877/232140188-29ff28d8-9365-4218-a8b0-cac95942d0d9.png)

I have reformatted the layout in a PR so that the JRE combos are considered 2 of 3 columns and the message with the long JRE name is also considered 2 of 3 columns.
