### ISSUE TITLE
UI issue : Unable to scroll down to "Application" section in the "New project" window

### ISSUE THREAD

**Issue by sharma-mallika** [eclipse-jdt/eclipse.jdt.ui#539]
Hello Team, 

In Eclipse IDE for Java development, i goto >> File >> New >> JavaCard Project

the window appearing is not showing the complete "Application" section and there is no way to scroll to it. 

Is there any possible way to fix it?
<img width="584" alt="Capture" src="https://user-images.githubusercontent.com/112951134/233107007-867f1ac6-eb4e-4d43-8f93-a18a93e5269a.PNG">

**Comment by jjohnstn** [comment]
Hi @sharma-mallika Have you tried expanding/stretching the window?  The Java Card project wizard is not part of JDT UI.  If re-sizing doesn't help, you'll need to open an issue against Oracle which develops the Eclipse Java Card plug-in.  Closing this issue.
