### ISSUE TITLE
ClassNotFoundException while using the rerun junit5 functionality

### ISSUE THREAD

**Issue by vik-chand** [eclipse-jdt/eclipse.jdt.ui#57]
While testing https://www.eclipse.org/eclipse/news/4.24/jdt.php#junit5-rerun-failures-first
```

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class t {

	@Test
	void atest() {
		//fail("Not yet implemented");
	}
	@Test
	void test() {
		fail("Not yet implemented");
	}

}
```

While running re-run I get
```

May 17, 2022 10:33:39 PM org.junit.jupiter.engine.config.InstantiatingConfigurationParameterConverter logFailureMessage
WARNING: Failed to load default method orderer class 'org.eclipse.jdt.internal.junit5.runner.FailuresFirstMethodOrderer' set via the 'junit.jupiter.testmethod.order.default' configuration parameter. Falling back to default behavior.
java.lang.ClassNotFoundException: org.eclipse.jdt.internal.junit5.runner.FailuresFirstMethodOrderer
	at org.eclipse.pde.internal.junit.runtime.MultiBundleClassLoader.findClass(MultiBundleClassLoader.java:40)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.junit.platform.commons.util.ReflectionUtils.lambda$tryToLoadClass$9(ReflectionUtils.java:829)
	at org.junit.platform.commons.function.Try.lambda$call$0(Try.java:57)
	at org.junit.platform.commons.function.Try.of(Try.java:93)
```

**Comment by jjohnstn** [comment]
I can test this on I20220517 by creating a Plug-in project that depends on org.junit.jupiter.api, and org.eclipse.jdt.junit5.runtime.  Works fine.  Is there some requires needed in JDT so it works in your scenario?

**Comment by jjohnstn** [comment]
After thinking about it, the jar containing the FailuresFirstMethodOrder class (currently  org.eclipse.jdt.junit5.runtime) needs to be added on the classpath by default instead of manually, but I am not sure how to do this.  I tried adding it in JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration() where we add jupiter jars to the classpath, but it wasn't successful.  The feature will need to be marked incomplete and removed from the N&N until I can sort this out.

**Comment by jjohnstn** [comment]
I tried running the same test as JUnit test and it works fine so I'll leave the feature in and keep this as an open issue.  The workaround is to add org.eclipse.jdt.junit5.runtime as a test plug-in dependency.

**Comment by jjohnstn** [comment]
@vik-chand Can you review the PR mentioned above?

**Comment by jjohnstn** [comment]
The PDE changes have fixed this problem.
