### ISSUE TITLE
Call Hierarchy for Record components does not work

### ISSUE THREAD

**Issue by JanecekPetr** [eclipse-jdt/eclipse.jdt.ui#571]
Using eclipse 2023-03 and Java 17 on an M1 Pro Mac with the provided JustJ 17:

1. The Call Hierarchy only works for Record components _when the record definition is in the same file as the caller_. Otherwise it does not show up at all.

    Different files:
![image](https://user-images.githubusercontent.com/1746404/229822892-b53aa604-9cb0-4ce0-ba24-d4223b832f46.png)

    Same file (it does not matter if the record is nested or a sibling, it shows up every time):
![image](https://user-images.githubusercontent.com/1746404/229823537-b87de155-a46b-4d99-b598-e69edbc5253a.png)

2. (Edit: Separated into an another ticket.) ~~Currently the Outline view does not show the record component accessor methods. I tried unticking the Synthetic members, does not make a difference. This is annoying because normally I have fields filtered out and only see methods which is now not possible for records.~~
    ~~Also I thought using Call Hierarchy on the methods might help, but they're not available at all. Maybe this is somehow related? I imagine the component accessors are special methods which circumvent the normal eclipse way of tracking things?~~

If these two things are completely unrelated, I'm happy to split this ticket into two.

**Comment by trancexpress** [comment]
> 2\. the private field is final and has matching public synthetic member

I'm not sure how to do this. And which case it should cover?
