### ISSUE TITLE
Organize the order of actions when 'save actions' are enabled

### ISSUE THREAD

**Issue by freedom1b2830** [eclipse-jdt/eclipse.jdt.ui#573]
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

The problem is that when I save, the variable declaration becomes var, the import becomes unused

actions now:

1) Remove unused imports
2) var
``an unused import appears``

what I want

1) var
2) Remove unused imports
``no unused imports``

https://user-images.githubusercontent.com/102818470/236677073-995d0bf2-a46a-44ad-a810-36d9f3ef3d12.mp4

**Comment by jjohnstn** [comment]
Looking at the code, it is actually an error in the var cleanup.  The var cleanup is not registering removed types.  When it does this, the import is removed by the var cleanup.  I will post a patch shortly.
