### ISSUE TITLE
Proposal: Make Static Refactoring

### ISSUE THREAD

**Issue by Michael5601** [eclipse-jdt/eclipse.jdt.ui#590]
# Proposal: Make Static Refactoring

## Background
The Eclipse IDE provides plenty of refactorings for different use cases. We want to implement a `MakeStatic` refactoring like the one that IntelliJ provides. The following description should give you a little insight to our planning and the functions that we want to include in the refactoring.

## Goal
The `MakeStatic` refactoring can be applied to instance methods and fields to make them static. It updates accesses and calls of these methods and fields to retain syntactic correctness and the execution semantics of all code currently accessible by the JDT tooling.

## Description
`MakeStatic` refactoring can be used in different ways. At first we will implement it for methods only. Later, an implementation for fields is also possible.
By performing the refactoring, a `RefactoringWizard` will open, giving the user a preview of the changes to the source code. The user can confirm the changes or cancel the refactoring.

A static keyword will be added to the selected function when the refactoring is performed. Furthermore, the references to this method will be adjusted so that every invocation is working properly after the refactoring.

#### Before refactoring
```java
class Foo {
  public void bar() {
      int i = 0;
  }

  public void Reference() {
      Foo foo = new Foo();
      foo.bar();
  }
}
```

#### After refactoring `bar`
```java
class Foo {
   public static void bar() {
      int i = 0;
  }

   public void Reference() {
      Foo foo = new Foo();
      Foo.bar();
  }
}
```

### Special Application Conditions
There are several special cases in which the refactoring must function properly. The initial functionality we plan to include should analyze those cases and give the user information why the refactoring cannot be executed.

The initial implementation should only work under the following conditions:

* The refactored method does not access instance variable/method.
* The refactored method is not a constructor.
* The refactored method does not override a method of the parent type and also does not have a child type where the method is overridden.
* The type in which the refactored method is declared must not be a local type, an anonymous type or an annotation.
* The refactoring can be executed if a MethodInvocation is selected but not if a SuperMethodInvocation is selected.

This is the minimum we plan to bring into this refactoring for now. In the following we provide a list with additional functions this refactoring should be able to do in the future.

### Precondition checks
In the following we discuss which of the above conditions will be checked as **initial preconditions** to make sure that the refactoring can be started and the workspace is in a stable state.

#### Initial conditions
1. Check for constructor:
The refactoring should not be able to change a constructor method into a static method.

2. Check for local type, anonymous type or annotation:
The parent type of the refactored method must not be local because it is not possible to access them outside of the method they are declared in. So a static method is not possible in local types. Anonymous types do not have a class name to associate them with so they also do not allow static methods. Annotations can have methods but should be used for metadata and not behavior, so static methods will not be allowed. 

3. Check for SuperMethodInvocation:
The refactoring should not change the method of the parent type to static if a SuperMethodInvocation in the child type is selected. It would not be possible to access the method of the parent type with the "super" keyword anymore.

#### Final conditions
After the **initial conditions** are met the refactoring can be started. It is important to add **final checks** that have to be met in runtime. The user gets a error message with the specific status if a condition check fails:

1. Check for access to instance variables and methods:
The refactoring should not change a method to static if it contains instance variable access or instance method access. A static method can only access static variables or methods without having an instance of a class.

2. Check if method overrides a method of parent type:
It should not be possible to refactor a method that overrides a method of the parent type. This is because a static method cannot override a method of the parent type. It is important that the AST will be analyzed for overrides before executing the refactoring.

3. Check if method is overridden in hierarchy:
The refactoring can not be executed if the refactored method is overridden in a child type because a static method cannot be overridden.

### Extensions
When the initial scope of the refactoring is implemented, extensions can be added.
Most extensions add functionality for the various edge cases covered in the conditions.

1. Instance variables and instance method access in method body:

    Should a type contain instance variables or methods that are used in the refactored 	method, the `MakeStatic` refactoring will have the same behavior but additionally an instance of the type will be added to the parameter list of the method. Every access of an instance variable or instance method inside the refactored method will be modified with the new parameter.

 #### Before refactoring
```java
class Foo {
       int i = 0;

       public void bar() {
            this.i = 0;
       }

       public void instanceReference() {
             this.bar();
        }

        public static void staticReference() {
              Foo foo = new Foo();
              foo.bar();
         }
}
```

 #### After refactoring `bar`
```java
class Foo {

         int i = 0;

          public static void bar(Foo foo) {
               foo.i = 0;
          }

         public void instanceReference() {
               Foo.bar(this);
         }

         public static void staticReference() {
               Foo foo = new Foo();
               Foo.bar(foo);
          }
}
```

   Additionally some final conditions need to be checked to make sure that the refactoring works properly:

 - Check for duplicate method signature:
It is possible that a method with the same signature as the refactored method already exists. In this case the refactoring will be canceled and the user will receive an error message.

 - Check for duplicate parameter name:
If the new parameter that is introduced to the refactored method has the same name as an already existing parameter the refactoring will be canceled and the user will receive an error message.

2. Refactoring a method that overrides a method of the parent type:

    This extension should make it possible to refactor a method that overrides a method of the parent type. After the refactoring a potential  `Override` annotation is deleted and the “super”-keyword will be exchanged with a new parameter containing an instance of the subclass. This is only possible when there is no further override in the lower hierarchy. If there is another override the same error will be shown as in the initial implementation. This means that only the lowest method in the hierarchy can be refactored. Even though no compiler error will be thrown after refactoring, it is necessary to include a warning when refactoring an overridding method in the subtype. This is because the program semantics can be changed very quickly if the hierarchy will be changed.

 #### Before refactoring
 ```java
public class SuperClass {

        public String toRefactor(String bar) {
              String i = bar;
              return i;
        }
}
```
```java
public class SubClass extends SuperClass {

        @Override
        public String toRefactor(String bar) {
             String i = super.toRefactor(bar);
             return i;
        }

        public static void staticMethod() {
            SubClass instance = new SubClass();
            String j = instance.toRefactor("bar");
        }
}
```

 #### After refactoring `toRefactor`

 ```java
public class SuperClass {

        public String toRefactor(String bar) {
            String i = bar;
            return i;
        }
}
```
```java
public class SubClass extends SuperClass {

       public static String toRefactor(String bar, SubClass subclass) {
           String i = subclass.toRefactor(bar);
           return i;
       }

       public static void staticMethod() {
           SubClass instance = new SubClass();
           String j = SubClass.toRefactor("bar", instance);
       }
}
```

## Feedback
We look forward to your feedback on the idea for adding such a `MakeStatic` refactoring. We particularly appreciate your input on:
1. The overall idea of having such a refactoring
2. Specific pointers to preconditions or special cases that may need to be consider before or while applying the refactoring.
3. Ideas for further extensions of the refactoring.

**Comment by jukzi** [comment]
I am curious: what is the benefit of mass-converting to static? Is there any measurable runtime benfit? Doesn't the JVM erase unneeded parameters?

**Comment by Michael5601** [comment]
The use case of the refactoring is to ease the refactoring of methods that were initially defined for a non-static context to be used in a static context.

Initial:
```java
public double calculateAverage(double[] numbers) {
		if (numbers == null || numbers.length == 0) {
			return 0.0;
		}

		double sum = 0.0;
		for (double number : numbers) {
			sum += number;
		}

		return sum / numbers.length;
	}
```
After Refactoring:
```java
public static double calculateAverage(double[] numbers) {
		if (numbers == null || numbers.length == 0) {
			return 0.0;
		}

		double sum = 0.0;
		for (double number : numbers) {
			sum += number;
		}

		return sum / numbers.length;
	}
```
Calls:
```java
public void caller() {
		double[] arr = { 0.5, 1.4, 2.5, 3.1 };
		Foo foo= new Foo();

                //instance method call
		foo.calculateAverage(arr);
	}
```
```java
public void caller() {
		double[] arr = { 0.5, 1.4, 2.5, 3.1 };
                Foo foo = new Foo();

                //static method call with instance
		foo.calculateAverage(arr);
                //static method call
		calculateAverage(arr);
	}
```

The JVM does not eliminate unused parameters. Particularly, it is rather difficult to eliminate references to <code>this</code> as non-static, non-final method references are usually resolved via the vtable of the object's class (https://wiki.openjdk.org/display/HotSpot/VirtualCalls).

There are also performance implications for very hot utility methods due to the multiple hops needed to resolve virtual calls. However, our central motivation is to ease the refactoring of non-static methods to be called in static contexts, where <code>this</code> is not used.
