### ISSUE TITLE
Refactor renames random java elements

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#592]
Very nasty regression (random results - but reproducible):
ALT+SHIFT+R on a method sometimes also selects and refactors code that has nothing todo with it.
Example:
![image](https://user-images.githubusercontent.com/51790620/187499163-c1b26aec-84db-43b7-8ad2-055efdb05d76.png)

I wanted to refactor the name of "waitFor" but in the same turn it refactored "lockAcquiringRunnable"
![image](https://user-images.githubusercontent.com/51790620/187499752-d346f2da-667e-4d58-b31f-554a41c57cf9.png)
When i slightly change the code then either problem is gone or other elements are refactored:
![image](https://user-images.githubusercontent.com/51790620/187501093-31fdda92-39f6-46cf-bf64-68b7b653263b.png)

You can download the the example from https://github.com/jukzi/eclipse.platform/commits/refactorBug
```
git clone git@github.com:jukzi/eclipse.platform.git
git checkout refactorBug

```
Then import the `project eclipse.platform\runtime\tests\org.eclipse.core.tests.runtime` to your workspace.
It will have many compilation errors if you do not have the dependencies but that does not affect the bug.

Sorry, that i could not find a smaller example .. as soon as i reduce it i can't reproduce.

Feels like there is a comparison of a colliding hash instead of checking for equals.

**Comment by iloveeclipse** [comment]
> Can this go into RC1 or RC2?

The patch seem simple. Is there anyone else who knows the code and can review it?
Is a regression test easily doable?

**Comment by jjohnstn** [comment]
@iloveeclipse I'm hoping @jukzi can review it as he located the source of the issue.  A test is difficult because it is a fluke that we are able to find a method name range in another file that is also a name position in the current file.  I could give it a try if @jukzi hasn't already.

**Comment by jukzi** [comment]
i'll test tomorrow, source looks good to me.

**Comment by jjohnstn** [comment]
I was able to make the following test.  If you rename the waitFor() call in B without the patch, it will try and change the loop variable name as well.  With the patch, it works.  Didn't quite know how to fit this into existing rename tests which only have one file supported.

[testrename.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/11559426/testrename.zip)
