### ISSUE TITLE
Automated Name Recommendation For The Extract Local Variable Refactoring

### ISSUE THREAD

**Issue by Michaelll123** [eclipse-jdt/eclipse.jdt.ui#601]
### Automated Name Recommendation For The Extract Local Variable Refactoring
---
**Description**
---
"Extract Variable" refactoring is a useful feature of JDT. However, the names recommended for the extracted variables sometimes are substantially different from what developers manually coin. Here we report a case as follows:
This example is a real-world case of extracting local variable refactoring in GeoServer, an open-source software server written in Java that allows users to share and edit geospatial data. (https://github.com/geoserver/geoserver/commit/c54d9ccbebd5d55ff2bcb2ca4db5e7167c1e2f2a#diff-40dd1af56b59d542f9c41036b47c0db77b2b4a5bc8ece7a2f4a78cc196867181, line 61 in src/community/oseo/oseo-stac/src/main/java/org/geoserver/ogcapi/stac/TemplatedItemsConverter.java )
```java
/* CS1: Real Case of Extract Local Variable Refactoring */
protected void writeInternal(
            AbstractItemsResponse itemsResponse, HttpOutputMessage httpOutputMessage)
            throws IOException {
-		RootBuilder builder = templates.getItemTemplate();
        try (STACGeoJSONWriter writer =
                new STACGeoJSONWriter(
                        new JsonFactory()
                                .createGenerator(httpOutputMessage.getBody(), JsonEncoding.UTF8))) {
            writer.startTemplateOutput(null);
            try (FeatureIterator features = itemsResponse.getItems().features()) {
                while (features.hasNext()) {
-					builder.evaluate(writer, new TemplateBuilderContext(features.next()));
+       			// lookup the builder, might be specific to the parent collection
+        			Feature feature = features.next();
+        			String collectionId =
+                		(String) feature.getProperty("parentIdentifier").getValue();
+        			RootBuilder builder = templates.getItemTemplate(collectionId);
+        			builder.evaluate(writer, new TemplateBuilderContext(feature));
                }
            }
            //Do other things
      	    // ...
        } catch (Exception e) {
            throw new ServiceException(e);
        }
    }
```
The actual name developer assigned to the extracted expression, i.e., `features.next()` (line 13 in CS1) is "feature". However, if we select the expression features.next() and conduct refactoring "extract local variable" in Eclipse, we will get the following code snippet:
```java
/* CS2: Code Snippet After Refactoring in Eclipse*/
protected void writeInternal(
            AbstractItemsResponse itemsResponse, HttpOutputMessage httpOutputMessage)
            throws IOException {
		RootBuilder builder = templates.getItemTemplate();
        try (STACGeoJSONWriter writer =
                new STACGeoJSONWriter(
                        new JsonFactory()
                                .createGenerator(httpOutputMessage.getBody(), JsonEncoding.UTF8))) {
            writer.startTemplateOutput(null);
            try (FeatureIterator features = itemsResponse.getItems().features()) {
                while (features.hasNext()) {
					Feature next = features.next();
					builder.evaluate(writer, new TemplateBuilderContext(feature));
                }
            }
            //Do other things
      	    // ...
        } catch (Exception e) {
            throw new ServiceException(e);
        }
    }
```
The name recommended for the extracted variable is "next" which is substantially different from what the developers finally selected. 

**Solution**
---
To this end, we proposed a new rule for recommending names for extracted variables:
`X = Xs.next()`, where "Xs" represents the receiver object in plural format, and "X" represents the singular format of the receiver object. Note that there are multiple plural forms, e.g., *f -> *ves, and here we just take "X" and "Xs" for example. 

The precondition for applying this rule is specified as follows:
1. The expression to be extracted is an instance of MethodInvocation.
2. The selected expression contains a receiver that is a SimpleName.
3. The receiver object is in plural format, indicating that it is a collection object.
4. The invoked method is named "next", indicating that the expression is to retrieve a single element from the collection.

To validate the effectiveness of the proposed rule, we identified real-world  extracted variables refactorings by mining commit histories of projects on GitHub.  
Evaluation results suggest that Xs.next() is often extracted as local variables, and developers rarely (2 out of 26 cases) name the variables as "next" (as Eclipse recommends). 
In contrast, the manually selected variable names are identical to the ones recommended by the new rule in 15 out of 26 cases, much higher than the success rate of Eclipse's default recommendation. 

**We will submit the pull request (implementing the new rule) if that is fine.**

**Comment by liuhuigmail** [comment]
@jjohnstn  Following our contribution in safer extract local variable refactoring to Eclipse, now we begin to improve the recommendation of variables names during the refactoring.  

Please kindly have a look at the issue and the solution. Thanks.
