### ISSUE TITLE
UI Freeze with quick assist

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-jdt/eclipse.jdt.ui#610]
The UI froze for 16 seconds while waiting for the content of the _quick assist_ (CTRL + 1).

Sadly I didn't create a Sample with VisualVM at the moment so all I have are the reports created by the _UI responsiveness monitoring_ (Attached: [ui_freeze_16s.log](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/11649785/ui_freeze_16s.log)).

IMHO the relevant methods in the stack trace are:

```
...
	at org.eclipse.m2e.jdt.ui.internal.AddDependencyQuickFixProcessor.handleImportNotFound(AddDependencyQuickFixProcessor.java:95)
	at org.eclipse.m2e.jdt.ui.internal.AddDependencyQuickFixProcessor.getCorrections(AddDependencyQuickFixProcessor.java:79)
...
```

And I assume what's happening is that these methods end up making some expensive IO calls (I've seen them opening a file and also making an HTTP call via `okhttp3`) in the main UI Thread.

Since I don't know my way around the code yet, I won't be able to fix this issue myself. So please let me know if it can be fixed at all by someone with more experience (someone that can look into it without the samples) or if I should close it. 

Any hints about how to reproduce the issue are also appreciated :)

**Comment by jukzi** [comment]
"org.eclipse.m2e" is not part of jdt
