### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by andreasdc** [eclipse-jdt/eclipse.jdt.ui#678]
Cannot complete the install because of a conflicting dependency.
  Software being installed: Tip of the Day UI Feature 0.4.0.v20230429-1617 (org.eclipse.tips.feature.feature.group 0.4.0.v20230429-1617)
  Software currently installed: Tip of the Day UI Feature Developer Resources 0.4.0.v20230317-0802 (org.eclipse.tips.feature.source.feature.group 0.4.0.v20230317-0802)
  Only one of the following can be installed at once: 
    IDE Enablement for Tip of the Day 0.3.0.v20230315-0554 (org.eclipse.tips.ide 0.3.0.v20230315-0554)
    IDE Enablement for Tip of the Day 0.3.0.v20230429-1617 (org.eclipse.tips.ide 0.3.0.v20230429-1617)
  Cannot satisfy dependency:
    From: Tip of the Day UI Feature 0.4.0.v20230317-0802 (org.eclipse.tips.feature.feature.group 0.4.0.v20230317-0802)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tips.ide [0.3.0.v20230315-0554,0.3.0.v20230315-0554]
  Cannot satisfy dependency:
    From: Tip of the Day UI Feature 0.4.0.v20230429-1617 (org.eclipse.tips.feature.feature.group 0.4.0.v20230429-1617)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tips.ide [0.3.0.v20230429-1617,0.3.0.v20230429-1617]
  Cannot satisfy dependency:
    From: Tip of the Day UI Feature Developer Resources 0.4.0.v20230317-0802 (org.eclipse.tips.feature.source.feature.group 0.4.0.v20230317-0802)
    To: org.eclipse.equinox.p2.iu; org.eclipse.tips.feature.feature.group [0.4.0.v20230317-0802,0.4.0.v20230317-0802]

**Comment by andreasdc** [comment]
nice

**Comment by jjohnstn** [comment]
Closing this as issue has been moved over to platform.
