### ISSUE TITLE
Recommend variable name for Extracted Local Variable Refactoring when the extracted expression is a method invocation

### ISSUE THREAD

**Issue by Michaelll123** [eclipse-jdt/eclipse.jdt.ui#684]
### Recommend variable name for **Extracted Local Variable** Refactoring when the extracted expression is a method invocation
---
**Description**
---
In this case, Eclipse first retrieves the simple name of the invoked method, e.g., "getValue" for the extracted expression "descriptor.getValue(CLASSNAME)", and replaces specific verbs (i.e., "get", "is", and "to") if they appear in the first place of the simple method name. Consequently, in the above example, "value" is recommended as the new name for the extracted variable.

However, we observe some instances such simple rules may not work. Consequently, here we propose a novel approach to improve it.

Except for "get", "is", and "to", we further collect a set of frequently used verbs that should be removed from variable names: {"create", "load", "find",  "build", "generate", "prepare", "parse", "current", "read", "resolve", "retrieve", "make", "add", "extract"}
```java
/* CS1: Real Case of Extract Local Variable Refactoring From the jmeter of Apache. (1708f277f112e608cd48e5c9eabd8f10bb44778b/apache_jmeter/src/protocol/tcp/org/apache/jmeter/protocol/tcp/config/gui/TCPConfigGui.java) */
private void init() {
        setLayout(new BorderLayout(0, 5));
        if (displayName) {
            setBorder(makeBorder());
            add(makeTitlePanel(), BorderLayout.NORTH);
        }
		
        VerticalPanel mainPanel = new VerticalPanel();
-       mainPanel.add(createServerPanel());
+       classname = new JLabeledTextField(JMeterUtils.getResString("tcp_classname"));
+       mainPanel.add(classname);
+       final JPanel serverPanel = createServerPanel();
+       serverPanel.add(createPortPanel(), BorderLayout.EAST);
+       mainPanel.add(serverPanel);
        mainPanel.add(createClosePortPanel());
-       mainPanel.add(createPortPanel());
        mainPanel.add(createTimeoutPanel());
        mainPanel.add(createNoDelayPanel());
        mainPanel.add(createRequestPanel());
```
For this example, when the expression "createServerPanel()" is extracted, Eclipse recommends "createServerPanel" as the new name for the variable. However, "serverPanel" should be much better. In general, we believe that all verbs in the base form should be removed from the recommended variable names if they are the first tokens of the names. Or at least, remove the verbs in our list.

**Genetic Solution**
---
The precondition for applying these three improved rules is specified as follows:

	- The extracted expression is a method invocation
	- The simple name of the invoked method starts with verbs in their base form (in our predefined collection).
	- We remove the vers from the method name, and the resulting string is recommended as the variable name.

These additional rules can improve the performance of Eclipse substantially (precision from 28.8% to 34.0%, and recall from 21.3% to 25.0%).

The pull request that implements the new rule has also been submitted.

**Comment by liuhuigmail** [comment]
@jjohnstn   please kindly have a look. Thanks.
