### ISSUE TITLE
Support for either org.hamcrest.core 1.x or org.hamcrest/org.hamcrest.core 2.x

### ISSUE THREAD

**Issue by merks** [eclipse-jdt/eclipse.jdt.ui#705]
This constant was changed to accommodate org.hamcrest.core 2.x

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/7e18055320a51cb8bd946156952b610824951ffd/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java#L307-L308

but now it excludes org.hamcrest.core 1.x from the range.  But org.hamcrest.core alone 1.x is sufficient to satisfy org.junit's bundle require.

On the other hand, org.hamcrest.core 2.x is just a wrapper and has a bundle require on org.hamcrest 2.x, so this constant was added because without this bundle, the org.hamcrest.core bundle 2.x is effectively useless:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/7e18055320a51cb8bd946156952b610824951ffd/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java#L310-L311

I.e., the org.hamcrest.core bundle 2.x provides nothing of significance so it doesn't actually need to be on the classpath...

We could change the lower bound of the range of HAMCREST_CORE_PLUGIN here to 1.x:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/7e18055320a51cb8bd946156952b610824951ffd/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java#L307-L308

However, if 1.x, rather than 2.x, actually resolves for HAMCREST_CORE_PLUGIN's range, then the org.hamcrest plugin 2.x is no longer needed to make org.junit happy.

But the following "new" logic diagnoses an error for any range that doesn't resolve:

https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/7e18055320a51cb8bd946156952b610824951ffd/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/internal/junit/buildpath/BuildPathSupport.java#L235-L236

So it's not clear how we can require org.hamcrest.core 1.x, **or** require org.hamcrest.core 2.x **and** org.hamcrest 2.x, without errors being logged.  And, as mentioned, the org.hamcrest.core bundle 2.x is actually useless and provides nothing that needs to be on a plain-old-java classpath.

@HannesWell 

Is the issue clear from this description?  Do you have any good ideas for how best to implement this in a minimal and correct way?

**Comment by iloveeclipse** [comment]
> without errors being logged.

Ed, I've added this to avoid "silent" fails like with the recent build. It is not written in stone that for optional bundles this error should be logged too, but **if** we fail to compute **any of mandatory** bundles we should at least log something useful.

So assuming we have an idea what is the best solution to deal with hamcrest, this error should be logged only if we would be unable to reach "satisfiable" state.

**Comment by HannesWell** [comment]
Ed, your descriptions look totally correct, but I'm not familiar with the JDT code in that area.

> > without errors being logged.
> 
> Ed, I've added this to avoid "silent" fails like with the recent build. It is not written in stone that for optional bundles this error should be logged too, but **if** we fail to compute **any of mandatory** bundles we should at least log something useful.

Sounds also reasonable. But I cannot see a way to declare a PluginDescription optional, so probably this has to be added? But hamcrest.core 2 is actually not even optional, it is actually a redirect as Ed said. So instead of adding an `optional` option it might be better to implement some kind of re-direct that requires the redirected plugin and removes the initial plugin from the set of required ones.

**Comment by merks** [comment]
@iloveeclipse 

I think this is a better way to address the issue of needing either org.hamcrest.core 1.x or org.hamcrest 2.x and providing compatibility such that either one will work.
