### ISSUE TITLE
"Open declaration/implementation" popup disappears too soon

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-jdt/eclipse.jdt.ui#72]
I think this issue might be related to Wayland (in Linux) because I've just started using the Wayland session in Gnome 42 and I've never experienced this problem before: when I Ctrl+click on a type in the editor and the popup for "Open declaration"/"Open implementation" appears, it becomes nearly impossible to select "Open implementation" (the second item) because the popup disappears (most of the time) when you move the mouse to select the menu. And this happens in Fedora, Arch and Ubuntu (latest versions, Gnome 42, all with Wayland session).

![Screenshot-20220528164903-2560x1600](https://user-images.githubusercontent.com/1202254/170830598-0890d8c5-2e7f-4f2a-a775-1447bb99845e.png)

The version of Eclipse is 2022-03 (4.23.0)

**Comment by iloveeclipse** [comment]
Please report this for SWT. JDT UI is platform independent.

**Comment by LorenzoBettini** [comment]
@iloveeclipse can I move the issue from here?

**Comment by iloveeclipse** [comment]
> @iloveeclipse can I move the issue from here?

Nope, "modern" github is not "ancient" bugzilla, it doesn't allow that simple thing.

**Comment by LorenzoBettini** [comment]
> > @iloveeclipse can I move the issue from here?
> 
> Nope, "modern" github is not "ancient" bugzilla, it doesn't allow that simple thing.

Actually, you can, but you have to have write access to both repositories.

**Comment by iloveeclipse** [comment]
> Actually, you can, but you have to have write access to both repositories.

Actually, you can't, if the bugs belong to different **organizations** which is unfortunately the case here.
