### ISSUE TITLE
jdt.ui.tests.refactoring test failures in Y-build

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#745]
jdt.ui.tests.refactoring has 4 test failures in Y-build from:

org.eclipse.jdt.ui.tests.refactoring.SurroundWithTests16

and 

org.eclipse.jdt.ui.tests.refactoring.UseSupertypeWherePossibleTests16

**Comment by noopur2507** [comment]
Y-build is created are from BETA_JAVA21 branch. 
https://download.eclipse.org/eclipse/downloads/drops4/Y20230831-1000/testResults.php

I am able to reproduce them locally.

@jjohnstn I see these tests were added by you. Can you please take a look?

**Comment by noopur2507** [comment]
Also, following test failure from jdt.ui.tests is reproducible locally:

org.eclipse.jdt.ui.tests.quickfix.CleanUpTest16#testPatternMatchingForInstanceof

**Comment by noopur2507** [comment]
Other JUnit related test failures in Y-build are passing locally for me.

**Comment by noopur2507** [comment]
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1316

This could be related.

**Comment by noopur2507** [comment]
@jjohnstn Would it be possible for you to look at these before Java 21 is released? Or else, I can disable the tests temporarily. 

Latest test results:
https://download.eclipse.org/eclipse/downloads/drops4/Y20230914-1000/testResults.php

**Comment by jjohnstn** [comment]
Taking a look using the Y-build.
