### ISSUE TITLE
Refactoring issue "Add final modifier to private fields" on lambdas

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#769]
"Add final modifier to private fields" on org.eclipse.core.internal.databinding.observable.MapEntryObservableValue leads to compile error `The blank final field key may not have been initialized`.

Automated refactoring should not lead into compile time error
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/5788f55c-1e48-4bfa-83cd-b024048c877c)

**Comment by jukzi** [comment]
nother example:  org.eclipse.jface.viewers.deferred.ConcurrentTableUpdator.uiRunnable - always lambdas involved.

**Comment by jukzi** [comment]
@jjohnstn  still happens with 	org.eclipse.jdt.ui 3.31.0.v20230926-0702	
on org.eclipse.core.internal.databinding.observable.MapEntryObservableValue
another example:
 org.eclipse.jdt.internal.ui.dialogs.TypeInfoViewer
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/703c43b4-992d-49e2-9b63-612d0334fe17)

**Comment by jjohnstn** [comment]
@jukzi The TypeInfoViewer failure had to do with a constructor using a lambda and writing to the field in question after the lambda references the field.  If you find another scenario, please open a separate issue.
