### ISSUE TITLE
Ignore spelling in Java string literals should also apply to text blocks

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-jdt/eclipse.jdt.ui#770]
Currently the following two strings have different markers when spell checking is enabled and ignore Java string literals is specified:

From #707

In the current Eclipse IDE 2023‑06 Java code editor
with spell checking enabled and option "Ignore Java string literals" ticked I get:

```
String jdbcString = "jdbc"; // spelling ignored

String jdbcBlock = """
    jdbc""";                // tagged as misspelled

```

Both strings should ignore spelling.

**Comment by illustrare-opera** [comment]
Perfect.
Much appreciated.
