### ISSUE TITLE
[21][quick fix] Provide quick fix to add default case for exhaustive enhanced switch statement

### ISSUE THREAD

**Issue by noopur2507** [eclipse-jdt/eclipse.jdt.ui#783]
`package pkg;

public class Snippet {
	
	int m1(R<X> c) {
		return switch (c) { // [1]
		case R<X>(X x, Y y) -> 1;
		case R<X>(Y y, X x) -> 2;
		
		};
	}
}

class X {}
class Y extends X {}
record R<T> (T x, T y) {}`

[1] has an error: An enhanced switch statement should be exhaustive; a default label expected

A quick fix should be provided to add the missing default case.

**Comment by stephan-herrmann** [comment]
> Documenting [eclipse-jdt/eclipse.jdt.ui#783](https://github.com/stephan-herrmann/eclipse.platform.releng.aggregator/commit/b9ccb9adfbeac971cd1fee18941c3a83bddb0602) 

wrong reference, sorry.
