### ISSUE TITLE
Clean Up: "Convert to enhanced 'for' loops" produces wrong code

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#798]
using the cleanup on jdt.core leads to many compilation errors.
"Duplicate local variable"
"The import is never used" 
...

Most notably on org.eclipse.pde.internal.core.builders.ExtensionsErrorReporter.validateMaxElementMult(Element, ISchemaElement)
where using the the same variable name twice would perform a wrong call:
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/21314bad-a5de-480f-a3ab-25d5c2aea796)

**Comment by vogella** [comment]
IIRC from an earlier discussion with @jjohnstn the clean-up of import is not include in each and every cleanup but available as separate clean-up. Not sure if you tick both clean-ups if that does the right thing or if you need to run the clean-up of imports after the other one.

**Comment by jjohnstn** [comment]
Please open a separate issue regarding the imports.
