### ISSUE TITLE
Move LTK from JDT to Platform?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-jdt/eclipse.jdt.ui#851]
I think the LTK bundle would reach more of their target audience if being moved into eclipse.platform.ui GitHub repo.
Would it be OK for JDT project to get rid of those?
If there is consensus, I volunteer in taking care of this refactoring.

**Comment by vogella** [comment]
IIRC this was already planned and agreed upon in the past in the PMC but no one did the actual work. Same for the spell checker in JDT.

I think CDT has made copies of the spell checker and maybe also of LTK, cc @jonahgraham maybe also PDT? cc @zulus

**Comment by mickaelistria** [comment]
I didn't find any reference to that topic in https://github.com/eclipse-platform/.github/wiki/PMC-Meeting-minutes or earlier wiki PMC meeting notes after 2017 (I didn't find later). I searched for "LTK" and "refact" without a clear hit. Do you think you can find a note about it?

**Comment by jonahgraham** [comment]
> I think CDT has made copies of the spell checker and maybe also of LTK

CDT does [have a copy of spell checker](https://github.com/eclipse-cdt/cdt/tree/main/core/org.eclipse.cdt.ui/src/org/eclipse/cdt/internal/ui/text/spelling) - but AFAIK we use LTK provided by JDT: ([require org.eclipse.ltk.core in our manifests](https://github.com/eclipse-cdt/cdt/blob/a92b90a4c8f50a0c435a51c6f9e13971d0beeaf3/core/org.eclipse.cdt.core/META-INF/MANIFEST.MF#L142)) - that isn't to say we haven't copied parts of it as I am sure over time we have. CDT has copied lots of JDT stuff in the past.

**Comment by zulus** [comment]
> I think CDT has made copies of the spell checker and maybe also of LTK, cc @jonahgraham maybe also PDT? cc @zulus

Only small (engine integration parts) from JDT are copied (in WTP SSE and DLTK) for now we just rely on available ISpellingEngine, so PHP EPP package haven't any

LTK is used directly from JDT, Long time ago I was surprised when realize it isn't part of platform ;)

**Comment by vogella** [comment]
At least Dani gave his OK for this move based on your request from 2017 :-) https://www.eclipse.org/lists/eclipse-dev/msg10519.html

**Comment by mickaelistria** [comment]
Thanks, that's enough support to let me start this task.
