### ISSUE TITLE
Javadocs tag completions do not show up when JDK 21 compliance is selected

### ISSUE THREAD

**Issue by agentgt** [eclipse-jdt/eclipse.jdt.ui#879]
To reproduce:

1. Create project with JDK 21 compile
2. Go to a method with and create a javadoc comment
3. Type `@` and do ctrl+space (completion) nothing will show up.
4. Switch the project to anything below JDK 21 and completion will come back.

**Comment by akurtakov** [comment]
This one is fixed.
