### ISSUE TITLE
Test projects are being imported when using the "official" Oomph installation

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-jdt/eclipse.jdt.ui#903]
See https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382210377

When using this installer, some Test projects are being added to the WS (see [this other comment](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/902#discussion_r1382172743))

@merks fyi

**Comment by merks** [comment]
The assertion of the issue title does not appear to be true.  In my SDK workspace, which includes the JDT setup, you can see that the source locator property is set to not consider nested projects and a manual "import projects" on the clone shows that a bunch of nested projects are not yet imported into the workspace.

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/208716/f3b53230-764c-4ffc-8e60-83253648cf16)

So I don't think it is the Oomph setup that did the importing of those projects.

**Comment by fedejeanne** [comment]
I tested again in **Windows** and the configuration seems fine: the folders are checked out from GH but they are not added as projects so I don't get any findings in the _Problems_ view 👍 
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/2205684/b5edc420-2a39-4c6b-a70a-be39e2c8e723)

But still, I would like to test it out on **Mac** before we close this issue (I don't have it on me right now) since that's where the error happened. 

@merks do you think this could be related to some kind of caching issue? I usually don't develop on my Mac so chances are that the caches there are totally outdated. BTW I followed [your instructions](https://github.com/eclipse-equinox/p2/pull/349#discussion_r1373044370) when I installed the (faulty) Eclipse in my Mac and I will do so tomorrow when I test it again :)

**Comment by fedejeanne** [comment]
Same thing in my Mac, the error is not reproducible...

I don't know how I got those "projects" imported into my WS, I must have cloned the Git Repos after the installation and wrongly searched for nested projects and forgotten about it.

@merks sorry for the confusion and thank you for your support!
