### ISSUE TITLE
Switch back to "Completion inserts" instead of "Completion overrides" as default

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#911]
I used to be one of or THE driver (don't remember exactly) to switch code completion to "Completion overrides".

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/139910/1cb02906-5a20-4e05-8362-41c1e4c8a7f4)

IIRC @rgrunber said somewhere at a later point that he preferred the old setting. Not sure if @jjohnstn issued an opinion on this in the past. (Please correct me if I remember wrong).

These days I find the replacement highly annoying, maybe because I use more and more builder API, like we have in Jface. I also see my IDE trainees struggling with the current code completion behavior and it is not intuitive that you can toogle this with holder CNTR to new users.

WDYT? Could / should we switch back to the old setting?

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/139910/6aa55a40-824b-4772-976f-f4cd18b7993c)

**Comment by vogella** [comment]
I stand corrected, both behaviors are similar annoying.

I frequently have to change a method name using the same parameters, e.g. I have

```
				partService.createPart(detail, EPartService.PartState.ACTIVATE);
```
which I want to change to 

```
				partService.showPart(detail, EPartService.PartState.ACTIVATE);

```

So I move to `partService.` start typing show hit code completion and get "broken" output. 

With override:

```
				partService.showPart(detail, null)
```
With insert

```
				partService.showPart(detail, null)(detail, EPartService.PartState.ACTIVATE);

```

So I close this one, both proposals are not want I would like to have.

**Comment by humphreygao** [comment]
It would be good if the Java Editor choose the correct behavior automatically.
