### ISSUE TITLE
Test runner runs more than selected

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-jdt/eclipse.jdt.ui#920]
Originally raised as https://github.com/eclipse-platform/eclipse.platform/issues/848: If multiple source folders exists and contain the same package, then launching one of the source folders as test results in the tests from _all_ source folders to be launched (only for packages that are contained in the first source folder).
Root cause is that we send only the package name to the remote runner process, see https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/34f6473dbf659c47714111393ea2b085902af54f/org.eclipse.jdt.junit.core/src/org/eclipse/jdt/junit/launcher/JUnitLaunchConfigurationDelegate.java#L466. We would need to collect all test classes instead, if multiple source folders exist (like done some lines deeper in the code).

**Comment by jukzi** [comment]
@erik-brangs thanks for contributing to the Eclipse IDE
