### ISSUE TITLE
Code Minings disappear at certain scroll positions

### ISSUE THREAD

**Issue by MahatmaFatalError** [eclipse-jdt/eclipse.jdt.ui#922]
Regression since Eclipse 2023-09.

The inline code mining labels disappear at random scroll positions.

Please see gif
![Screen Recording 2023-11-13 at 16 16 08](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/776825/957e4caa-151f-4776-8533-5682d7b86bf4)

Version:  / STS 4.20.1.RELEASE
Build Id: 202310260003
org.eclipse.jdt.feature.group 3.19.200.v20230903-1000

**Comment by iloveeclipse** [comment]
Should be already fixed in 4.30, can't find right now the right ticket to link
