### ISSUE TITLE
Support @Suite from JUnit5

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#93]
If I try to use @Suite from latest JUnit Jupiter the context menu to run tests is not available.
See https://howtodoinjava.com/junit5/junit5-test-suites-examples/

To test:

- Open org.eclipse.e4.ui.tests.css.core.CssCoreTestSuite from platform.ui repo and replace @RunWith(JUnitPlatform.class)
 with @Suite
- Right-click on the class and see that run and JUnit test is not available

![image](https://user-images.githubusercontent.com/139910/172578975-149be1a4-3179-451a-92a1-5f4c27bc7951.png)

**Comment by ktatavarthi** [comment]
@jjohnstn is this issue a continuation of 
- [Bug 576995](https://bugs.eclipse.org/bugs/show_bug.cgi?id=576995) - [junit 5] Add @Suite support from JUnit 5.8.1

Please add your comments here.

**Comment by jjohnstn** [comment]
Looking into this, it seems there is some requirement for the suite name to start with the prefix "Test".  If I rename the file to be TestCssCoreTestSuite, it works.  I need to look at where the filtering is taking place and why it isn't looking at the annotation.

**Comment by jjohnstn** [comment]
I have just installed the new EPP for Eclipse Committers 2022-06 and now it works fine in a child Eclipse without a need for a rename. 

I have the following additional change to MANIFEST.MF

- org.junit.platform.suite.api;bundle-version="1.1.0"
+ org.junit.platform.suite.api;bundle-version="1.1.0",
+ org.junit.platform.suite.engine;bundle-version="1.8.1",
+ org.junit.jupiter.engine;bundle-version="5.8.1"

There is cached information in the TestKindRegistry which would explain why a rename fixed the problem for me and it works today after restarting.  Could you add the changes above and restart with -clean and see if it works for you?

**Comment by vogella** [comment]
Thanks @jjohnstn for looking into this. I'm still not able to run the test suite. I pushed the example to https://github.com/eclipse-platform/eclipse.platform.ui/pull/158 to make it easier to check what is wrong. My version range for the MANIFEST.MF is different, I picked whatever the Eclipse SDK provides as version.


```
 org.junit.jupiter.api;bundle-version="5.8.1",
 org.junit.platform.suite.api;bundle-version="1.8.1",
 org.junit.platform.suite.engine;bundle-version="1.8.1",
 org.junit.jupiter.engine;bundle-version="5.8.1"
```

**Comment by fedejeanne** [comment]
This issue seems to be fixed

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/2205684/ab76e3d3-af1d-498e-90b8-58a595096bfb)
