### ISSUE TITLE
[15] Textblock cleanup does not blockify every possibility

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#935]
"Convert String concatenation to Text Block" should for example also blockify the Strings in 
org.eclipse.jdt.core.tests.model.JavaSearchBugs16Tests.testBug570246_002()
![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/30902922-9692-4891-9ea3-2ac99ed4ea07)

![image](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/51790620/5ad1c484-a971-4c04-baf1-e70d5325e948)

**Comment by vogella** [comment]
I also get an NPE trying to run this clean-up see #950

**Comment by jukzi** [comment]
thanks @jjohnstn
