### ISSUE TITLE
Dont show children for JUnit 5 @TestTemplate tests that ran only once

### ISSUE THREAD

**Issue by trancexpress** [eclipse-jdt/eclipse.jdt.ui#945]
The JUnit view displays `@TestTemplate` JUnit 5 tests with an extra `TestSuiteElement`, that contains the template executions.

E.g. the following test code:

```
public class TestTemplatesJunit5 {

	@RepeatedTest(value = 1)
	public void test1() throws Exception {
		Thread.sleep(500);
	}

	@RepeatedTest(value = 2)
	public void test2() throws Exception {
		Thread.sleep(500);
	}

	@Test
	public void test3() throws Exception {
		Thread.sleep(500);
	}
}
```

Results in this JUnit view state: 

![junit_view_repeated_test_single_run](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/24752155/966ba0f1-d093-4c08-9f98-32f91915309a)

For `test.TestTemplatesJunit5.test1()` this extra `TestSuiteElement` results in only noise. E.g. when repeating failed tests (see https://github.com/artsok/rerunner-jupiter), often there will be many (or all) tests in a test case that have this structure single child in a test suite.

Ideally we hide such `TestSuiteElement` tree elements with only a single `TestCaseElement` child. E.g. the view could look like this:

![junit_view_repeated_test_improvement](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/24752155/a0dc3626-5719-4c18-a47c-5d8f6110bd08)

**Comment by iloveeclipse** [comment]
Fix was reverted via https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1203, reopening.
