### ISSUE TITLE
request: pomless builds

### ISSUE THREAD

**Issue by jukzi** [eclipse-jdt/eclipse.jdt.ui#948]
Is it possible to make the JDT plugins pomless so that i don't need to increase version in pom.xml too? 
Any Volunteer?

**Comment by vogella** [comment]
Sure, I think I tried this in past but got no reviews. I might be wrong but if you would help with the review I can do the work.

**Comment by jukzi** [comment]
i'll sponsor review

**Comment by vogella** [comment]
Interested in getting the same for JDT.core @jukzi?

**Comment by vogella** [comment]
Please core this issue,  I cannot close it.

**Comment by vogella** [comment]
@jukzi now I'm happy to help with releng simplications in JDT...

**Comment by jukzi** [comment]
@vogella is still have to update some poms
for example org.eclipse.jdt.core.tests.builder/pom.xml - is it possible to get rid of all poms, please?

**Comment by vogella** [comment]
@jukzi I currently do not plan to work on JDT for various personal reasons, most of them I discussed with you already via private email.
