### ISSUE TITLE
Eclipse Splash picture upside-down on SONOMA

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-jdt/eclipse.jdt.ui#962]
![EclipseSplash](https://github.com/eclipse-jdt/eclipse.jdt.ui/assets/121790387/5d6bae6d-9954-4d05-a5de-d46ff339a9bb)

I just upgraded to SONOMA 14.1.2
While testing all applications I noticed that the Eclipse splash was upside down, 
while the IDE itself seems to work without a problem.

Is this intentional? If so, how did you do that?

;JOOP!

**Comment by noopur2507** [comment]
This has been fixed for the Eclipse 4.30 release build.
