### ISSUE TITLE
Open Resource - Show in -> Project Explorer missing in Java perspectives

### ISSUE THREAD

**Issue by vogella** [eclipse-jdt/eclipse.jdt.ui#97]
Could you also add the project explorer to the show-in list of the Java perspective and the Debug perspective?

![image](https://user-images.githubusercontent.com/139910/173020837-8f533b6c-0c59-4bf8-833b-a192cb69ea7a.png)

**Comment by vogella** [comment]
cc @[jukzi](https://github.com/jukzi)

**Comment by Bananeweizen** [comment]
It's available in all 3 Java perspectives, see https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/master/org.eclipse.jdt.ui/plugin.xml#L613. I've opened a PR on platform.debug for the Debug perspective.

**Comment by ktatavarthi** [comment]
`Open Resource - Show in -> Project Explorer` is available in Java Perspective. @vogella I am not able to reproduce the issue.

**Comment by vogella** [comment]
Solved via https://github.com/eclipse-platform/eclipse.platform.debug/pull/27 for the debug perspective. Thanks @Bananeweizen 

@ktatavarthi yes, sorry, it is already available for Java perspective, look like I was in debug perspective which @Bananeweizen now enhanced.
